/**
 * Bounded-concurrency map over async work — the fix for the extension's
 * dominant startup cost. `ModuleIndexer`/`NamingIssuesIndex` used to read
 * thousands of files with a plain `for (const f of files) { await read(f) }`
 * loop: each file's open+read had to fully finish before the next one even
 * started. That's invisible on a warm file cache (sub-millisecond per file),
 * but on a *cold* one — right after a real WorkspaceConsole build rewrites
 * `Autogenerated/Src` wholesale, or after a reboot — every first-time file
 * open pays real latency (most likely antivirus real-time scanning; the
 * exact cause doesn't matter for the fix). Measured directly against two
 * real installs: a serial cold scan of ~4,000 `Autogenerated/Src` files took
 * 88 seconds on one machine/install combination vs. 1.3-5.6 seconds for the
 * same files read with this pool — multiplied across every file category
 * (`Autogenerated/Src` + `Pkg/**\/Schemas` + `Resources/ui/BPMSoft` +
 * `conf/content`), this is what turns into a multi-minute activation hang.
 * Concurrency beyond ~8 gave no further improvement in that same
 * measurement (Node's libuv thread pool backing `fs.promises.*` defaults to
 * 4 background threads and an extension can't raise that at runtime — it's
 * an env var libuv only reads once, before the process starts) — 16 is
 * comfortably past that ceiling with no downside.
 */
export const DEFAULT_FS_CONCURRENCY = 16;

/**
 * Runs `worker` over every item in `items`, at most `concurrency` in flight
 * at once, and returns results in the same order as `items` (independent of
 * completion order) — a caller that doesn't care about order can still rely
 * on `results[i]` corresponding to `items[i]`, which keeps callers simple.
 */
export async function pMap<T, R>(
	items: readonly T[],
	worker: (item: T, index: number) => Promise<R>,
	concurrency: number = DEFAULT_FS_CONCURRENCY
): Promise<R[]> {
	const results: R[] = new Array(items.length);
	if (!items.length) {
		return results;
	}
	let next = 0;
	async function run(): Promise<void> {
		while (true) {
			const i = next++;
			if (i >= items.length) {
				return;
			}
			results[i] = await worker(items[i], i);
		}
	}
	const workerCount = Math.max(1, Math.min(concurrency, items.length));
	await Promise.all(Array.from({ length: workerCount }, run));
	return results;
}
