import { IndexedModule } from "./types";

export function normalizeFilePath(filePath: string): string {
	return filePath.replace(/\\/g, "/");
}

export function packageLabel(filePath: string): string {
	const norm = normalizeFilePath(filePath);
	const pkg = norm.match(/\/Pkg\/([^/]+)\//);
	if (pkg) {
		return `Pkg/${pkg[1]}`;
	}
	const auto = norm.match(/\/Autogenerated\/Src\/[^/]+\.([^.]+)\.js$/i);
	if (auto) {
		return `Autogenerated/${auto[1]}`;
	}
	if (/\/Autogenerated\//i.test(norm)) {
		return "Autogenerated";
	}
	const ui = norm.match(/\/Resources\/ui\/BPMSoft\/(.+)\.js$/i);
	if (ui) {
		return `ui/${ui[1]}`;
	}
	return filePath;
}

/** Same replacing schema in Pkg and Autogenerated/{Name}.{Package}.js */
export function schemaOriginKey(filePath: string): string {
	const norm = normalizeFilePath(filePath);
	const pkg = norm.match(/\/Pkg\/([^/]+)\/Schemas\/([^/]+)\//i);
	if (pkg) {
		return `${pkg[2]}::${pkg[1]}`;
	}
	const auto = norm.match(/\/Autogenerated\/Src\/([^/]+)\.([^/.]+)\.js$/i);
	if (auto) {
		return `${auto[1]}::${auto[2]}`;
	}
	return norm;
}

export function preferPkgHit(
	a: { module: IndexedModule },
	b: { module: IndexedModule }
): boolean {
	const aPkg = /\/Pkg\//i.test(normalizeFilePath(a.module.filePath));
	const bPkg = /\/Pkg\//i.test(normalizeFilePath(b.module.filePath));
	return aPkg && !bPkg;
}

export function inheritdocTarget(mod: IndexedModule): string {
	if (mod.alternateClassName) {
		return mod.alternateClassName;
	}
	if (mod.className) {
		return mod.className;
	}
	if (mod.name.includes(".")) {
		return mod.name;
	}
	return `BPMSoft.${mod.name}`;
}

export function isPageSchema(mod: IndexedModule): boolean {
	return mod.kind === "page";
}

export function mixinIndexKeys(className: string): string[] {
	const keys = [className];
	const short = className.replace(/^BPMSoft\./, "");
	if (short !== className) {
		keys.push(short);
	}
	return keys;
}
