import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import { parseAmdModule } from "../parse/amdParser";
import { SymbolIndex } from "./SymbolIndex";
import { buildPlatformStubs } from "../stubs/platformGlobals";
import { buildExtStubs } from "../stubs/extGlobals";
import {
	resolveAppLayouts,
	walkJsFiles,
	BpmsoftAppLayout
} from "./workspaceLayout";

export class ModuleIndexer {
	constructor(private readonly index: SymbolIndex) {}

	async rebuild(progress?: vscode.Progress<{ message?: string }>): Promise<number> {
		this.index.clearModules();
		const folders =
			vscode.workspace.workspaceFolders?.map((f) => f.uri.fsPath) || [];
		this.index.setWorkspaceRoots(folders);
		const layouts = resolveAppLayouts(folders);

		const enableStubs = vscode.workspace
			.getConfiguration("bpmsoft")
			.get<boolean>("enablePlatformStubs", true);
		if (enableStubs) {
			this.index.setPlatformStubs(buildPlatformStubs(folders));
			this.index.setExtStubs(buildExtStubs(folders));
		} else {
			this.index.setPlatformStubs([]);
			this.index.setExtStubs(buildExtStubs(folders));
		}

		let files = this.collectIndexFiles(layouts);
		if (!files.length) {
			files = await this.collectViaWorkspaceGlobs();
		}

		let count = 0;
		for (const filePath of files) {
			progress?.report({ message: path.basename(filePath) });
			if (await this.indexFile(filePath)) {
				count++;
			}
		}
		return count;
	}

	/**
	 * Index Pkg + Autogenerated + platform UI using resolved app paths,
	 * so opening Configuration / Pkg / {Package} still sees the full tree.
	 */
	private collectIndexFiles(layouts: BpmsoftAppLayout[]): string[] {
		const seen = new Set<string>();
		const out: string[] = [];

		const add = (filePath: string) => {
			const key = path.normalize(filePath);
			if (seen.has(key)) {
				return;
			}
			seen.add(key);
			out.push(key);
		};

		for (const layout of layouts) {
			if (layout.pkgRoot) {
				for (const file of walkJsFiles(layout.pkgRoot, (p) =>
					/\/Schemas\/.+\.js$/i.test(p.replace(/\\/g, "/"))
				)) {
					add(file);
				}
			}
			if (layout.autogeneratedRoot) {
				const src = path.join(layout.autogeneratedRoot, "Src");
				for (const file of walkJsFiles(src, (p) => p.endsWith(".js"))) {
					add(file);
				}
			}
			if (layout.resourcesRoot) {
				const ui = path.join(layout.resourcesRoot, "ui", "BPMSoft");
				for (const file of walkJsFiles(ui, (p) => p.endsWith(".js"))) {
					add(file);
				}
			}
		}
		return out;
	}

	private async collectViaWorkspaceGlobs(): Promise<string[]> {
		const cfg = vscode.workspace.getConfiguration("bpmsoft");
		const pkgGlob = cfg.get<string>("pkgGlob", "**/Pkg/**/Schemas/**/*.js");
		const autoGlob = cfg.get<string>(
			"autogeneratedGlob",
			"**/Autogenerated/Src/*.js"
		);
		const uiGlob = cfg.get<string>(
			"platformUiGlob",
			"**/Resources/ui/BPMSoft/**/*.js"
		);
		const globs = [pkgGlob, autoGlob, uiGlob].filter(
			(g) => g && g.trim().length > 0
		);
		const seen = new Set<string>();
		const out: string[] = [];
		for (const glob of globs) {
			const uris = await vscode.workspace.findFiles(glob, "**/node_modules/**");
			for (const uri of uris) {
				if (seen.has(uri.fsPath)) {
					continue;
				}
				seen.add(uri.fsPath);
				out.push(uri.fsPath);
			}
		}
		return out;
	}

	async indexFile(filePath: string): Promise<boolean> {
		try {
			const source = await fs.promises.readFile(filePath, "utf8");
			const mod = parseAmdModule(source, filePath);
			if (!mod) {
				this.index.removeByPath(filePath);
				return false;
			}
			this.index.upsertModule(mod);
			return true;
		} catch {
			this.index.removeByPath(filePath);
			return false;
		}
	}

	removeFile(filePath: string): void {
		this.index.removeByPath(filePath);
	}

	matchesGlob(filePath: string): boolean {
		const normalized = filePath.replace(/\\/g, "/");
		return (
			/\/Pkg\/.+\/Schemas\/.+\.js$/i.test(normalized) ||
			/\/Autogenerated\/Src\/.+\.js$/i.test(normalized) ||
			/\/Resources\/ui\/BPMSoft\/.+\.js$/i.test(normalized)
		);
	}
}
