/**
 * NLog target and layout-renderer reference data, frozen from the same JSON
 * that backs the official interactive config explorer at nlog-project.org/config
 * (source: github.com/NLog/NLog.github.io, config/targets.json + config/layout-renderers.json,
 * pulled 2026-09-08). Used by NlogTargetsWizardPanel to offer a searchable,
 * described type picker when adding a target instead of hand-typing an
 * xsi:type value, and as static reference material (not live autocomplete)
 * for layout renderers.
 *
 * BPMSoft installs observed both ship NLog core 5.4.0 (NLog.Web.AspNetCore
 * 4.8.4, NLog.Extensions.Logging 1.5.1) - this data reflects the current
 * NLog docs as of that version line (e.g. Database/ElasticSearch/Kafka/
 * Loki/Syslog/RabbitMQ targets already split into their own NuGet packages,
 * matching the separate NLog.*.dll files these installs actually carry).
 *
 * Regenerate by re-downloading those two JSON files and re-running the
 * generation one-liner in this repo's implementation history - not done on
 * any schedule, since NLog's own config surface changes rarely.
 */

export interface NlogCatalogEntry {
	name: string;
	description: string;
	category: string;
	/** True for a wrapper/compound target that wraps another target (or a group of them) rather than writing log events itself. Meaningless for layout renderers. */
	wrapper?: boolean;
	/** NuGet package name when not part of the NLog core package. */
	package?: string;
	/** Free-text version/platform note straight from the source docs, e.g. "For NLog 5.0: NLog.Database nuget package required". */
	platformNotes?: string;
	/** True for a third-party/community target or renderer, not maintained in the core NLog repo. */
	external?: boolean;
}

export const NLOG_TARGET_TYPES: NlogCatalogEntry[] = [
	{"name":"Chainsaw","description":"Sends log messages to the remote instance of Chainsaw application from log4j.","category":"Integrations (GUI tools)","package":"NLog.Targets.Network","platformNotes":"For NLog 6.0: NLog.Targets.Network nuget package required"},
	{"name":"ColoredConsole","description":"Writes log messages to the console with customizable coloring.","category":""},
	{"name":"Console","description":"Writes log messages to the console.","category":""},
	{"name":"Database","description":"Writes log messages to the database using an ADO.NET provider.","category":"Databases","package":"NLog.Database","platformNotes":"For NLog 5.0: NLog.Database nuget package required"},
	{"name":"DebugSystem","description":"Sends log messages through System.Diagnostics.Debug.","category":"Integrations","platformNotes":"For NLog 4.7 (and older) then use OutputDebugString-target instead"},
	{"name":"Debug","description":"Mock target - useful for testing.","category":"Programmatically"},
	{"name":"Debugger","description":"Writes log messages to the attached debugger through System.Diagnostics.Debugger.Log","category":"Integrations"},
	{"name":"EventLog","description":"Writes log message to the Windows Event Log.","category":"Integrations","package":"NLog.WindowsEventLog","platformNotes":"For .NET Standard: NLog.WindowsEventLog nuget package required"},
	{"name":"File","description":"Writes log messages to one or more files.","category":""},
	{"name":"Atomic File","description":"Writes log messages to one or more files using O_APPEND.","category":"","package":"NLog.Targets.AtomicFile"},
	{"name":"GZip File","description":"Writes log messages to one or more files using GZipStream.","category":"","package":"NLog.Targets.GZipFile"},
	{"name":"HTTP","description":"Sends messages to a designated HTTP target using POST by default. Combined with JSON Formatter supports Splunk.","category":"Integrations","package":"NLog.Targets.Http","external":true},
	{"name":"HttpClient","description":"Sending log messages to HTTP or HTTPS endpoint, with support for batching and compression, and supports Splunk.","category":"Integrations","package":"NLog.Targets.HttpClient","external":true},
	{"name":"LogReceiverService","description":"Sends log messages to a NLog Receiver Service (using WCF or Web Services).","category":"Integrations","package":"NLog.WCF","platformNotes":"For NLog 5.0 and .NET Standard: NLog.WCF nuget package required"},
	{"name":"Mail","description":"Sends log messages with SmtpClient using SMTP protocol or pickup folder.","category":"Integrations","package":"NLog.Targets.Mail","platformNotes":"For NLog 6.0: NLog.Targets.Mail nuget package required"},
	{"name":"MailKit","description":"Sends log messages with MailKit using SMTP protocol or pickup folder.","category":"Integrations","package":"NLog.MailKit"},
	{"name":"Memory","description":"Writes log messages to an ArrayList in memory for programmatic retrieval.","category":"Programmatically"},
	{"name":"MethodCall","description":"Calls the specified static method on each log message and passes contextual parameters to it.","category":"Programmatically"},
	{"name":"Network","description":"Sends log messages over the network using TCP / UDP / SSL / TLS.","category":"Integrations","package":"NLog.Targets.Network","platformNotes":"For NLog 6.0: NLog.Targets.Network nuget package required"},
	{"name":"NLogViewer","description":"Sends log messages to the remote instance of NLog Viewer.","category":"Integrations (GUI tools)","package":"NLog.Targets.Network","platformNotes":"For NLog 6.0: NLog.Targets.Network nuget package required"},
	{"name":"Log4JXml","description":"Sends log messages to the remote instance of Log4JXml Receiver.","category":"Integrations","package":"NLog.Targets.Network"},
	{"name":"Null","description":"Discards log messages. Used mainly for debugging and benchmarking.","category":"Programmatically"},
	{"name":"OpenTelemetry","description":"Exports log events to an OpenTelemetry Collector or any OTLP/HTTP-compatible endpoint.","category":"Integrations","package":"NLog.Targets.OpenTelemetryHttp","external":true},
	{"name":"OtlpTarget","description":"Exports log events to OpenTelemetry EndPoint via the official OpenTelemetry SDK.","category":"Integrations","package":"NLog.Targets.OpenTelemetryProtocol","external":true},
	{"name":"OutputDebugString","description":"Outputs log messages through the OutputDebugString() Win32 API.","category":"Integrations","package":"NLog.OutputDebugString","platformNotes":"For NLog 5.0: NLog.OutputDebugString nuget package required"},
	{"name":"PerfCounter","description":"Updates specified Windows Performance Counter on each write.","category":"Integrations","package":"NLog.PerformanceCounter","platformNotes":"For NLog 5.0: NLog.PerformanceCounter nuget package required"},
	{"name":"Trace","description":"Sends log messages through System.Diagnostics.Trace.","category":"Integrations","package":"NLog.Targets.Trace","platformNotes":"For NLog 6.0: NLog.Targets.Trace nuget package required"},
	{"name":"WebService","description":"Calls the specified web service on each log message.","category":"Integrations","package":"NLog.Targets.WebService","platformNotes":"For NLog 6.0: NLog.Targets.WebService nuget package required"},
	{"name":"AsyncWrapper","description":"Provides asynchronous, buffered execution of target writes.","category":"Async and buffering","wrapper":true},
	{"name":"AutoFlushWrapper","description":"Causes a flush after each write on a wrapped target.","category":"Async and buffering","wrapper":true},
	{"name":"BufferingWrapper","description":"A target that buffers log events and sends them in batches to the wrapped target. Useful in combination with Mail target.","category":"Async and buffering","wrapper":true},
	{"name":"FallbackGroup","description":"Provides fallback-on-error.","category":"Filtering, throttling and error handling","wrapper":true},
	{"name":"FilteringWrapper","description":"Filters log entries based on a condition.","category":"Filtering, throttling and error handling","wrapper":true},
	{"name":"ImpersonatingWrapper","description":"Impersonates another user for the duration of the write.","category":"Security","wrapper":true,"package":"NLog.WindowsIdentity","platformNotes":"For NLog 5.0: NLog.WindowsIdentity nuget package required"},
	{"name":"LimitingWrapper","description":"Limits number of log events sent to target.","category":"Filtering, throttling and error handling","wrapper":true},
	{"name":"PostFilteringWrapper","description":"Filters buffered log entries based on a set of conditions that are evaluated on a group of events.","category":"Filtering, throttling and error handling","wrapper":true},
	{"name":"RandomizeGroup","description":"Sends log messages to a randomly selected target.","category":"Filtering, throttling and error handling","wrapper":true},
	{"name":"RepeatingWrapper","description":"Repeats each log event the specified number of times.","category":"Filtering, throttling and error handling","wrapper":true},
	{"name":"RetryingWrapper","description":"Retries in case of write error.","category":"Filtering, throttling and error handling","wrapper":true},
	{"name":"RoundRobinGroup","description":"Distributes log events to targets in a round-robin fashion.","category":"Filtering, throttling and error handling","wrapper":true},
	{"name":"SplitGroup","description":"Writes log events to all targets.","category":"Filtering, throttling and error handling","wrapper":true},
	{"name":"MSMQ","description":"Writes log message to the specified message queue handled by MSMQ.","category":"Integrations","package":"NLog.MSMQ","platformNotes":"For NLog 4.7 (and older) then NLog.Extended nuget package required"},
	{"name":"AspNetTrace","description":"Writes log messages to the ASP.NET trace.","category":"Integrations","package":"NLog.Web"},
	{"name":"AspNetBufferingWrapper","description":"Buffers log events for the duration of ASP.NET request and sends them down to the wrapped target at the end of a request.","category":"Async and buffering","wrapper":true,"package":"NLog.Web"},
	{"name":"FormControl","description":"Logs text to Windows.Forms.Control.Text property control of specified Name.","category":"Windows Forms","package":"NLog.Windows.Forms"},
	{"name":"MessageBox","description":"Pops up log messages as message boxes.","category":"Windows Forms","package":"NLog.Windows.Forms"},
	{"name":"RichTextBox","description":"Log text a Rich Text Box control in an existing or new form.","category":"Windows Forms","package":"NLog.Windows.Forms"},
	{"name":"ToolStripItem","description":"Logs text to Windows.Forms.ToolStripItem property control of specified Name","category":"Windows Forms","package":"NLog.Windows.Forms"},
	{"name":"Elmah","description":"Logs to Elmah","category":"Integrations","package":"NLog.Elmah"},
	{"name":"ETW","description":"Log to Event Tracing for Windows (ETW)","category":"Integrations","package":"NLog.ETW"},
	{"name":"Amazon SNS","description":"Writes NLog messages to Amazon SNS","category":"Integrations (Cloud)","package":"NLog.Targets.SNS","external":true},
	{"name":"Amazon SQS","description":"Writes NLog messages to Amazon SQS","category":"Integrations (Cloud)","package":"NLog.Targets.SQS","external":true},
	{"name":"Microsoft Azure Data Explorer","description":"Writes NLog messages to Azure Data Explorer (Kusto) cluster ","category":"Integrations (Cloud)","package":"NLog.Azure.Kusto","external":true},
	{"name":"Microsoft Azure Table Storage","description":"Writes NLog messages to Azure TableStorage","category":"Integrations (Cloud)","package":"NLog.Extensions.AzureTableStorage","external":true},
	{"name":"Microsoft Azure ApplicationInsights","description":"Writes NLog messages to Microsoft ApplicationInsights","category":"Integrations (Cloud)","package":"Microsoft.ApplicationInsights.NLogTarget","external":true},
	{"name":"Microsoft Azure AppCenter","description":"Writes NLog messages to Microsoft Visual Studio AppCenter with Azure","category":"Integrations (Cloud)","package":"NLog.Targets.AppCenter","external":true},
	{"name":"Microsoft DiagnosticSource","description":"DiagnosticListenerTarget as a named source of instrumentation events","category":"Integrations","package":"NLog.DiagnosticSource","external":true},
	{"name":"Elastic Common Schema","description":"Writes logs directly to Elasticsearch or Elastic Cloud using the Elastic Common Schema (ECS)","category":"Integrations","package":"Elastic.NLog.Targets","external":true},
	{"name":"Elastic Search","description":"Writes to Elastic Search servers","category":"Integrations","package":"NLog.Targets.ElasticSearch","external":true},
	{"name":"elmah.io","description":"Sends logs to https://elmah.io","category":"Integrations (Cloud)","package":"elmah.io.nlog","external":true},
	{"name":"blipboard.io","description":"Sends logs to the Blipboard","category":"Integrations (Cloud)","package":"Bliptech.Blipboard.NLog","external":true},
	{"name":"ExceptionLess","description":"Writes NLog messages to https://www.exceptionless.com","category":"Integrations (Cloud)","package":"Exceptionless.NLog","external":true},
	{"name":"Fluentd","description":"Writes NLog messages to Fluentd","category":"Integrations","package":"NLog.Targets.Fluentd","external":true},
	{"name":"Gelf","description":"Writes NLog messages to GrayLog - Gelf UDP / TCP / HTTP","category":"Integrations","package":"NLog.Targets.Network","external":true},
	{"name":"NLog.Targets.Gelf","description":"Writes NLog messages to GrayLog - Gelf UDP","category":"Integrations","package":"NLog.Targets.Gelf","external":true},
	{"name":"Gelf4NLog","description":"Writes NLog messages to GrayLog - Gelf UDP","category":"Integrations","package":"Gelf4NLog.Target","external":true},
	{"name":"NLog.Gelf","description":"Writes NLog messages to GrayLog - Gelf UDP / HTTP","category":"Integrations","package":"NLog.Gelf","external":true},
	{"name":"GrayNLog","description":"Write log messages to Graylog - Gelf UDP.","category":"Integrations","package":"GrayNLog","external":true},
	{"name":"GraylogHttp","description":"Write log messages to Graylog - Gelf HTTP.","category":"Integrations","package":"NLog.Targets.GraylogHttp","external":true},
	{"name":"GelfAspNetCore","description":"Write log messages to Graylog - Gelf UDP.","category":"Integrations","package":"NLog.Web.AspNetCore.Targets.Gelf","external":true},
	{"name":"InfluxDB","description":"Writes NLog messages to InfluxDB v2","category":"Databases","package":"NLog.Targets.InfluxDB","external":true},
	{"name":"Glimpse","description":"Show NLog information in https://getglimpse.com/","category":"Integrations","package":"Glimpse.NLog","external":true},
	{"name":"GrowlNotify","description":"Sends logs via Growl for Windows (http://www.growlforwindows.com/gfw/) a desktop notification system.","category":"Integrations (GUI tools)","package":"NLog.Growl","external":true},
	{"name":"LiveSwitch","description":"Sends logs via named pipes to a local service that you can monitor in real-time with a UI","category":"Integrations (Cloud)","package":"LiveSwitch.NLog","external":true},
	{"name":"Loggly","description":"Writes NLog messages to https://www.loggly.com","category":"Integrations (Cloud)","package":"NLog.Targets.Loggly","external":true},
	{"name":"Logentries","description":"Writes NLog messages to https://www.logentries.com","category":"Integrations (Cloud)","package":"Logentries.nlog","external":true},
	{"name":"Loki","description":"Writes NLog messages to Grafana Loki https://github.com/grafana/loki","category":"Integrations (Cloud)","package":"NLog.Targets.Loki","external":true},
	{"name":"Loupe","description":"Writes NLog messages to Gibraltar Loupe Agent https://www.onloupe.com","category":"Integrations (Cloud)","package":"Loupe.Agent.NLog","external":true},
	{"name":"MongoDB","description":"Writes NLog messages to MongoDB","category":"Databases","package":"NLog.Mongo","external":true},
	{"name":"LiteDB","description":"Writes NLog messages to LiteDB","category":"Databases","package":"NLog.LiteDB","external":true},
	{"name":"Pushover","description":"Sends logs via (https://pushover.net/), an Android/iOS/Desktop  push notification system","category":"Integrations (Cloud)","package":"NLog.Targets.Pushover","external":true},
	{"name":"RabbitMQ","description":"Sends logs over a RabbitMQ message broker","category":"Integrations","package":"NLog.RabbitMQ.Target","external":true},
	{"name":"Raygun","description":"Writes NLog messages to www.raygun.com","category":"Integrations (Cloud)","package":"NLog.Raygun","external":true},
	{"name":"Redis","description":"Writes NLog messages to Redis","category":"Integrations","package":"NLog.Targets.Redis"},
	{"name":"ReflectInsight","description":"Writes NLog messages to https://www.reflectsoftware.com","category":"Integrations (Cloud)","package":"ReflectSoftware.Insight.Extensions.NLog","external":true},
	{"name":"RavenDB","description":"Writes NLog messages to RavenDB","category":"Databases","package":"NLog.Raven","external":true},
	{"name":"Sentry (Unified SDK)","description":"Official NLog integration for Sentry - Open-source error tracking that helps developers monitor and fix crashes in real time.","category":"Integrations (Cloud)","package":"Sentry.NLog","external":true},
	{"name":"Sentry (Raven sdk)","description":"Writes NLog messages to https://www.sentry.io","category":"Integrations (Cloud)","package":"NLog.Targets.Sentry3","external":true},
	{"name":"Seq","description":"Writes NLog messages to https://www.getseq.net","category":"Integrations (Cloud)","package":"NLog.Targets.Seq","external":true},
	{"name":"SignalR","description":"Writes NLog messages to a SignalR hub","category":"Integrations","package":"NLog.SignalR","external":true},
	{"name":"Splunk","description":"Writes NLog messages to Splunk","category":"Integrations","package":"NLog.Targets.Splunk","external":true},
	{"name":"Syslog","description":"Writes NLog messages to Syslog Server","category":"Integrations","package":"NLog.Targets.Network","external":true},
	{"name":"NLog.Targets.Syslog","description":"[Discontinued] Writes NLog messages to Syslog Server","category":"Integrations","package":"NLog.Targets.Syslog","external":true},
	{"name":"Amazon CloudWatch","description":"Writes NLog messages to Amazon CloudWatch Logs (AWS)","category":"Integrations (Cloud)","package":"AWS.Logger.NLog","external":true},
	{"name":"Microsoft Azure Blob Storage","description":"Batch writing of NLog messages to Azure BlobStorage","category":"Integrations (Cloud)","package":"NLog.Extensions.AzureBlobStorage","external":true},
	{"name":"Microsoft Azure DataTables Storage","description":"Batch writing of NLog messages to Azure Table Storage or Azure CosmosDb Tables","category":"Integrations (Cloud)","package":"NLog.Extensions.AzureDataTables","external":true},
	{"name":"Microsoft Azure EventHubs","description":"Batch writing of NLog messages to Azure Event Hubs","category":"Integrations (Cloud)","package":"NLog.Extensions.AzureEventHub","external":true},
	{"name":"Microsoft Azure Queue Storage","description":"Batch writing of NLog messages to Azure Queue Storage","category":"Integrations (Cloud)","package":"NLog.Extensions.AzureQueueStorage","external":true},
	{"name":"Microsoft Azure ServiceBus","description":"Batch writing of NLog messages to Azure Service Bus","category":"Integrations (Cloud)","package":"NLog.Extensions.AzureServiceBus","external":true},
	{"name":"Microsoft Azure EventGrid","description":"Writing of NLog messages to Azure Event Grid","category":"Integrations (Cloud)","package":"NLog.Extensions.AzureEventGrid/","external":true},
	{"name":"Microsoft Azure File System","description":"Write NLog messages to Microsoft Azure file system (file shares)","category":"Integrations (Cloud)","package":"NLog.Extensions.AzureFileSystem","external":true},
	{"name":"Google Logging","description":"Write NLog message to Google Cloud Logging StackDriver","category":"Integrations (Cloud)","package":"Google.Cloud.Logging.NLog","external":true},
	{"name":"R7 InsightOps","description":"Writes NLog messages to Rapid7 InsightOps / Logentries","category":"Integrations (Cloud)","package":"r7Insight.nlog","external":true},
	{"name":"Logify","description":"Writes NLog messages to https://logify.devexpress.com","category":"Integrations (Cloud)","package":"Logify.Alert.NLog","external":true},
	{"name":"Logzio","description":"Writes NLog messages to https://logz.io/","category":"Integrations (Cloud)","package":"Logzio.DotNet.NLog","external":true},
	{"name":"Rollbar.NET","description":"Writes NLog messages to https://rollbar.com/","category":"Integrations (Cloud)","package":"Rollbar.PlugIns.NLog","external":true},
	{"name":"Stackify Retrace","description":"Writes NLog messages to https://stackify.com/retrace/","category":"Integrations (Cloud)","package":"NLog.Targets.Stackify","external":true},
	{"name":"SumoLogic","description":"Writes NLog messages to https://www.sumologic.com/","category":"Integrations (Cloud)","package":"SumoLogic.Logging.NLog","external":true},
	{"name":"NLog.Targets.MicrosoftTeams","description":"Writes NLog messages to Microsoft Teams Channel via O365 Webhook Connector","category":"Integrations (Cloud)","package":"NLog.Targets.MicrosoftTeams","external":true},
	{"name":"Microsoft Teams","description":"Writes NLog messages to MS Teams incoming Webhook connectors","category":"Integrations (Cloud)","package":"NLog.Targets.Teams","external":true},
	{"name":"Ntfy.sh","description":"Writes NLog messages to a topic on https://ntfy.sh/","category":"Integrations","package":"MichelMichels.NLog.Targets.Ntfy","external":true},
	{"name":"Bugsnag","description":"Writes NLog messages to https://www.bugsnag.com","category":"Integrations (Cloud)","package":"NLog.Targets.Bugsnag","external":true},
	{"name":"Kafka","description":"Writes NLog messages to Kafka Queue Topic","category":"Integrations","package":"NLog.Targets.KafkaAppender","external":true},
	{"name":"Nats","description":"Writes NLog messages to NATS messaging server","category":"Integrations","package":"NLog.Targets.Nats","external":true},
	{"name":"ActiveMQ","description":"Writes NLog messages using Apache ActiveMQ NMS native OpenWire protocol","category":"Integrations","package":"NLog.Targets.ActiveMQ","external":true}
];

export const NLOG_LAYOUT_RENDERERS: NlogCatalogEntry[] = [
	{"name":"activityid","description":"Puts into log a System.Diagnostics trace correlation id.","category":"Context information"},
	{"name":"db-null","description":"Render DbNull for the database","category":""},
	{"name":"all-event-properties","description":"Log all event context data.","category":"Context information"},
	{"name":"appdomain","description":"Current app domain.","category":"Processes, threads and assemblies"},
	{"name":"assembly-version","description":"The version of the executable in the default application domain.","category":"Processes, threads and assemblies"},
	{"name":"basedir","description":"The current application domain's base directory.","category":"Files and directories"},
	{"name":"dir-separator","description":"The the OS dependent directory separator.","category":"Files and directories"},
	{"name":"callsite","description":"The call site (class name, method name and source information)","category":"Callsite and stacktraces"},
	{"name":"callsite-linenumber","description":"The call site source line number.","category":"Callsite and stacktraces"},
	{"name":"callsite-filename","description":"The call site source file name.","category":"Callsite and stacktraces"},
	{"name":"counter","description":"A counter value (increases on each layout rendering)","category":"Counters"},
	{"name":"currentdir","description":"The current working directory of the application.","category":"Files and directories"},
	{"name":"processdir","description":"The executable process directory of the application.","category":"Files and directories"},
	{"name":"date","description":"Current date and time.","category":"Date and time"},
	{"name":"environment","description":"The environment variable. (e.g PATH, OSVersion)","category":"Environment and config files"},
	{"name":"event-properties","description":"Log event properties data - rename of ${event-context}","category":"Context information"},
	{"name":"environment-user","description":"User identity information (username).","category":"Identity"},
	{"name":"exception","description":"Exception information provided through a call to one of the Logger methods","category":"Context information"},
	{"name":"exceptiondata","description":"Lookup item in Exception.Data-Dictionary from Exception provided together with the LogEvent","category":"Context information"},
	{"name":"file-contents","description":"Renders contents of the specified file.","category":"Files and directories"},
	{"name":"gc","description":"The information about the garbage collector.","category":"Processes, threads and assemblies"},
	{"name":"gdc","description":"Global Diagnostic Context item. Dictionary structure to hold per-application-instance values.","category":"Context information"},
	{"name":"guid","description":"Globally-unique identifier(GUID).","category":"Counters"},
	{"name":"hostname","description":"The host name of the computer that the process is running on.","category":"Processes, threads and assemblies"},
	{"name":"identity","description":"Thread identity information (name and authentication information).","category":"Identity"},
	{"name":"install-context","description":"Installation parameter (passed to InstallNLogConfig).","category":"Context information"},
	{"name":"level","description":"The log level (e.g. ERROR, DEBUG) or level ordinal (number)","category":""},
	{"name":"literal","description":"A string literal. (text) - useful to escape brackets","category":""},
	{"name":"local-ip","description":"Local IP Address from Network Interface.","category":"Processes, threads and assemblies"},
	{"name":"log4jxmlevent","description":"XML event description compatible with log4j, Chainsaw and NLogViewer.","category":"Integrations"},
	{"name":"logger","description":"The logger name. GetLogger, GetCurrentClassLogger etc","category":"Context information"},
	{"name":"longdate","description":"The date and time in a long, sortable format `yyyy-MM-dd HH:mm:ss.ffff`.","category":"Date and time"},
	{"name":"machinename","description":"The machine name that the process is running on.","category":"Processes, threads and assemblies"},
	{"name":"mdc","description":"Mapped Diagnostics Context - a thread-local structure.","category":"Context information","platformNotes":"For NLog 5.0 this has been replaced with ScopeProperty"},
	{"name":"mdlc","description":"Async Mapped Diagnostics Context - a thread-local structure for scoped context. Async version of the MDC. ","category":"Context information","platformNotes":"For NLog 5.0 this has been replaced with ScopeProperty"},
	{"name":"message","description":"The (formatted) log message.","category":""},
	{"name":"ndc","description":"Nested Diagnostics Context - a thread-local structure.","category":"Context information","platformNotes":"For NLog 5.0 this has been replaced with ScopeNested"},
	{"name":"ndlc","description":"Async Nested Diagnostics Context  - thread-local structure.","category":"Context information","platformNotes":"For NLog 5.0 this has been replaced with ScopeNested"},
	{"name":"newline","description":"A newline literal.","category":""},
	{"name":"nlogdir","description":"The directory where NLog.dll is located.","category":"Files and directories"},
	{"name":"performancecounter","description":"The performance counter.","category":"Processes, threads and assemblies","package":"NLog.PerformanceCounter","platformNotes":"For NLog 5.0: NLog.PerformanceCounter nuget package required"},
	{"name":"processid","description":"The identifier of the current process.","category":"Processes, threads and assemblies"},
	{"name":"processinfo","description":"The information about the running process. e.g. StartTime, PagedMemorySize","category":"Processes, threads and assemblies"},
	{"name":"processname","description":"The name of the current process.","category":"Processes, threads and assemblies"},
	{"name":"processtime","description":"The process lifetime in format HH:mm:ss.mmm.","category":"Processes, threads and assemblies"},
	{"name":"processstart","description":"The process start time.","category":"Processes, threads and assemblies"},
	{"name":"registry","description":"A value from the Windows Registry.","category":"Environment and config files","package":"NLog.WindowsRegistry","platformNotes":"For NLog 5.0: NLog.WindowsRegistry nuget package required"},
	{"name":"scopenested","description":"ScopeContext Nested states from the thread execution context (Ex. BeginScope). Similar to Nested Diagnostic Context (NDC) in Log4j","category":"Context information"},
	{"name":"scopeproperty","description":"ScopeContext Properties from the thread execution context (Ex. BeginScope). Similar to Mapped Diagnostic Context (MDC) in Log4j","category":"Context information"},
	{"name":"scopetiming","description":"ScopeContext Timing formats scope duration time  (Ex. BeginScope).","category":"Context information"},
	{"name":"sequenceid","description":"The log sequence id","category":"Counters"},
	{"name":"shortdate","description":"The short date in a sortable format yyyy-MM-dd.","category":"Date and time"},
	{"name":"specialfolder","description":"System special folder path (includes My Documents, My Music, Program Files, Desktop, and more).","category":"Files and directories"},
	{"name":"stacktrace","description":"Render the Stack trace","category":"Callsite and stacktraces"},
	{"name":"tempdir","description":"A temporary directory.","category":"Files and directories"},
	{"name":"threadid","description":"The identifier of the current thread.","category":"Processes, threads and assemblies"},
	{"name":"threadname","description":"The name of the current thread.","category":"Processes, threads and assemblies"},
	{"name":"ticks","description":"The Ticks value of current date and time.","category":"Date and time"},
	{"name":"time","description":"The time in a 24-hour, sortable format HH:mm:ss.mmm.","category":"Date and time"},
	{"name":"var","description":"NLog Logging Configuration Variable Value","category":"Context information"},
	{"name":"windows-identity","description":"Thread Windows identity information (username)","category":"Identity","package":"NLog.WindowsIdentity","platformNotes":"For NLog 5.0 and .NET Standard: NLog.WindowsIdentity nuget package required"},
	{"name":"cached","description":"Applies caching to another layout output.","category":"","wrapper":true},
	{"name":"norawvalue","description":"Prevents the output of another layout renderer to be treated as raw value","category":"Encoding and string transformations","wrapper":true},
	{"name":"filesystem-normalize","description":"Filters characters not allowed in the file names by replacing them with safe character.","category":"Files and directories","wrapper":true},
	{"name":"object-path","description":"Render a (nested) property of an object","category":"","wrapper":true},
	{"name":"json-encode","description":"Escapes output of another layout using JSON rules.","category":"Encoding and string transformations","wrapper":true},
	{"name":"lowercase","description":"Converts the result of another layout output to lower case.","category":"Encoding and string transformations","wrapper":true},
	{"name":"onexception","description":"Only outputs the inner layout when exception has been defined for log message.","category":"Context information","wrapper":true},
	{"name":"onhasproperties","description":"Only outputs the inner layout when event properties are included with the logevent.","category":"Context information","wrapper":true},
	{"name":"pad","description":"Applies padding to another layout output.","category":"Encoding and string transformations","wrapper":true},
	{"name":"replace","description":"Replaces a string in the output of another layout with another string. Optional with regex","category":"Encoding and string transformations","wrapper":true},
	{"name":"replace-newlines","description":"Replaces newline characters with another string.","category":"Encoding and string transformations","wrapper":true},
	{"name":"rot13","description":"Decodes text \"encrypted\"with ROT-13.","category":"Encoding and string transformations","wrapper":true},
	{"name":"trim-whitespace","description":"Trims the whitespace from the result of another layout renderer.","category":"Encoding and string transformations","wrapper":true},
	{"name":"uppercase","description":"Converts the result of another layout output to upper case.","category":"Encoding and string transformations","wrapper":true},
	{"name":"url-encode","description":"Encodes the result of another layout output for use with URLs.","category":"Encoding and string transformations","wrapper":true},
	{"name":"when","description":"Only outputs the inner layout when the specified condition has been met.","category":"Conditions","wrapper":true},
	{"name":"whenEmpty","description":"Outputs alternative layout when the inner layout produces empty result.","category":"Conditions","wrapper":true},
	{"name":"WrapLine","description":"Wraps the result of another layout output at specified line length.","category":"Encoding and string transformations","wrapper":true},
	{"name":"Left","description":"Left part of a text","category":"Encoding and string transformations","wrapper":true},
	{"name":"Right","description":"Right part of a text","category":"Encoding and string transformations","wrapper":true},
	{"name":"Substring","description":"Substring of a text","category":"Encoding and string transformations","wrapper":true},
	{"name":"xml-encode","description":"Converts the result of another layout output to be XML-compliant.","category":"Encoding and string transformations","wrapper":true},
	{"name":"appsetting","description":"AppSetting value from application app.config or web.config file","category":"Environment and config files","platformNotes":"For NLog 4.5 (and older) then NLog.Extended nuget package required"},
	{"name":"configsetting","description":"Value from the appsettings.json or other configuration in ASP.NET Core & .NET Core","category":"Environment and config files","package":"NLog.Extensions.Logging, NLog.Extensions.Hosting, NLog.Web.AspNetCore"},
	{"name":"host-appname","description":"HostEnvironment ApplicationName","category":"Environment and config files","package":"NLog.Extensions.Hosting, NLog.Web.AspNetCore"},
	{"name":"host-environment","description":"HostEnvironment Environment","category":"Environment and config files","package":"NLog.Extensions.Hosting, NLog.Web.AspNetCore"},
	{"name":"host-rootdir","description":"HostEnvironment ContentRoot","category":"Files and directories","package":"NLog.Extensions.Hosting, NLog.Web.AspNetCore"},
	{"name":"MicrosoftConsoleLayout","description":"Write events to text format similar to Microsoft AddConsole Formatter for Microsoft.Hosting.Lifetime","category":"Integrations","package":"NLog.Extensions.Logging, NLog.Extensions.Hosting, NLog.Web.AspNetCore"},
	{"name":"aspnet-MVC-Action","description":"ASP.NET MVC Action Name from routing parameters","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-MVC-Controller","description":"ASP.NET MVC Controller Name from routing parameters","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-Application","description":"ASP.NET Application variable.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web"},
	{"name":"aspnet-request-connection-id","description":"ASP.NET Http Request Connection Id. The unique identifier that represents the connection.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-request-duration","description":"ASP.NET Request Duration.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-httpcontext-item","description":"ASP.NET `HttpContext` Items Dictionary Value.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-environment","description":"ASP.NET Environment name","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-request-bidirectional-stream","description":"ASP.NET Request capable of upgrading connection to an opaque, bidirectional stream.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-request-endpoint","description":"ASP.NET Request EndPoint display name.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-request-endpoint-group","description":"ASP.NET Request EndPoint Group name.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-request-endpoint-name","description":"ASP.NET Request EndPoint Name name.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-request-client-certificate","description":"ASP.NET Request Client Certificate","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-request-contentlength","description":"ASP.NET Request Header Content-Length","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-request-contenttype","description":"ASP.NET Content-Type header (Ex. application/json)","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-request-http-transport-type","description":"ASP.NET supported transport types that the client can use to send HTTP requests","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-request-inherent-keep-alive","description":"ASP.NET Request using connection transport capable of 'inherent keep-alive'","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-request-local-ip","description":"ASP.NET Request HttpContext.Connection.LocalIpAddress","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-request-local-port","description":"ASP.NET Request HttpContext.Connection.LocalPort","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-request-remote-port","description":"ASP.NET Request HttpContext.Connection.RemotePort","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-request-servervariable","description":"ASP.NET Server Variable (Ex. APP_POOL_ID)","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-request-stream-id","description":"ASP.NET Http Request Stream Id. The unique identifier that represents the reusable socket.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-request-tls-handshake","description":"ASP.NET TLS Handshake Features ITlsHandshakeFeature of the connection.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-request-tls-token-binding","description":"ASP.NET TLS Token Bindings for Provider and Referrer","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-request-tracking-consent","description":"ASP.NET Tracking Consent","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-request-trailers","description":"ASP.NET Request Trailers","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-request-web-socket-requested-protocols","description":"ASP.NET Request HttpContext.WebSockets.WebSocketRequestedProtocols","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-TraceIdentifier","description":"ASP.NET trace identifier","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-appbasepath","description":"ASP.NET Application base path (Content Root)","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-webrootpath","description":"ASP.NET Web root path (wwwroot)","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-Request","description":"ASP.NET Request variable.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-request-has-posted-body","description":"ASP.NET posted body / payload was included with the request","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-request-posted-body","description":"ASP.NET posted body / payload","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-Request-Cookie","description":"ASP.NET Request cookie content.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-Request-Headers","description":"ASP.NET Header key/value pairs.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-Request-Host","description":"ASP.NET Request host.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-Request-Method","description":"ASP.NET Request method (GET, POST etc).","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-Request-IP","description":"Client IP.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-Request-QueryString","description":"ASP.NET Request querystring.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-Request-Referrer","description":"ASP.NET Request referrer.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-Request-RouteParameters","description":"ASP.NET Request route parameters.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-Request-UserAgent","description":"ASP.NET Request useragent.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-Request-Url","description":"ASP.NET Request URL.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-Request-Form","description":"ASP.NET Request form content.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-response-contentlength","description":"ASP.NET Response status code content.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-response-contenttype","description":"ASP.NET Response Header Content-Type (Ex. application/json)","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-response-cookie","description":"Cookie Name and Values stored in the ASP.NET Response Cookies collection.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-response-has-started","description":"ASP.NET Http Response HasStarted ","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-response-headers","description":"ASP.NET Response Headers key/value pairs.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-response-https-compression","description":"ASP.NET Response HTTPS Compression Mode","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-Response-StatusCode","description":"ASP.NET Response status code content.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-response-trailers","description":"ASP.NET Response Trailers","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web.AspNetCore"},
	{"name":"aspnet-Session","description":"ASP.NET Session variable.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-SessionId","description":"ASP.NET Session ID variable.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-User-isAuthenticated","description":"ASP.NET User authenticated?","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-User-AuthType","description":"ASP.NET User auth.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-User-Identity","description":"ASP.NET User variable.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"aspnet-User-Claim","description":"ASP.NET User Claims authorization values","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"iis-site-name","description":"IIS site name.","category":"Web, ASP.NET and ASP.NET Core","package":"NLog.Web, NLog.Web.AspNetCore"},
	{"name":"gelf","description":"Converts LogEvents into GELF format for sending to Graylog","category":"Integrations","package":"NLog.GelfLayout","external":true},
	{"name":"activity","description":"Capture span context details like request TraceId from System.Diagnostics.Activity.Current","category":"Context information","package":"NLog.DiagnosticSource","external":true}
];
