import * as path from "path";

/** A package's own standard top-level content folders. */
export type PkgItemCategory = "Schemas" | "SqlScripts" | "Data" | "Resources" | "Files";

const KNOWN_CATEGORIES: PkgItemCategory[] = ["Schemas", "SqlScripts", "Data", "Resources", "Files"];
const PKG_MARKER_RE = /\/Pkg\//gi;

export interface PkgPathInfo {
	/** `.../Pkg` — the folder holding every package (also the git root, per
	 * the confirmed repo topology: the whole `Pkg` folder is one git repo).
	 * OS-native separators. */
	pkgRoot: string;
	/** `.../Pkg/{Package}`. OS-native separators. */
	packageDir: string;
	packageName: string;
	/** `Schemas`/`SqlScripts`/`Data`/`Resources`/`Files`, matched
	 * case-insensitively against the real (always exactly-cased) folder name.
	 * `undefined` when `filePath` doesn't go at least that deep, or sits
	 * directly under an unrecognized folder (`Autogenerated`, a stray
	 * build-cache dir, ...). */
	category?: PkgItemCategory;
	/** The category folder's own immediate child name — a schema/sqlScript/
	 * data/resource item's own folder name. Set only when `category` is, and
	 * only when `filePath` actually reaches inside that item folder (a file
	 * sitting bare in the category folder itself, e.g. a stray `.DS_Store`
	 * directly under `Schemas/`, isn't a real item). */
	itemName?: string;
	/** `.../Pkg/{Package}/{category}/{itemName}`. OS-native separators. Set
	 * only when `itemName` is. */
	itemDir?: string;
	/** Whatever `/`-joined path comes after `itemDir` — e.g. a file name
	 * directly inside the item folder. Always set when `itemDir` is (an empty
	 * `rest` would mean `itemDir` itself wasn't real content, which
	 * `itemName`'s own requirement above already rules out). */
	rest?: string;
}

/** Index of the last `/Pkg/` marker in an already `/`-normalized path, or
 * `undefined` if there isn't one. Real paths essentially never contain more
 * than one, but where a couple of the original regexes this module replaces
 * disagreed on first-vs-last, last (the deepest/most specific package root)
 * matches the majority of them — the greedy-anchored `.*\/Pkg\/...` ones. */
function lastPkgMarkerIndex(normalized: string): number | undefined {
	let index: number | undefined;
	let match: RegExpExecArray | null;
	PKG_MARKER_RE.lastIndex = 0;
	while ((match = PKG_MARKER_RE.exec(normalized))) {
		index = match.index;
	}
	return index;
}

/**
 * Parses any path under a BPMSoft package tree — `.../Pkg/{Package}/...` —
 * into its structured pieces. Replaces roughly a dozen ad hoc `/Pkg/.../`
 * regexes previously scattered across the indexing/provider layer (see the
 * naming-refactor plan), each with its own slightly different shape and
 * inconsistent case-sensitivity. Deliberate normalizations relative to those
 * originals, all low-risk:
 *  - matches the `Pkg` marker and the category folder name
 *    case-insensitively, always (several call sites already did this
 *    inconsistently; a couple didn't at all — a real folder is always
 *    exactly-cased on disk in practice, so this only helps).
 *  - uses the LAST `/Pkg/` occurrence when there's more than one (see
 *    `lastPkgMarkerIndex`).
 *  - `packageName`/`itemName` are only reported when `filePath` actually
 *    continues past them (matching every original regex here, which all
 *    needed a trailing separator after a captured segment to match at all) —
 *    so a stray repo-root file directly under `Pkg/` (`.gitattributes`,
 *    `README.md`) or directly under a category folder (`Schemas/.DS_Store`)
 *    correctly reports no package/item, not a bogus one named after the
 *    file itself.
 * Accepts either an OS path or an already `/`-separated one. `undefined` if
 * `filePath` isn't under a real `Pkg/{Package}/...` at all.
 */
export function parsePkgPath(filePath: string): PkgPathInfo | undefined {
	const normalized = filePath.replace(/\\/g, "/");
	const markerIndex = lastPkgMarkerIndex(normalized);
	if (markerIndex === undefined) {
		return undefined;
	}
	const pkgRootSlash = normalized.slice(0, markerIndex) + "/Pkg";
	const afterPkg = normalized.slice(markerIndex + "/Pkg/".length);
	const segments = afterPkg.split("/").filter(Boolean);
	// A bare trailing segment (nothing after it in the original path) isn't
	// real container content — see the doc comment above.
	const hasMore = (count: number) => segments.length > count || afterPkg.endsWith("/");
	if (!hasMore(1)) {
		return undefined;
	}
	const packageName = segments[0];
	const toOsPath = (p: string) => p.replace(/\//g, path.sep);
	const pkgRoot = toOsPath(pkgRootSlash);
	const packageDir = toOsPath(`${pkgRootSlash}/${packageName}`);
	const categorySegment = segments[1];
	const category = categorySegment
		? KNOWN_CATEGORIES.find((c) => c.toLowerCase() === categorySegment.toLowerCase())
		: undefined;
	if (!category || !hasMore(3)) {
		return { pkgRoot, packageDir, packageName, category };
	}
	const itemName = segments[2];
	const itemDir = toOsPath(`${pkgRootSlash}/${packageName}/${category}/${itemName}`);
	const rest = segments.slice(3).join("/");
	return { pkgRoot, packageDir, packageName, category, itemName, itemDir, rest };
}

/** Thin helper for the common "just the package name" case. */
export function packageNameFromPkgPath(filePath: string): string | undefined {
	return parsePkgPath(filePath)?.packageName;
}

/** Whether `filePath` sits anywhere under a `Pkg/` folder at all — the
 * loose check a few call sites need (e.g. "prefer a match from inside a real
 * package over an Autogenerated one"), as opposed to `parsePkgPath`'s
 * stricter "resolves to a real package name" contract. Deliberately not
 * `parsePkgPath(filePath) !== undefined`: every real caller of this looser
 * check only ever sees actual indexed schema files, never a bare
 * repo-scaffolding file directly under `Pkg/` — but keeping the two
 * concepts distinct means that stays true by construction, not by
 * happenstance. */
export function isUnderPkg(filePath: string): boolean {
	return /\/Pkg\//i.test(filePath.replace(/\\/g, "/"));
}

/** `.../Pkg` for any path under it, using the same last-marker-wins rule as
 * `parsePkgPath` — but, like `isUnderPkg`, without requiring a real package
 * name to follow. */
export function findPkgRoot(filePath: string): string | undefined {
	const normalized = filePath.replace(/\\/g, "/");
	const markerIndex = lastPkgMarkerIndex(normalized);
	return markerIndex === undefined ? undefined : (normalized.slice(0, markerIndex) + "/Pkg").replace(/\//g, path.sep);
}
