import * as fs from "fs";
import { IndexedModule } from "../parse/types";
import { parseJsonNoBom } from "../textUtils";
import { pMap } from "./concurrency";

/**
 * Cross-activation cache for the two `ModuleIndexer` categories that are
 * genuinely static between ordinary extension activations — `Resources/ui/
 * BPMSoft/**\/*.js` (platform UI) and `conf/content/*Module*.js` (platform
 * modules) — confirmed real-world stable (only a BPMSoft version upgrade
 * changes them; `Pkg/**` and `Autogenerated/Src/**` are excluded on
 * purpose, they change constantly). Measured directly against two real
 * installs: these two categories are ~2.2-3.1s of a ~5-6.6s full rebuild —
 * worth skipping when nothing has actually changed.
 *
 * Validity is decided by a fingerprint over each file's own `(size, mtime)`
 * (see `computeDirFingerprint`), not by trying to read BPMSoft's own
 * version number — this extension has no reliable, layout-independent way
 * to locate one, and a file fingerprint catches an upgrade (or any other
 * reason the files changed) by construction, not by assumption. Combined
 * with the extension's own version, so an update to this extension (which
 * could change `IndexedModule`'s shape or `parseAmdModule`'s output)
 * invalidates any cache written by an older version, even if the platform
 * files themselves didn't change.
 */
export interface PlatformIndexCache {
	extensionVersion: string;
	fingerprint: string;
	modules: IndexedModule[];
}

/** FNV-1a over each file's `path\0size\0mtimeMs`, sorted by path first so
 * traversal order doesn't affect the result — cheap (a handful of bytes of
 * arithmetic per file) next to the `fs.stat` call it's paired with, and good
 * enough for "did anything change", which is all this needs (no
 * cryptographic requirement). Stats are gathered through `pMap` (not a plain
 * serial loop) for the same reason `ModuleIndexer` reads file content that
 * way — see `concurrency.ts`'s own doc. */
export async function computeDirFingerprint(files: string[]): Promise<string> {
	const sorted = [...files].sort();
	const entries = await pMap(sorted, async (filePath) => {
		try {
			const stat = await fs.promises.stat(filePath);
			return `${filePath}\0${stat.size}\0${stat.mtimeMs}`;
		} catch {
			return undefined;
		}
	});
	let hash = 0x811c9dc5;
	for (const entry of entries) {
		if (entry === undefined) {
			continue;
		}
		for (let i = 0; i < entry.length; i++) {
			hash ^= entry.charCodeAt(i);
			hash = Math.imul(hash, 0x01000193);
		}
	}
	return (hash >>> 0).toString(16);
}

/** `undefined` on any miss — file missing/unreadable, JSON malformed, or
 * either `extensionVersion`/`fingerprint` not matching what the caller
 * expects. Never throws; a cache is a pure optimization, a bad one should
 * just be treated as absent. */
export function loadPlatformIndexCache(
	cacheFilePath: string,
	extensionVersion: string,
	fingerprint: string
): IndexedModule[] | undefined {
	let raw: string;
	try {
		raw = fs.readFileSync(cacheFilePath, "utf8");
	} catch {
		return undefined;
	}
	const cache = parseJsonNoBom<PlatformIndexCache>(raw);
	if (
		!cache ||
		cache.extensionVersion !== extensionVersion ||
		cache.fingerprint !== fingerprint ||
		!Array.isArray(cache.modules)
	) {
		return undefined;
	}
	return cache.modules;
}

/** Best-effort write — swallows any failure (read-only storage, disk full,
 * ...) since losing the cache only costs the next activation a fresh
 * parse, never correctness. */
export function savePlatformIndexCache(
	cacheFilePath: string,
	extensionVersion: string,
	fingerprint: string,
	modules: IndexedModule[]
): void {
	try {
		const cache: PlatformIndexCache = { extensionVersion, fingerprint, modules };
		fs.writeFileSync(cacheFilePath, JSON.stringify(cache));
	} catch {
		// best-effort — see doc comment
	}
}
