import * as fs from "fs";
import { IndexedMember, IndexedModule, PlatformStubMember, memberDedupeKey } from "./types";
import { SchemaHierarchyResolver } from "./schemaHierarchy";
import { parseAmdModule, parseEntityColumns } from "../parse/amdParser";
import { buildSandboxStubs } from "../stubs/sandboxGlobals";

function packageLabel(filePath: string): string {
	const norm = filePath.replace(/\\/g, "/");
	const pkg = norm.match(/\/Pkg\/([^/]+)\//);
	if (pkg) {
		return `Pkg/${pkg[1]}`;
	}
	const auto = norm.match(/\/Autogenerated\/Src\/[^/]+\.([^.]+)\.js$/i);
	if (auto) {
		return `Autogenerated/${auto[1]}`;
	}
	if (/\/Autogenerated\//i.test(norm)) {
		return "Autogenerated";
	}
	const ui = norm.match(/\/Resources\/ui\/BPMSoft\/(.+)\.js$/i);
	if (ui) {
		return `ui/${ui[1]}`;
	}
	return filePath;
}

function inheritdocTarget(mod: IndexedModule): string {
	if (mod.alternateClassName) {
		return mod.alternateClassName;
	}
	if (mod.className) {
		return mod.className;
	}
	if (mod.name.includes(".")) {
		return mod.name;
	}
	return `BPMSoft.${mod.name}`;
}

const MAX_INHERIT_DEPTH = 25;

function isPageSchema(mod: IndexedModule): boolean {
	return mod.kind === "page";
}

/**
 * In-memory symbol index for AMD modules and platform stubs.
 */
export class SymbolIndex {
	private modulesByName = new Map<string, IndexedModule[]>();
	private modulesByPath = new Map<string, IndexedModule>();
	private alternateToModules = new Map<string, IndexedModule[]>();
	private platformRoot: PlatformStubMember[] = [];
	private extRoot: PlatformStubMember[] = [];
	private sandboxMembers: IndexedMember[] = [];
	private sandboxOrigin?: { filePath: string; position: { line: number; character: number } };
	private workspaceRoots: string[] = [];
	private entityCache = new Map<string, IndexedModule | null>();
	readonly hierarchy = new SchemaHierarchyResolver();

	setPlatformStubs(members: PlatformStubMember[]): void {
		this.platformRoot = members;
	}

	setExtStubs(members: PlatformStubMember[]): void {
		this.extRoot = members;
	}

	setSandboxStubs(
		members: IndexedMember[],
		origin?: { filePath: string; position: { line: number; character: number } }
	): void {
		this.sandboxMembers = members;
		this.sandboxOrigin = origin;
	}

	setWorkspaceRoots(roots: string[]): void {
		this.workspaceRoots = roots;
		this.hierarchy.setWorkspaceRoots(roots);
		this.entityCache.clear();
	}

	clearModules(): void {
		this.modulesByName.clear();
		this.modulesByPath.clear();
		this.alternateToModules.clear();
		this.entityCache.clear();
	}

	invalidateEntity(filePath: string): void {
		const base = filePath.replace(/\\/g, "/").split("/").pop() || "";
		const name = base.replace(/\.js$/i, "");
		if (name) {
			this.entityCache.delete(name);
		}
	}

	upsertModule(mod: IndexedModule): void {
		this.removeByPath(mod.filePath);
		this.modulesByPath.set(mod.filePath, mod);
		this.pushNamed(this.modulesByName, mod.name, mod);
		if (mod.className && mod.className !== mod.name) {
			this.pushNamed(this.modulesByName, mod.className, mod);
		}
		if (mod.alternateClassName) {
			this.pushNamed(this.alternateToModules, mod.alternateClassName, mod);
			const short = mod.alternateClassName.replace(/^BPMSoft\./, "");
			this.pushNamed(this.alternateToModules, short, mod);
			this.pushNamed(this.alternateToModules, mod.name, mod);
		}
		if (mod.className) {
			this.pushNamed(this.alternateToModules, mod.className, mod);
		}
	}

	removeByPath(filePath: string): void {
		const prev = this.modulesByPath.get(filePath);
		if (!prev) {
			return;
		}
		this.modulesByPath.delete(filePath);
		this.pullNamed(this.modulesByName, prev.name, filePath);
		if (prev.className && prev.className !== prev.name) {
			this.pullNamed(this.modulesByName, prev.className, filePath);
		}
		if (prev.alternateClassName) {
			this.pullNamed(this.alternateToModules, prev.alternateClassName, filePath);
			this.pullNamed(
				this.alternateToModules,
				prev.alternateClassName.replace(/^BPMSoft\./, ""),
				filePath
			);
			this.pullNamed(this.alternateToModules, prev.name, filePath);
		}
		if (prev.className) {
			this.pullNamed(this.alternateToModules, prev.className, filePath);
		}
	}

	getAllByName(name: string): IndexedModule[] {
		if (!name) {
			return [];
		}
		const seen = new Map<string, IndexedModule>();
		const add = (list?: IndexedModule[]) => {
			if (!list) {
				return;
			}
			for (const m of list) {
				seen.set(m.filePath, m);
			}
		};
		add(this.modulesByName.get(name));
		add(this.alternateToModules.get(name));
		add(this.alternateToModules.get(name.replace(/^BPMSoft\./, "")));
		return Array.from(seen.values());
	}

	getByPath(filePath: string): IndexedModule | undefined {
		return this.modulesByPath.get(filePath);
	}

	ensureModule(filePath: string): IndexedModule | undefined {
		const existing = this.modulesByPath.get(filePath);
		if (existing) {
			return existing;
		}
		try {
			const source = fs.readFileSync(filePath, "utf8");
			const mod = parseAmdModule(source, filePath);
			if (!mod) {
				return undefined;
			}
			this.upsertModule(mod);
			return mod;
		} catch {
			return undefined;
		}
	}

	resolveMembers(prefix: string, enablePlatformStubs: boolean): IndexedMember[] {
		const parts = prefix.split(".").filter(Boolean);
		if (parts.length === 0) {
			return [];
		}

		const full = parts.join(".");
		if (!(parts[0] === "BPMSoft" && parts.length === 1)) {
			const named = this.getAllByName(full);
			if (named.length) {
				return this.mergeMembers(named);
			}
		}

		if (parts[0] === "BPMSoft") {
			if (!enablePlatformStubs) {
				if (parts.length === 1) {
					return this.collectBpmsoftShortcuts();
				}
				const alt = `BPMSoft.${parts[1]}`;
				const mods = this.getAllByName(alt);
				if (mods.length && parts.length === 2) {
					return this.mergeMembers(mods);
				}
				return [];
			}
			return this.resolvePlatformPath(parts.slice(1));
		}

		if (parts[0] === "Ext") {
			return this.resolveExtPath(parts.slice(1));
		}

		const mods = this.getAllByName(parts[0]);
		if (!mods.length) {
			return [];
		}
		if (parts.length === 1) {
			return this.mergeMembers(mods);
		}
		return [];
	}

	private collectBpmsoftShortcuts(): IndexedMember[] {
		const out: IndexedMember[] = [];
		const seen = new Set<string>();
		for (const mod of this.modulesByPath.values()) {
			const alt = mod.alternateClassName;
			if (!alt?.startsWith("BPMSoft.")) {
				continue;
			}
			const short = alt.slice("BPMSoft.".length);
			if (!short || short.includes(".") || seen.has(short)) {
				continue;
			}
			seen.add(short);
			out.push({
				name: short,
				kind: "namespace",
				detail:
					mod.kind === "mixin"
						? "mixin"
						: mod.kind === "class"
							? "class"
							: "type",
				documentation: mod.filePath
			});
		}
		return out;
	}

	private resolveExtPath(rest: string[]): IndexedMember[] {
		if (!this.extRoot.length) {
			return [];
		}
		if (rest.length === 0) {
			return this.extRoot.map((s) => this.stubToMember(s));
		}
		let current: PlatformStubMember[] | undefined = this.extRoot;
		let node: PlatformStubMember | undefined;
		for (const part of rest) {
			node = current?.find((c) => c.name === part);
			if (!node) {
				return [];
			}
			current = node.children;
		}
		if (node?.children?.length) {
			return node.children.map((c) => this.stubToMember(c));
		}
		return [];
	}

	private resolvePlatformPath(rest: string[]): IndexedMember[] {
		if (rest.length === 0) {
			const stubs = this.platformRoot.map((s) => this.stubToMember(s));
			const shortcuts = this.collectBpmsoftShortcuts();
			return this.mergeMemberLists(stubs, shortcuts);
		}
		let current: PlatformStubMember[] | undefined = this.platformRoot;
		let node: PlatformStubMember | undefined;
		for (const part of rest) {
			node = current?.find((c) => c.name === part);
			if (!node) {
				const mods = this.getAllByName(`BPMSoft.${rest.join(".")}`).concat(
					this.getAllByName(rest.join("."))
				);
				if (mods.length) {
					return this.mergeMembers(mods);
				}
				return [];
			}
			current = node.children;
		}
		if (node?.children?.length) {
			return node.children.map((c) => this.stubToMember(c));
		}
		// Leaf stub with no children → try real Ext/AMD class (SysSettings, Collection, …)
		const mods = this.getAllByName(`BPMSoft.${rest.join(".")}`).concat(
			this.getAllByName(rest[rest.length - 1])
		);
		if (mods.length) {
			return this.mergeMembers(mods);
		}
		return [];
	}

	private mergeMemberLists(...lists: IndexedMember[][]): IndexedMember[] {
		const map = new Map<string, IndexedMember>();
		for (const list of lists) {
			for (const m of list) {
				if (!map.has(m.name)) {
					map.set(m.name, m);
				}
			}
		}
		return Array.from(map.values());
	}

	private stubToMember(s: PlatformStubMember): IndexedMember {
		return {
			name: s.name,
			kind: s.kind,
			detail: s.detail,
			documentation: s.documentation
		};
	}

	private collectInheritanceChain(mod: IndexedModule): IndexedModule[] {
		const out: IndexedModule[] = [];
		const visitedNames = new Set<string>();
		let current: IndexedModule | undefined = mod;
		for (let depth = 0; depth < MAX_INHERIT_DEPTH && current; depth++) {
			const parentName: string | undefined = current.override || current.extend;
			if (!parentName || visitedNames.has(parentName)) {
				break;
			}
			visitedNames.add(parentName);
			const currentPath = current.filePath;
			const candidates: IndexedModule[] = this.getAllByName(parentName).filter(
				(m: IndexedModule) => m.filePath !== currentPath
			);
			if (!candidates.length) {
				break;
			}
			const parent: IndexedModule =
				candidates.find((m: IndexedModule) => !m.override) ||
				candidates.find((m: IndexedModule) =>
					/\/Resources\/ui\//i.test(m.filePath)
				) ||
				candidates.find((m: IndexedModule) =>
					/\/Autogenerated\//i.test(m.filePath)
				) ||
				candidates[0];
			out.push(parent);
			current = parent;
		}
		return out;
	}

	/**
	 * Schema pages: conf/content hierarchy (stack + structureParent + extra Pkg).
	 * Ext modules: own file + override/extend chain.
	 */
	resolveThisMembers(filePath: string): IndexedMember[] {
		const mod = this.getByPath(filePath) || this.ensureModule(filePath);
		if (!mod) {
			return [];
		}

		const chainMods = this.collectOwnerChain(mod);

		const result = this.mergeMembers(chainMods, true);
		const seen = new Set(result.map((m) => memberDedupeKey(m)));
		this.appendMixinMembers(chainMods, result, seen);
		this.appendEntityColumns(chainMods, result, seen);
		this.appendRuntimeThisMembers(result, seen);
		return result;
	}

	/**
	 * Parent/mixin methods that can be overridden in the current schema or class.
	 * Current file members are excluded (already defined).
	 */
	resolveOverridableMethods(
		filePath: string
	): Array<{ name: string; params: string[]; owner: string; documentation?: string }> {
		const mod = this.getByPath(filePath) || this.ensureModule(filePath);
		if (!mod) {
			return [];
		}

		const chainMods = this.collectOwnerChain(mod);

		const seen = new Set<string>();
		for (const member of mod.members) {
			if (member.kind === "method") {
				seen.add(member.name);
			}
		}

		const out: Array<{
			name: string;
			params: string[];
			owner: string;
			documentation?: string;
		}> = [];

		const addFrom = (ownerMod: IndexedModule) => {
			if (ownerMod.filePath === mod.filePath) {
				return;
			}
			const owner = inheritdocTarget(ownerMod);
			for (const member of ownerMod.members) {
				if (member.kind !== "method" || seen.has(member.name)) {
					continue;
				}
				seen.add(member.name);
				out.push({
					name: member.name,
					params: member.params || [],
					owner,
					documentation: member.documentation
				});
			}
		};

		for (const ownerMod of chainMods) {
			addFrom(ownerMod);
		}

		const mixinAlts = new Set<string>();
		for (const schemaMod of chainMods) {
			for (const alt of Object.values(schemaMod.mixins)) {
				mixinAlts.add(alt);
			}
		}
		for (const alt of mixinAlts) {
			const short = alt.replace(/^BPMSoft\./, "");
			const mixinMods = this.getAllByName(alt).concat(this.getAllByName(short));
			const uniqueMixins = new Map<string, IndexedModule>();
			for (const m of mixinMods) {
				uniqueMixins.set(m.filePath, m);
			}
			for (const mixinMod of uniqueMixins.values()) {
				addFrom(mixinMod);
			}
		}

		return out;
	}

	findThisMemberLocations(
		filePath: string,
		memberName: string,
		kind?: IndexedMember["kind"]
	): Array<{ module: IndexedModule; member: IndexedMember }> {
		const mod = this.getByPath(filePath) || this.ensureModule(filePath);
		if (!mod) {
			return [];
		}
		const hits: Array<{ module: IndexedModule; member: IndexedMember }> = [];
		const seenPaths = new Set<string>();
		const dollar = memberName.startsWith("$") && memberName.length > 1;
		const lookupName = dollar ? memberName.slice(1) : memberName;
		const requiredKind = kind || (dollar ? "attribute" : undefined);

		const consider = (m: IndexedModule) => {
			if (seenPaths.has(m.filePath)) {
				return;
			}
			seenPaths.add(m.filePath);
			for (const member of m.members) {
				if (member.name !== lookupName) {
					continue;
				}
				if (requiredKind && member.kind !== requiredKind) {
					continue;
				}
				if (!member.position) {
					continue;
				}
				hits.push({ module: m, member });
			}
		};

		const chainMods = this.collectOwnerChain(mod);

		for (const m of chainMods) {
			consider(m);
		}

		const mixinAlts = new Set<string>();
		for (const schemaMod of chainMods) {
			for (const alt of Object.values(schemaMod.mixins)) {
				mixinAlts.add(alt);
			}
		}
		for (const alt of mixinAlts) {
			const short = alt.replace(/^BPMSoft\./, "");
			for (const mixinMod of this.getAllByName(alt).concat(
				this.getAllByName(short)
			)) {
				consider(mixinMod);
			}
		}

		const entityMod = this.getEntityModuleForChain(chainMods);
		if (entityMod) {
			consider(entityMod);
		}
		return hits;
	}

	private collectOwnerChain(mod: IndexedModule): IndexedModule[] {
		return isPageSchema(mod)
			? this.collectSchemaHierarchyModules(mod)
			: [mod, ...this.collectInheritanceChain(mod)];
	}

	private collectSchemaHierarchyModules(mod: IndexedModule): IndexedModule[] {
		const ordered: IndexedModule[] = [];
		const seen = new Set<string>();

		const push = (m: IndexedModule | undefined) => {
			if (!m || seen.has(m.filePath)) {
				return;
			}
			seen.add(m.filePath);
			ordered.push(m);
		};

		// Current file first (most specific while editing)
		push(mod);

		if (this.hierarchy.hasRoots()) {
			const layers = this.hierarchy.resolveSchemaLayers(mod.name);
			for (const layer of layers) {
				push(this.ensureModule(layer.filePath));
			}
		} else {
			// Fallback without conf: same-name replacements, current first already done
			for (const sibling of this.getAllByName(mod.name)) {
				push(sibling);
			}
		}

		const platformClass = this.hierarchy.resolvePlatformExtendClass(mod.name);
		if (platformClass) {
			const rootExt = this.pickNamedModule(platformClass);
			if (rootExt) {
				push(rootExt);
				for (const parent of this.collectInheritanceChain(rootExt)) {
					push(parent);
				}
			}
		}

		return ordered;
	}

	private pickNamedModule(name: string): IndexedModule | undefined {
		const candidates = this.getAllByName(name);
		if (!candidates.length) {
			return undefined;
		}
		return (
			candidates.find(
				(m) => !m.override && /\/Resources\/ui\//i.test(m.filePath)
			) ||
			candidates.find((m) => !m.override) ||
			candidates.find((m) => /\/Resources\/ui\//i.test(m.filePath)) ||
			candidates[0]
		);
	}

	private appendMixinMembers(
		owners: IndexedModule[],
		result: IndexedMember[],
		seen: Set<string>
	): void {
		const mixinAlts = new Set<string>();
		for (const schemaMod of owners) {
			for (const alt of Object.values(schemaMod.mixins)) {
				mixinAlts.add(alt);
			}
		}
		for (const alt of mixinAlts) {
			const short = alt.replace(/^BPMSoft\./, "");
			const mixinMods = this.getAllByName(alt).concat(this.getAllByName(short));
			const uniqueMixins = new Map<string, IndexedModule>();
			for (const m of mixinMods) {
				uniqueMixins.set(m.filePath, m);
			}
			for (const mixinMod of uniqueMixins.values()) {
				for (const member of mixinMod.members) {
					const key = memberDedupeKey(member);
					if (seen.has(key)) {
						continue;
					}
					seen.add(key);
					result.push({
						...member,
						detail:
							member.detail ||
							`mixin ${mixinMod.name} (${packageLabel(mixinMod.filePath)})`
					});
				}
			}
		}
	}

	private appendRuntimeThisMembers(
		result: IndexedMember[],
		seen: Set<string>
	): void {
		const runtime: IndexedMember[] = [
			{
				name: "Ext",
				kind: "property",
				detail: "injected Ext",
				documentation:
					"Экземпляр Ext модуля (тот же API, что у глобального Ext)"
			},
			{
				name: "BPMSoft",
				kind: "property",
				detail: "injected BPMSoft",
				documentation:
					"Экземпляр BPMSoft модуля (тот же API, что у глобального BPMSoft)"
			},
			{
				name: "sandbox",
				kind: "property",
				detail: "module sandbox",
				documentation:
					"Песочница модуля: publish / subscribe / loadModule",
				children: this.getSandboxMembers(),
				filePath: this.sandboxOrigin?.filePath,
				position: this.sandboxOrigin?.position
			}
		];
		for (const member of runtime) {
			const key = memberDedupeKey(member);
			if (seen.has(key)) {
				continue;
			}
			seen.add(key);
			result.push(member);
		}
	}

	private getSandboxMembers(): IndexedMember[] {
		if (this.sandboxMembers.length) {
			return this.sandboxMembers;
		}
		const built = buildSandboxStubs(this.workspaceRoots);
		this.sandboxMembers = built.members;
		this.sandboxOrigin = built.origin;
		return this.sandboxMembers;
	}

	findSandboxMember(name: string): IndexedMember | undefined {
		return this.getSandboxMembers().find((m) => m.name === name);
	}

	private appendEntityColumns(
		owners: IndexedModule[],
		result: IndexedMember[],
		seen: Set<string>
	): void {
		const entityMod = this.getEntityModuleForChain(owners);
		if (!entityMod) {
			return;
		}
		for (const member of entityMod.members) {
			const key = memberDedupeKey(member);
			if (seen.has(key)) {
				continue;
			}
			seen.add(key);
			result.push({
				...member,
				detail: member.detail || `entity ${entityMod.name}`
			});
		}
	}

	private getEntityModuleForChain(
		owners: IndexedModule[]
	): IndexedModule | undefined {
		const entityName = owners
			.map((m) => m.entitySchemaName)
			.find((name): name is string => Boolean(name));
		if (!entityName) {
			return undefined;
		}
		return this.getEntityModule(entityName);
	}

	private getEntityModule(entityName: string): IndexedModule | undefined {
		if (this.entityCache.has(entityName)) {
			return this.entityCache.get(entityName) || undefined;
		}
		const filePath = this.hierarchy.resolveEntitySchemaPath(entityName);
		if (!filePath) {
			this.entityCache.set(entityName, null);
			return undefined;
		}
		try {
			const source = fs.readFileSync(filePath, "utf8");
			const members = parseEntityColumns(source, filePath);
			const mod: IndexedModule = {
				name: entityName,
				filePath,
				kind: "unknown",
				dependencies: [],
				paramNames: [],
				members,
				mixins: {},
				entitySchemaName: entityName
			};
			this.entityCache.set(entityName, mod);
			return mod;
		} catch {
			this.entityCache.set(entityName, null);
			return undefined;
		}
	}

	resolveLocalAlias(filePath: string, alias: string): string | undefined {
		const mod = this.getByPath(filePath);
		if (!mod) {
			return undefined;
		}
		if (alias === mod.name) {
			return mod.name;
		}
		const idx = mod.paramNames.indexOf(alias);
		if (idx >= 0 && idx < mod.dependencies.length) {
			return mod.dependencies[idx];
		}
		if (mod.dependencies.includes(alias)) {
			return alias;
		}
		return undefined;
	}

	private mergeMembers(
		mods: IndexedModule[],
		annotateSource = false
	): IndexedMember[] {
		const result: IndexedMember[] = [];
		const seen = new Set<string>();
		for (const mod of mods) {
			const label = packageLabel(mod.filePath);
			for (const member of mod.members) {
				const key = memberDedupeKey(member);
				if (seen.has(key)) {
					continue;
				}
				seen.add(key);
				result.push(
					annotateSource
						? {
								...member,
								detail: member.detail || label
							}
						: member
				);
			}
		}
		return result;
	}

	private pushNamed(
		map: Map<string, IndexedModule[]>,
		key: string,
		mod: IndexedModule
	): void {
		const list = map.get(key);
		if (list) {
			list.push(mod);
		} else {
			map.set(key, [mod]);
		}
	}

	private pullNamed(
		map: Map<string, IndexedModule[]>,
		key: string,
		filePath: string
	): void {
		const list = map.get(key);
		if (!list) {
			return;
		}
		const next = list.filter((m) => m.filePath !== filePath);
		if (next.length) {
			map.set(key, next);
		} else {
			map.delete(key);
		}
	}
}
