import * as fs from "fs";
import { IndexedMember, IndexedModule, IndexedSchemaMessage, PlatformStubMember, memberDedupeKey, schemaMessageSupports } from "./types";
import { SchemaHierarchyResolver } from "./schemaHierarchy";
import { parseAmdModule, parseEntityColumns } from "../parse/amdParser";
import { buildSandboxStubs } from "../stubs/sandboxGlobals";

function packageLabel(filePath: string): string {
	const norm = filePath.replace(/\\/g, "/");
	const pkg = norm.match(/\/Pkg\/([^/]+)\//);
	if (pkg) {
		return `Pkg/${pkg[1]}`;
	}
	const auto = norm.match(/\/Autogenerated\/Src\/[^/]+\.([^.]+)\.js$/i);
	if (auto) {
		return `Autogenerated/${auto[1]}`;
	}
	if (/\/Autogenerated\//i.test(norm)) {
		return "Autogenerated";
	}
	const ui = norm.match(/\/Resources\/ui\/BPMSoft\/(.+)\.js$/i);
	if (ui) {
		return `ui/${ui[1]}`;
	}
	return filePath;
}

function inheritdocTarget(mod: IndexedModule): string {
	if (mod.alternateClassName) {
		return mod.alternateClassName;
	}
	if (mod.className) {
		return mod.className;
	}
	if (mod.name.includes(".")) {
		return mod.name;
	}
	return `BPMSoft.${mod.name}`;
}

const MAX_INHERIT_DEPTH = 25;

function isPageSchema(mod: IndexedModule): boolean {
	return mod.kind === "page";
}

/**
 * In-memory symbol index for AMD modules and platform stubs.
 */
export class SymbolIndex {
	private modulesByName = new Map<string, IndexedModule[]>();
	private modulesByPath = new Map<string, IndexedModule>();
	private alternateToModules = new Map<string, IndexedModule[]>();
	private platformRoot: PlatformStubMember[] = [];
	private extRoot: PlatformStubMember[] = [];
	private sandboxMembers: IndexedMember[] = [];
	private sandboxOrigin?: { filePath: string; position: { line: number; character: number } };
	private coreMessages: IndexedSchemaMessage[] = [];
	private workspaceRoots: string[] = [];
	private entityCache = new Map<string, IndexedModule | null>();
	readonly hierarchy = new SchemaHierarchyResolver();

	setPlatformStubs(members: PlatformStubMember[]): void {
		this.platformRoot = members;
	}

	setExtStubs(members: PlatformStubMember[]): void {
		this.extRoot = members;
	}

	setSandboxStubs(
		members: IndexedMember[],
		origin?: { filePath: string; position: { line: number; character: number } }
	): void {
		this.sandboxMembers = members;
		this.sandboxOrigin = origin;
	}

	setCoreMessages(messages: IndexedSchemaMessage[]): void {
		this.coreMessages = messages;
	}

	setWorkspaceRoots(roots: string[]): void {
		this.workspaceRoots = roots;
		this.hierarchy.setWorkspaceRoots(roots);
		this.entityCache.clear();
	}

	clearModules(): void {
		this.modulesByName.clear();
		this.modulesByPath.clear();
		this.alternateToModules.clear();
		this.entityCache.clear();
	}

	invalidateEntity(filePath: string): void {
		const base = filePath.replace(/\\/g, "/").split("/").pop() || "";
		const name = base.replace(/\.js$/i, "");
		if (name) {
			this.entityCache.delete(name);
		}
	}

	upsertModule(mod: IndexedModule): void {
		this.removeByPath(mod.filePath);
		this.modulesByPath.set(mod.filePath, mod);
		this.pushNamed(this.modulesByName, mod.name, mod);
		if (mod.className && mod.className !== mod.name) {
			this.pushNamed(this.modulesByName, mod.className, mod);
		}
		if (mod.alternateClassName) {
			this.pushNamed(this.alternateToModules, mod.alternateClassName, mod);
			const short = mod.alternateClassName.replace(/^BPMSoft\./, "");
			this.pushNamed(this.alternateToModules, short, mod);
			this.pushNamed(this.alternateToModules, mod.name, mod);
		}
		if (mod.className) {
			this.pushNamed(this.alternateToModules, mod.className, mod);
		}
	}

	removeByPath(filePath: string): void {
		const prev = this.modulesByPath.get(filePath);
		if (!prev) {
			return;
		}
		this.modulesByPath.delete(filePath);
		this.pullNamed(this.modulesByName, prev.name, filePath);
		if (prev.className && prev.className !== prev.name) {
			this.pullNamed(this.modulesByName, prev.className, filePath);
		}
		if (prev.alternateClassName) {
			this.pullNamed(this.alternateToModules, prev.alternateClassName, filePath);
			this.pullNamed(
				this.alternateToModules,
				prev.alternateClassName.replace(/^BPMSoft\./, ""),
				filePath
			);
			this.pullNamed(this.alternateToModules, prev.name, filePath);
		}
		if (prev.className) {
			this.pullNamed(this.alternateToModules, prev.className, filePath);
		}
	}

	getAllByName(name: string): IndexedModule[] {
		if (!name) {
			return [];
		}
		const seen = new Map<string, IndexedModule>();
		const add = (list?: IndexedModule[]) => {
			if (!list) {
				return;
			}
			for (const m of list) {
				seen.set(m.filePath, m);
			}
		};
		add(this.modulesByName.get(name));
		add(this.alternateToModules.get(name));
		add(this.alternateToModules.get(name.replace(/^BPMSoft\./, "")));
		return Array.from(seen.values());
	}

	getByPath(filePath: string): IndexedModule | undefined {
		return this.modulesByPath.get(filePath);
	}

	ensureModule(filePath: string): IndexedModule | undefined {
		const existing = this.modulesByPath.get(filePath);
		if (existing) {
			return existing;
		}
		try {
			const source = fs.readFileSync(filePath, "utf8");
			const mod = parseAmdModule(source, filePath);
			if (!mod) {
				return undefined;
			}
			this.upsertModule(mod);
			return mod;
		} catch {
			return undefined;
		}
	}

	resolveMembers(prefix: string, enablePlatformStubs: boolean): IndexedMember[] {
		const parts = prefix.split(".").filter(Boolean);
		if (parts.length === 0) {
			return [];
		}

		const full = parts.join(".");
		if (!(parts[0] === "BPMSoft" && parts.length === 1)) {
			const named = this.getAllByName(full);
			if (named.length) {
				return this.mergeMembers(named);
			}
		}

		if (parts[0] === "BPMSoft") {
			if (!enablePlatformStubs) {
				if (parts.length === 1) {
					return this.collectBpmsoftShortcuts();
				}
				const alt = `BPMSoft.${parts[1]}`;
				const mods = this.getAllByName(alt);
				if (mods.length && parts.length === 2) {
					return this.mergeMembers(mods);
				}
				return [];
			}
			return this.resolvePlatformPath(parts.slice(1));
		}

		if (parts[0] === "Ext") {
			return this.resolveExtPath(parts.slice(1));
		}

		const mods = this.getAllByName(parts[0]);
		if (!mods.length) {
			return [];
		}
		if (parts.length === 1) {
			return this.mergeMembers(mods);
		}
		return [];
	}

	private collectBpmsoftShortcuts(): IndexedMember[] {
		const out: IndexedMember[] = [];
		const seen = new Set<string>();
		for (const mod of this.modulesByPath.values()) {
			const alt = mod.alternateClassName;
			if (!alt?.startsWith("BPMSoft.")) {
				continue;
			}
			const short = alt.slice("BPMSoft.".length);
			if (!short || short.includes(".") || seen.has(short)) {
				continue;
			}
			seen.add(short);
			out.push({
				name: short,
				kind: "namespace",
				detail:
					mod.kind === "mixin"
						? "mixin"
						: mod.kind === "class"
							? "class"
							: "type",
				documentation: mod.filePath
			});
		}
		return out;
	}

	private resolveExtPath(rest: string[]): IndexedMember[] {
		if (!this.extRoot.length) {
			return [];
		}
		if (rest.length === 0) {
			return this.extRoot.map((s) => this.stubToMember(s));
		}
		let current: PlatformStubMember[] | undefined = this.extRoot;
		let node: PlatformStubMember | undefined;
		for (const part of rest) {
			node = current?.find((c) => c.name === part);
			if (!node) {
				return [];
			}
			current = node.children;
		}
		if (node?.children?.length) {
			return node.children.map((c) => this.stubToMember(c));
		}
		return [];
	}

	private resolvePlatformPath(rest: string[]): IndexedMember[] {
		if (rest.length === 0) {
			const stubs = this.platformRoot.map((s) => this.stubToMember(s));
			const shortcuts = this.collectBpmsoftShortcuts();
			return this.mergeMemberLists(stubs, shortcuts);
		}
		let current: PlatformStubMember[] | undefined = this.platformRoot;
		let node: PlatformStubMember | undefined;
		for (const part of rest) {
			node = current?.find((c) => c.name === part);
			if (!node) {
				const mods = this.getAllByName(`BPMSoft.${rest.join(".")}`).concat(
					this.getAllByName(rest.join("."))
				);
				if (mods.length) {
					return this.mergeMembers(mods);
				}
				return [];
			}
			current = node.children;
		}
		if (node?.children?.length) {
			return node.children.map((c) => this.stubToMember(c));
		}
		// Leaf stub with no children → try real Ext/AMD class (SysSettings, Collection, …)
		const mods = this.getAllByName(`BPMSoft.${rest.join(".")}`).concat(
			this.getAllByName(rest[rest.length - 1])
		);
		if (mods.length) {
			return this.mergeMembers(mods);
		}
		return [];
	}

	private mergeMemberLists(...lists: IndexedMember[][]): IndexedMember[] {
		const map = new Map<string, IndexedMember>();
		for (const list of lists) {
			for (const m of list) {
				if (!map.has(m.name)) {
					map.set(m.name, m);
				}
			}
		}
		return Array.from(map.values());
	}

	private stubToMember(s: PlatformStubMember): IndexedMember {
		return {
			name: s.name,
			kind: s.kind,
			detail: s.detail,
			documentation: s.documentation,
			filePath: s.filePath,
			position: s.position
		};
	}

	private collectInheritanceChain(mod: IndexedModule): IndexedModule[] {
		const out: IndexedModule[] = [];
		const visitedNames = new Set<string>();
		let current: IndexedModule | undefined = mod;
		for (let depth = 0; depth < MAX_INHERIT_DEPTH && current; depth++) {
			const parentName: string | undefined = current.override || current.extend;
			if (!parentName || visitedNames.has(parentName)) {
				break;
			}
			visitedNames.add(parentName);
			const currentPath = current.filePath;
			const candidates: IndexedModule[] = this.getAllByName(parentName).filter(
				(m: IndexedModule) => m.filePath !== currentPath
			);
			if (!candidates.length) {
				break;
			}
			const parent: IndexedModule =
				candidates.find((m: IndexedModule) => !m.override) ||
				candidates.find((m: IndexedModule) =>
					/\/Resources\/ui\//i.test(m.filePath)
				) ||
				candidates.find((m: IndexedModule) =>
					/\/Autogenerated\//i.test(m.filePath)
				) ||
				candidates[0];
			out.push(parent);
			current = parent;
		}
		return out;
	}

	/**
	 * Schema pages: conf/content hierarchy (stack + structureParent + extra Pkg).
	 * Ext modules: own file + override/extend chain.
	 */
	resolveThisMembers(filePath: string): IndexedMember[] {
		const mod = this.getByPath(filePath) || this.ensureModule(filePath);
		if (!mod) {
			return [];
		}

		const chainMods = this.collectOwnerChain(mod);

		const result = this.mergeMembers(chainMods, true);
		const seen = new Set(result.map((m) => memberDedupeKey(m)));
		this.appendMixinMembers(chainMods, result, seen);
		this.appendMixinAccessors(chainMods, result, seen);
		this.appendEntityColumns(chainMods, result, seen);
		this.appendRuntimeThisMembers(result, seen);
		return result;
	}

	/**
	 * Names declared on parents / mixins / entity / core — local overrides of these
	 * are not "unused" even if this file never references them.
	 */
	resolveInheritedSchemaNames(filePath: string): {
		methods: Set<string>;
		attributes: Set<string>;
		messages: Set<string>;
	} {
		const methods = new Set<string>();
		const attributes = new Set<string>();
		const messages = new Set<string>();
		const mod = this.getByPath(filePath) || this.ensureModule(filePath);
		if (!mod) {
			return { methods, attributes, messages };
		}
		const current = filePath.replace(/\\/g, "/");
		const addOwner = (owner: IndexedModule) => {
			if (owner.filePath.replace(/\\/g, "/") === current) {
				return;
			}
			for (const member of owner.members) {
				if (member.kind === "method") {
					methods.add(member.name);
				}
				if (member.kind === "attribute") {
					attributes.add(member.name);
				}
			}
			for (const name of Object.keys(owner.messages || {})) {
				messages.add(name);
			}
		};
		const chainMods = this.collectOwnerChain(mod);
		for (const owner of chainMods) {
			addOwner(owner);
		}
		this.forEachMixinModule(chainMods, addOwner);
		const entity = this.getEntityModuleForChain(chainMods);
		if (entity) {
			for (const member of entity.members) {
				attributes.add(member.name);
			}
		}
		for (const msg of this.coreMessages) {
			messages.add(msg.name);
		}
		return { methods, attributes, messages };
	}

	/**
	 * Members under `this.{path}`, e.g. `mixins`, `mixins.LocalName`, `sandbox`.
	 */
	resolveThisPathMembers(filePath: string, pathAfterThis: string): IndexedMember[] {
		let current = this.resolveThisMembers(filePath);
		const parts = pathAfterThis.split(".").filter(Boolean);
		for (const part of parts) {
			const node = current.find((m) => m.name === part);
			if (!node?.children?.length) {
				return [];
			}
			current = node.children;
		}
		return current;
	}

	/**
	 * messages from the current schema/module, parents, and mixins (child-first).
	 */
	resolveSchemaMessages(filePath: string): Record<string, IndexedSchemaMessage> {
		const mod = this.getByPath(filePath) || this.ensureModule(filePath);
		if (!mod) {
			return {};
		}
		const result: Record<string, IndexedSchemaMessage> = {};
		const add = (owner: IndexedModule) => {
			for (const [name, msg] of Object.entries(owner.messages || {})) {
				if (!(name in result)) {
					result[name] = msg;
				}
			}
		};
		const chainMods = this.collectOwnerChain(mod);
		for (const owner of chainMods) {
			add(owner);
		}
		this.forEachMixinModule(chainMods, add);
		this.appendCoreMessages(result);
		return result;
	}

	resolveSandboxMessages(
		filePath: string,
		action: "publish" | "subscribe"
	): IndexedSchemaMessage[] {
		return Object.values(this.resolveSchemaMessages(filePath))
			.filter((msg) => schemaMessageSupports(msg, action))
			.sort((a, b) => a.name.localeCompare(b.name));
	}

	findSchemaMessageLocations(
		filePath: string,
		messageName: string
	): Array<{
		filePath: string;
		position: { line: number; character: number };
		direction: IndexedSchemaMessage["direction"];
		documentation?: string;
	}> {
		const mod = this.getByPath(filePath) || this.ensureModule(filePath);
		if (!mod || !messageName) {
			return [];
		}
		const hits: Array<{
			filePath: string;
			position: { line: number; character: number };
			direction: IndexedSchemaMessage["direction"];
			documentation?: string;
		}> = [];
		const seen = new Set<string>();
		const consider = (owner: IndexedModule) => {
			if (seen.has(owner.filePath)) {
				return;
			}
			seen.add(owner.filePath);
			const msg = owner.messages?.[messageName];
			if (!msg?.position) {
				return;
			}
			hits.push({
				filePath: owner.filePath,
				position: msg.position,
				direction: msg.direction,
				documentation: msg.documentation
			});
		};
		const chainMods = this.collectOwnerChain(mod);
		for (const owner of chainMods) {
			consider(owner);
		}
		this.forEachMixinModule(chainMods, consider);
		this.appendCoreMessageLocations(hits, seen, messageName);
		return hits;
	}

	private appendCoreMessages(result: Record<string, IndexedSchemaMessage>): void {
		for (const core of this.coreMessages) {
			const existing = result[core.name];
			if (!existing) {
				result[core.name] = core;
				continue;
			}
			if (existing.filePath && existing.filePath !== core.filePath) {
				continue;
			}
			if (existing.direction !== core.direction) {
				existing.direction = "bidirectional";
			}
			existing.documentation = existing.documentation || core.documentation;
			existing.position = existing.position || core.position;
			existing.filePath = existing.filePath || core.filePath;
		}
	}

	private appendCoreMessageLocations(
		hits: Array<{
			filePath: string;
			position: { line: number; character: number };
			direction: IndexedSchemaMessage["direction"];
			documentation?: string;
		}>,
		seen: Set<string>,
		messageName: string
	): void {
		for (const core of this.coreMessages) {
			if (core.name !== messageName || !core.filePath || !core.position) {
				continue;
			}
			if (seen.has(core.filePath)) {
				continue;
			}
			seen.add(core.filePath);
			hits.push({
				filePath: core.filePath,
				position: core.position,
				direction: core.direction,
				documentation: core.documentation
			});
		}
	}

	findThisPathMember(
		filePath: string,
		pathAfterThis: string,
		name: string
	): IndexedMember | undefined {
		return this.resolveThisPathMembers(filePath, pathAfterThis).find(
			(m) => m.name === name
		);
	}

	/**
	 * Parent/mixin methods that can be overridden in the current schema or class.
	 * Current file members are excluded (already defined).
	 */
	resolveOverridableMethods(
		filePath: string
	): Array<{ name: string; params: string[]; owner: string; documentation?: string }> {
		const mod = this.getByPath(filePath) || this.ensureModule(filePath);
		if (!mod) {
			return [];
		}

		const chainMods = this.collectOwnerChain(mod);

		const seen = new Set<string>();
		for (const member of mod.members) {
			if (member.kind === "method") {
				seen.add(member.name);
			}
		}

		const out: Array<{
			name: string;
			params: string[];
			owner: string;
			documentation?: string;
		}> = [];

		const addFrom = (ownerMod: IndexedModule) => {
			if (ownerMod.filePath === mod.filePath) {
				return;
			}
			const owner = inheritdocTarget(ownerMod);
			for (const member of ownerMod.members) {
				if (member.kind !== "method" || seen.has(member.name)) {
					continue;
				}
				seen.add(member.name);
				out.push({
					name: member.name,
					params: member.params || [],
					owner,
					documentation: member.documentation
				});
			}
		};

		for (const ownerMod of chainMods) {
			addFrom(ownerMod);
		}
		this.forEachMixinModule(chainMods, addFrom);
		return out;
	}

	findThisMemberLocations(
		filePath: string,
		memberName: string,
		kind?: IndexedMember["kind"]
	): Array<{ module: IndexedModule; member: IndexedMember }> {
		const mod = this.getByPath(filePath) || this.ensureModule(filePath);
		if (!mod) {
			return [];
		}
		const hits: Array<{ module: IndexedModule; member: IndexedMember }> = [];
		const seenPaths = new Set<string>();
		const dollar = memberName.startsWith("$") && memberName.length > 1;
		const lookupName = dollar ? memberName.slice(1) : memberName;
		const requiredKind = kind || (dollar ? "attribute" : undefined);

		const consider = (m: IndexedModule) => {
			if (seenPaths.has(m.filePath)) {
				return;
			}
			seenPaths.add(m.filePath);
			for (const member of m.members) {
				if (member.name !== lookupName) {
					continue;
				}
				if (requiredKind && member.kind !== requiredKind) {
					continue;
				}
				if (!member.position) {
					continue;
				}
				hits.push({ module: m, member });
			}
		};

		const chainMods = this.collectOwnerChain(mod);

		for (const m of chainMods) {
			consider(m);
		}
		this.forEachMixinModule(chainMods, consider);
		const entityMod = this.getEntityModuleForChain(chainMods);
		if (entityMod) {
			consider(entityMod);
		}
		return hits;
	}

	private collectOwnerChain(mod: IndexedModule): IndexedModule[] {
		return isPageSchema(mod)
			? this.collectSchemaHierarchyModules(mod)
			: [mod, ...this.collectInheritanceChain(mod)];
	}

	private collectSchemaHierarchyModules(mod: IndexedModule): IndexedModule[] {
		const ordered: IndexedModule[] = [];
		const seen = new Set<string>();

		const push = (m: IndexedModule | undefined) => {
			if (!m || seen.has(m.filePath)) {
				return;
			}
			seen.add(m.filePath);
			ordered.push(m);
		};

		// Current file first (most specific while editing)
		push(mod);

		if (this.hierarchy.hasRoots()) {
			const layers = this.hierarchy.resolveSchemaLayers(mod.name, mod.filePath);
			for (const layer of layers) {
				push(this.ensureModule(layer.filePath));
			}
		} else {
			// Fallback without conf: same-name replacements, current first already done
			for (const sibling of this.getAllByName(mod.name)) {
				push(sibling);
			}
		}

		// Runtime parent of every client schema: ViewModelGenerator.baseViewModelClassName
		this.appendExtClassChain(this.schemaViewModelClassName(), push);
		this.appendExtClassChain(
			this.hierarchy.resolvePlatformExtendClass(mod.name),
			push
		);

		return ordered;
	}

	/**
	 * Ext class that SchemaBuilder uses as the root of generated schema view models.
	 * Vanilla Creatio: BPMSoft.BaseSchemaViewModel (not listed in structureParent).
	 */
	private schemaViewModelClassName(): string {
		const generator =
			this.pickNamedModule("BPMSoft.ViewModelGenerator") ||
			this.pickNamedModule("ViewModelGeneratorV2");
		const member = generator?.members.find(
			(m) => m.name === "baseViewModelClassName"
		);
		const raw = `${member?.detail || ""} ${member?.documentation || ""}`;
		const match = raw.match(/BPMSoft(?:\.\w+)+/);
		return match?.[0] || "BPMSoft.BaseSchemaViewModel";
	}

	private appendExtClassChain(
		className: string | undefined,
		push: (m?: IndexedModule) => void
	): void {
		if (!className) {
			return;
		}
		const root = this.pickNamedModule(className);
		if (!root) {
			return;
		}
		push(root);
		for (const parent of this.collectInheritanceChain(root)) {
			push(parent);
		}
	}

	private pickNamedModule(name: string): IndexedModule | undefined {
		const candidates = this.getAllByName(name);
		if (!candidates.length) {
			return undefined;
		}
		return (
			candidates.find(
				(m) => !m.override && /\/Resources\/ui\//i.test(m.filePath)
			) ||
			candidates.find((m) => !m.override) ||
			candidates.find((m) => /\/Resources\/ui\//i.test(m.filePath)) ||
			candidates[0]
		);
	}

	private declaredMixins(
		owners: IndexedModule[]
	): Array<{ localName: string; className: string }> {
		const out: Array<{ localName: string; className: string }> = [];
		const seen = new Set<string>();
		for (const schemaMod of owners) {
			for (const [localName, className] of Object.entries(schemaMod.mixins)) {
				if (seen.has(localName)) {
					continue;
				}
				seen.add(localName);
				out.push({ localName, className });
			}
		}
		return out;
	}

	private mixinModulesForClass(className: string): IndexedModule[] {
		const short = className.replace(/^BPMSoft\./, "");
		const mixinMods = this.getAllByName(className).concat(this.getAllByName(short));
		const unique = new Map<string, IndexedModule>();
		for (const m of mixinMods) {
			unique.set(m.filePath, m);
		}
		return Array.from(unique.values());
	}

	private forEachMixinModule(
		owners: IndexedModule[],
		visit: (mod: IndexedModule) => void
	): void {
		const seen = new Set<string>();
		for (const { className } of this.declaredMixins(owners)) {
			for (const mixinMod of this.mixinModulesForClass(className)) {
				if (seen.has(mixinMod.filePath)) {
					continue;
				}
				seen.add(mixinMod.filePath);
				visit(mixinMod);
			}
		}
	}

	private mixinMembersFromModules(mods: IndexedModule[]): IndexedMember[] {
		const result: IndexedMember[] = [];
		const seen = new Set<string>();
		for (const mixinMod of mods) {
			for (const member of mixinMod.members) {
				const key = memberDedupeKey(member);
				if (seen.has(key)) {
					continue;
				}
				seen.add(key);
				result.push({
					...member,
					filePath: member.filePath || mixinMod.filePath,
					detail:
						member.detail ||
						`mixin ${mixinMod.name} (${packageLabel(mixinMod.filePath)})`
				});
			}
		}
		return result;
	}

	private mixinMembersForClass(className: string): IndexedMember[] {
		return this.mixinMembersFromModules(this.mixinModulesForClass(className));
	}

	private mixinAccessorMember(
		localName: string,
		className: string
	): IndexedMember {
		const mods = this.mixinModulesForClass(className);
		const origin = mods[0];
		return {
			name: localName,
			kind: "namespace",
			detail: `mixin ${className}`,
			documentation: `Миксин ${className}`,
			children: this.mixinMembersFromModules(mods),
			filePath: origin?.filePath,
			position:
				origin?.members[0]?.position ||
				(origin ? { line: 0, character: 0 } : undefined)
		};
	}

	private appendMixinMembers(
		owners: IndexedModule[],
		result: IndexedMember[],
		seen: Set<string>
	): void {
		const mixinAlts = new Set(
			this.declaredMixins(owners).map((item) => item.className)
		);
		for (const alt of mixinAlts) {
			for (const member of this.mixinMembersForClass(alt)) {
				const key = memberDedupeKey(member);
				if (seen.has(key)) {
					continue;
				}
				seen.add(key);
				result.push(member);
			}
		}
	}

	/**
	 * `this.LocalMixin` and `this.mixins.LocalMixin` with mixin methods as children.
	 */
	private appendMixinAccessors(
		owners: IndexedModule[],
		result: IndexedMember[],
		seen: Set<string>
	): void {
		const declared = this.declaredMixins(owners);
		if (!declared.length) {
			return;
		}
		const mixinItems = declared.map((item) =>
			this.mixinAccessorMember(item.localName, item.className)
		);
		for (const item of mixinItems) {
			if (seen.has(item.name)) {
				continue;
			}
			seen.add(item.name);
			result.push(item);
		}
		const mixinsMember: IndexedMember = {
			name: "mixins",
			kind: "property",
			detail: "schema mixins",
			documentation:
				"Миксины схемы и иерархии: this.mixins.Name и this.Name",
			children: mixinItems
		};
		const existing = result.findIndex((m) => m.name === "mixins");
		if (existing >= 0) {
			result[existing] = mixinsMember;
		} else {
			result.push(mixinsMember);
		}
		seen.add("mixins");
	}

	private appendRuntimeThisMembers(
		result: IndexedMember[],
		seen: Set<string>
	): void {
		const runtime: IndexedMember[] = [
			{
				name: "Ext",
				kind: "property",
				detail: "injected Ext",
				documentation:
					"Экземпляр Ext модуля (тот же API, что у глобального Ext)"
			},
			{
				name: "BPMSoft",
				kind: "property",
				detail: "injected BPMSoft",
				documentation:
					"Экземпляр BPMSoft модуля (тот же API, что у глобального BPMSoft)"
			},
			{
				name: "sandbox",
				kind: "property",
				detail: "module sandbox",
				documentation:
					"Песочница модуля: publish / subscribe / loadModule",
				children: this.getSandboxMembers(),
				filePath: this.sandboxOrigin?.filePath,
				position: this.sandboxOrigin?.position
			}
		];
		for (const member of runtime) {
			const key = memberDedupeKey(member);
			const existingIdx = result.findIndex((m) => memberDedupeKey(m) === key);
			if (existingIdx >= 0) {
				const existing = result[existingIdx];
				if (member.children?.length && !existing.children?.length) {
					result[existingIdx] = {
						...existing,
						children: member.children,
						documentation: existing.documentation || member.documentation,
						filePath: existing.filePath || member.filePath,
						position: existing.position || member.position
					};
				}
				continue;
			}
			seen.add(key);
			result.push(member);
		}
	}

	private getSandboxMembers(): IndexedMember[] {
		if (this.sandboxMembers.length) {
			return this.sandboxMembers;
		}
		const built = buildSandboxStubs(this.workspaceRoots);
		this.sandboxMembers = built.members;
		this.sandboxOrigin = built.origin;
		return this.sandboxMembers;
	}

	private appendEntityColumns(
		owners: IndexedModule[],
		result: IndexedMember[],
		seen: Set<string>
	): void {
		const entityMod = this.getEntityModuleForChain(owners);
		if (!entityMod) {
			return;
		}
		for (const member of entityMod.members) {
			const key = memberDedupeKey(member);
			if (seen.has(key)) {
				continue;
			}
			seen.add(key);
			result.push({
				...member,
				detail: member.detail || `entity ${entityMod.name}`,
				filePath: member.filePath || entityMod.filePath
			});
		}
	}

	private getEntityModuleForChain(
		owners: IndexedModule[]
	): IndexedModule | undefined {
		const entityName = owners
			.map((m) => m.entitySchemaName)
			.find((name): name is string => Boolean(name));
		if (!entityName) {
			return undefined;
		}
		return this.getEntityModule(entityName);
	}

	private getEntityModule(entityName: string): IndexedModule | undefined {
		if (this.entityCache.has(entityName)) {
			return this.entityCache.get(entityName) || undefined;
		}
		const filePath = this.hierarchy.resolveEntitySchemaPath(entityName);
		if (!filePath) {
			this.entityCache.set(entityName, null);
			return undefined;
		}
		try {
			const source = fs.readFileSync(filePath, "utf8");
			const members = parseEntityColumns(source, filePath);
			const mod: IndexedModule = {
				name: entityName,
				filePath,
				kind: "unknown",
				dependencies: [],
				paramNames: [],
				members,
				mixins: {},
				messages: {},
				entitySchemaName: entityName
			};
			this.entityCache.set(entityName, mod);
			return mod;
		} catch {
			this.entityCache.set(entityName, null);
			return undefined;
		}
	}

	resolveLocalAlias(filePath: string, alias: string): string | undefined {
		const mod = this.getByPath(filePath);
		if (!mod) {
			return undefined;
		}
		if (alias === mod.name) {
			return mod.name;
		}
		const idx = mod.paramNames.indexOf(alias);
		if (idx >= 0 && idx < mod.dependencies.length) {
			return mod.dependencies[idx];
		}
		if (mod.dependencies.includes(alias)) {
			return alias;
		}
		return undefined;
	}

	private mergeMembers(
		mods: IndexedModule[],
		annotateSource = false
	): IndexedMember[] {
		const result: IndexedMember[] = [];
		const seen = new Set<string>();
		for (const mod of mods) {
			const label = packageLabel(mod.filePath);
			for (const member of mod.members) {
				const key = memberDedupeKey(member);
				if (seen.has(key)) {
					continue;
				}
				seen.add(key);
				result.push(
					annotateSource
						? {
								...member,
								detail: member.detail || label,
								filePath: member.filePath || mod.filePath
							}
						: member
				);
			}
		}
		return result;
	}

	private pushNamed(
		map: Map<string, IndexedModule[]>,
		key: string,
		mod: IndexedModule
	): void {
		const list = map.get(key);
		if (list) {
			list.push(mod);
		} else {
			map.set(key, [mod]);
		}
	}

	private pullNamed(
		map: Map<string, IndexedModule[]>,
		key: string,
		filePath: string
	): void {
		const list = map.get(key);
		if (!list) {
			return;
		}
		const next = list.filter((m) => m.filePath !== filePath);
		if (next.length) {
			map.set(key, next);
		} else {
			map.delete(key);
		}
	}
}
