import * as fs from "fs";
import * as path from "path";

export type WorkspaceLayoutKind =
	| "app-root"
	| "configuration"
	| "pkg"
	| "package"
	| "unknown";

/**
 * Resolved locations for a BPMSoft/Creatio app, independent of which
 * subfolder the user opened as the workspace.
 */
export interface BpmsoftAppLayout {
	kind: WorkspaceLayoutKind;
	/** Folder the user opened */
	workspaceRoot: string;
	/**
	 * App root: contains conf/, Resources/, BPMSoft.Configuration/
	 * (e.g. bpmsoftdevelopment)
	 */
	appRoot?: string;
	/** …/BPMSoft.Configuration */
	configurationRoot?: string;
	/** …/BPMSoft.Configuration/Pkg */
	pkgRoot?: string;
	/** …/conf/content */
	confContent?: string;
	/** …/Resources */
	resourcesRoot?: string;
	/** …/BPMSoft.Configuration/Autogenerated */
	autogeneratedRoot?: string;
}

export interface DevDotnetProject {
	configurationRoot: string;
	csprojPath: string;
	/** Path to Dev.sln — file may be created later if missing. */
	slnPath: string;
}

/**
 * Detect app layout from a workspace folder path.
 *
 * Detection only walks upward from the opened folder; a parent directory
 * that merely contains nested BPMSoft apps is not a supported workspace
 * (returns kind "unknown").
 *
 * Supported open roots:
 * - app root
 * - BPMSoft.Configuration
 * - BPMSoft.Configuration/Pkg
 * - BPMSoft.Configuration/Pkg/{PackageName}
 */
export function resolveAppLayout(workspaceRoot: string): BpmsoftAppLayout {
	const ws = path.resolve(workspaceRoot);
	const base: BpmsoftAppLayout = {
		kind: "unknown",
		workspaceRoot: ws
	};

	// 1) Explicit markers walking upward
	const byWalk = detectByWalkingUp(ws);
	if (byWalk) {
		return byWalk;
	}

	// 2) Heuristics by folder name
	const name = path.basename(ws);
	const parent = path.dirname(ws);
	const parentName = path.basename(parent);
	const grand = path.dirname(parent);
	const grandName = path.basename(grand);

	if (name === "BPMSoft.Configuration" && looksLikeConfiguration(ws)) {
		return fillFromConfiguration(ws, "configuration", ws);
	}

	if (name === "Pkg" && parentName === "BPMSoft.Configuration") {
		return fillFromConfiguration(parent, "pkg", ws);
	}

	if (parentName === "Pkg" && grandName === "BPMSoft.Configuration") {
		return fillFromConfiguration(grand, "package", ws);
	}

	if (isAppRoot(ws)) {
		return fillFromAppRoot(ws, "app-root", ws);
	}

	return base;
}

export function resolveAppLayouts(workspaceRoots: string[]): BpmsoftAppLayout[] {
	const seen = new Set<string>();
	const out: BpmsoftAppLayout[] = [];
	for (const root of workspaceRoots) {
		const layout = resolveAppLayout(root);
		const key =
			layout.configurationRoot ||
			layout.appRoot ||
			layout.workspaceRoot;
		const norm = path.normalize(key);
		if (seen.has(norm)) {
			continue;
		}
		seen.add(norm);
		out.push(layout);
	}
	return out;
}

export function isSupportedBpmsoftLayout(layout: BpmsoftAppLayout): boolean {
	return layout.kind !== "unknown";
}

export function supportedAppLayouts(
	layouts: BpmsoftAppLayout[]
): BpmsoftAppLayout[] {
	return layouts.filter(isSupportedBpmsoftLayout);
}

/** BPMSoft.Configuration.Dev.csproj / .sln that feeds C# IntelliSense for Pkg + Autogenerated. */
export function findDevDotnetProject(
	layout: BpmsoftAppLayout
): DevDotnetProject | undefined {
	const configurationRoot = layout.configurationRoot;
	if (!configurationRoot) {
		return undefined;
	}
	const csprojPath = path.join(
		configurationRoot,
		"BPMSoft.Configuration.Dev.csproj"
	);
	if (!fs.existsSync(csprojPath)) {
		return undefined;
	}
	const slnPath = path.join(
		configurationRoot,
		"BPMSoft.Configuration.Dev.sln"
	);
	return {
		configurationRoot,
		csprojPath,
		slnPath
	};
}

/** Always the Dev .sln path (created on demand if the file is missing). */
export function devDotnetLoadFile(project: DevDotnetProject): string {
	return project.slnPath;
}

export function pathRelativePosix(fromDir: string, absFile: string): string {
	return path.relative(fromDir, absFile).replace(/\\/g, "/");
}

export function findDevDotnetProjects(
	layouts: BpmsoftAppLayout[]
): DevDotnetProject[] {
	const seen = new Set<string>();
	const out: DevDotnetProject[] = [];
	for (const layout of layouts) {
		const project = findDevDotnetProject(layout);
		if (!project) {
			continue;
		}
		const key = path.normalize(project.csprojPath);
		if (seen.has(key)) {
			continue;
		}
		seen.add(key);
		out.push(project);
	}
	return out;
}

function detectByWalkingUp(start: string): BpmsoftAppLayout | undefined {
	let current = start;
	for (let i = 0; i < 8; i++) {
		if (isAppRoot(current)) {
			const kind =
				path.normalize(current) === path.normalize(start)
					? "app-root"
					: inferKindRelativeToApp(start, current);
			return fillFromAppRoot(current, kind, start);
		}
		const cfg = path.join(current, "BPMSoft.Configuration");
		if (looksLikeConfiguration(cfg)) {
			const kind =
				path.normalize(current) === path.normalize(start)
					? "app-root"
					: inferKindRelativeToApp(start, current);
			return fillFromAppRoot(current, kind, start);
		}
		if (looksLikeConfiguration(current)) {
			const kind =
				path.basename(start) === "BPMSoft.Configuration" &&
				path.normalize(start) === path.normalize(current)
					? "configuration"
					: inferKindRelativeToConfiguration(start, current);
			return fillFromConfiguration(current, kind, start);
		}
		const parent = path.dirname(current);
		if (parent === current) {
			break;
		}
		current = parent;
	}
	return undefined;
}

function inferKindRelativeToApp(
	workspace: string,
	appRoot: string
): WorkspaceLayoutKind {
	const rel = path.relative(appRoot, workspace).replace(/\\/g, "/");
	if (!rel || rel === ".") {
		return "app-root";
	}
	if (rel === "BPMSoft.Configuration") {
		return "configuration";
	}
	if (rel === "BPMSoft.Configuration/Pkg") {
		return "pkg";
	}
	if (/^BPMSoft\.Configuration\/Pkg\/[^/]+$/.test(rel)) {
		return "package";
	}
	return "app-root";
}

function inferKindRelativeToConfiguration(
	workspace: string,
	configurationRoot: string
): WorkspaceLayoutKind {
	const rel = path.relative(configurationRoot, workspace).replace(/\\/g, "/");
	if (!rel || rel === ".") {
		return "configuration";
	}
	if (rel === "Pkg") {
		return "pkg";
	}
	if (/^Pkg\/[^/]+$/.test(rel)) {
		return "package";
	}
	return "configuration";
}

function isAppRoot(dir: string): boolean {
	const conf = path.join(dir, "conf", "content");
	const cfg = path.join(dir, "BPMSoft.Configuration");
	const resources = path.join(dir, "Resources");
	return (
		fs.existsSync(conf) &&
		(looksLikeConfiguration(cfg) || fs.existsSync(resources))
	);
}

function looksLikeConfiguration(dir: string): boolean {
	if (!fs.existsSync(dir)) {
		return false;
	}
	return (
		fs.existsSync(path.join(dir, "Pkg")) ||
		fs.existsSync(path.join(dir, "Autogenerated"))
	);
}

function fillFromAppRoot(
	appRoot: string,
	kind: WorkspaceLayoutKind,
	workspaceRoot: string
): BpmsoftAppLayout {
	const configurationRoot = path.join(appRoot, "BPMSoft.Configuration");
	const confContent = path.join(appRoot, "conf", "content");
	const resourcesRoot = path.join(appRoot, "Resources");
	return {
		kind,
		workspaceRoot,
		appRoot,
		configurationRoot: looksLikeConfiguration(configurationRoot)
			? configurationRoot
			: undefined,
		pkgRoot: fs.existsSync(path.join(configurationRoot, "Pkg"))
			? path.join(configurationRoot, "Pkg")
			: undefined,
		confContent: fs.existsSync(confContent) ? confContent : undefined,
		resourcesRoot: fs.existsSync(resourcesRoot) ? resourcesRoot : undefined,
		autogeneratedRoot: fs.existsSync(
			path.join(configurationRoot, "Autogenerated")
		)
			? path.join(configurationRoot, "Autogenerated")
			: undefined
	};
}

function fillFromConfiguration(
	configurationRoot: string,
	kind: WorkspaceLayoutKind,
	workspaceRoot: string
): BpmsoftAppLayout {
	const appRoot = path.dirname(configurationRoot);
	const confContent = path.join(appRoot, "conf", "content");
	const resourcesRoot = path.join(appRoot, "Resources");
	const appRootUsable =
		isAppRoot(appRoot) ||
		fs.existsSync(confContent) ||
		fs.existsSync(resourcesRoot);
	return {
		kind,
		workspaceRoot,
		appRoot: appRootUsable ? appRoot : undefined,
		configurationRoot,
		pkgRoot: fs.existsSync(path.join(configurationRoot, "Pkg"))
			? path.join(configurationRoot, "Pkg")
			: undefined,
		confContent: fs.existsSync(confContent) ? confContent : undefined,
		resourcesRoot: fs.existsSync(resourcesRoot) ? resourcesRoot : undefined,
		autogeneratedRoot: fs.existsSync(
			path.join(configurationRoot, "Autogenerated")
		)
			? path.join(configurationRoot, "Autogenerated")
			: undefined
	};
}

/** Collect JS files under a directory matching a simple recursive filter. */
export function walkJsFiles(
	rootDir: string,
	predicate: (absPath: string) => boolean,
	maxFiles = 200000
): string[] {
	const out: string[] = [];
	if (!rootDir || !fs.existsSync(rootDir)) {
		return out;
	}

	const stack = [rootDir];
	while (stack.length && out.length < maxFiles) {
		const dir = stack.pop()!;
		let entries: fs.Dirent[];
		try {
			entries = fs.readdirSync(dir, { withFileTypes: true });
		} catch {
			continue;
		}
		for (const ent of entries) {
			if (ent.name === "node_modules" || ent.name === ".git") {
				continue;
			}
			const full = path.join(dir, ent.name);
			if (ent.isDirectory()) {
				stack.push(full);
				continue;
			}
			if (ent.isFile() && ent.name.endsWith(".js") && predicate(full)) {
				out.push(full);
			}
		}
	}
	return out;
}

export function uniquePaths(paths: string[]): string[] {
	return Array.from(new Set(paths.map((p) => path.normalize(p))));
}

export function collectLayoutDirs(
	layouts: BpmsoftAppLayout[],
	pick: (layout: BpmsoftAppLayout) => string | undefined,
	fallbackRoots: string[],
	fallbackRel: string
): string[] {
	const dirs = layouts
		.map(pick)
		.filter((p): p is string => Boolean(p));
	if (!dirs.length) {
		for (const root of fallbackRoots) {
			dirs.push(path.join(root, fallbackRel));
		}
	}
	return dirs;
}

export function collectResourceRoots(
	layouts: BpmsoftAppLayout[],
	fallbackRoots: string[]
): string[] {
	return collectLayoutDirs(
		layouts,
		(layout) => layout.resourcesRoot,
		fallbackRoots,
		"Resources"
	);
}

export function collectSearchRoots(
	layouts: BpmsoftAppLayout[],
	extraRoots: string[]
): string[] {
	const roots = new Set<string>();
	for (const layout of layouts) {
		if (layout.appRoot) {
			roots.add(layout.appRoot);
		}
		roots.add(layout.workspaceRoot);
	}
	for (const root of extraRoots) {
		roots.add(root);
	}
	return Array.from(roots);
}

export function existingJoinedFiles(roots: string[], rels: string[]): string[] {
	const files: string[] = [];
	for (const root of roots) {
		for (const rel of rels) {
			const full = path.join(root, rel);
			if (fs.existsSync(full)) {
				files.push(full);
			}
		}
	}
	return Array.from(new Set(files));
}
