/**
 * Catalog of `WorkspaceConsole` operations and their command-line parameters —
 * reverse-engineered directly from `BPMSoft.Tools.WorkspaceConsole.dll` /
 * `BPMSoft.Tools.Common.dll` (decompiled with ilspycmd against a real 1.9.1
 * install, 2026-09-09), not from Creatio documentation — BPMSoft's own build
 * has both renamed and added/removed operations relative to stock Creatio, so
 * the Creatio Academy parameter tables don't reliably apply here.
 *
 * Ground truth used to build this table:
 * - `WorkspaceConsoleOperation` enum (`BPMSoft.Tools.WorkspaceConsole.dll`,
 *   XML doc) — the full set of operation names.
 * - `WorkspaceConsoleApplication.ExecuteOperation`'s `switch` — only ~62 of
 *   the 69 enum values actually have a `case`; the rest (`UpdatePackages`,
 *   `SaveVersionSvnContent`, `InstallBundlePackages`, `ConcatSvnRepositories`,
 *   `InstallTestPackages`, `InstallUnitTestPackages`,
 *   `InstallTestPackagesBySuffix`) fall through to `default` and throw
 *   `UnsupportedTypeException` — dead in this build, deliberately omitted
 *   below rather than offered as buttons that can't work.
 * - Each operation's own method body — every `CheckRequiredCommandLineParameter(name, ...)`
 *   call is a hard requirement; the exact CLI flag string is each field's own
 *   `...OptionName` constant value (read via reflection), not guessed from
 *   the C# property name — several differ in casing/spelling from their
 *   property (`CultureName` reads flag `culturename`, all-lowercase;
 *   `PublishAngularComponentOnlySystemPackages` reads flag
 *   `onlySystemPackages`).
 * - `WorkspaceConsoleCommandLine.CommandsWithRequiredConfRuntimeParentDirectoryParameter`
 *   — the exact list of operations where `confRuntimeParentDirectory` is
 *   enforced by `Validate()` before the operation even runs.
 * - `BaseApplicationCommandLine<TOperations>`'s own registered parameters —
 *   `-operation`, `-user`, `-workspaceName` are `IsRequired = true` for
 *   *every* operation; `-password`/`-autoExit`/`-logPath` are optional. Note
 *   the flag is `-user`/`-password`, not `-userName`/`-userPassword` despite
 *   the C# properties being named that way.
 *
 * Not modeled here (by design, not oversight): every operation's long tail of
 * filter/tuning options (`includedSchemas`, `excludedSchemaColumns`,
 * `schemaManagerNames`, `validate*`, ...) — modeling exhaustively would bloat
 * the form for little real benefit. Only parameters that are hard-required or
 * commonly needed are exposed as typed fields; the panel also offers a free
 * "additional arguments" text box appended verbatim to the generated command
 * line for anything else (see `WorkspaceConsoleOperationsPanel`).
 */

export type WCParamKind = "text" | "path" | "bool" | "int" | "password";

export interface WCParam {
	/** Exact CLI option name, e.g. the command line reads it as `-flag=value`. */
	flag: string;
	label: string;
	kind: WCParamKind;
	required?: boolean;
	hint?: string;
	/** Pre-fill from the app root path when the field is first shown. */
	defaultFromAppRoot?: boolean;
}

export interface WCOperation {
	/** Exact `WorkspaceConsoleOperation` enum member name. */
	op: string;
	category: string;
	caption: string;
	description: string;
	params: WCParam[];
	/** Mutates/deletes existing data (DB rows, files, packages) — shown with an extra confirmation. */
	destructive?: boolean;
}

/** Always shown, on every operation — required by `BaseApplicationCommandLine<T>`/`Validate()` regardless of operation. */
export const WORKSPACE_CONSOLE_BASE_PARAMS: WCParam[] = [
	{ flag: "user", label: "Пользователь", kind: "text", required: true, hint: "-user — логин администратора BPMSoft. Обязателен для любой операции." },
	{ flag: "password", label: "Пароль", kind: "password", hint: "-password — пароль пользователя. Формально необязателен, но нужен почти всегда." },
	{ flag: "workspaceName", label: "Рабочее пространство", kind: "text", required: true, hint: "-workspaceName — обязателен для любой операции (даже если рабочее пространство одно — обычно \"Default\")." },
	{ flag: "webApplicationPath", label: "Путь к приложению (webApplicationPath)", kind: "path", defaultFromAppRoot: true, hint: "-webApplicationPath — корень развёрнутого приложения. Один из двух способов сказать WorkspaceConsole, с каким приложением работать (см. configurationPath)." },
	{ flag: "configurationPath", label: "Путь к BPMSoft.Configuration (configurationPath)", kind: "path", hint: "-configurationPath — альтернатива webApplicationPath, путь прямо к папке BPMSoft.Configuration (так вызывают из Docker-контейнера, см. wrapper-скрипты вида _BuildWorkspace.bat)." },
	{ flag: "confRuntimeParentDirectory", label: "Родительская папка Autogenerated (confRuntimeParentDirectory)", kind: "path", hint: "-confRuntimeParentDirectory — обязателен для ряда операций сборки/установки (отмечено ниже); это родительская папка для BPMSoft.Configuration/Autogenerated." },
	{ flag: "autoExit", label: "Автозавершение (autoExit)", kind: "bool", hint: "-autoExit=true — не ждать нажатия клавиши после завершения (нужно для запуска из скрипта/CI)." },
	{ flag: "logPath", label: "Путь к логам (logPath)", kind: "path", hint: "-logPath — папка для файла лога (по умолчанию Logs рядом с WorkspaceConsole)." }
];

const P = (flag: string, label: string, kind: WCParamKind, opts: Partial<WCParam> = {}): WCParam => ({ flag, label, kind, ...opts });

const sourcePath = () => P("sourcePath", "Источник (sourcePath)", "path", { required: true });
const destinationPath = () => P("destinationPath", "Назначение (destinationPath)", "path", { required: true });
const packageName = (hint?: string) => P("packageName", "Пакет(ы) (packageName)", "text", { hint: hint ?? "Одно имя или несколько через запятую." });
const continueIfError = () => P("continueIfError", "Продолжать при ошибках (continueIfError)", "bool");

/** Shared "install options" group — read by `GetInstallOptions()`, applied to every install-style operation. */
const installOptionParams = (): WCParam[] => [
	packageName(),
	P("clearWorkspace", "Очистить пространство перед установкой (clearWorkspace)", "bool"),
	P("updatePackageHierarchy", "Обновить иерархию пакетов (updatePackageHierarchy)", "bool", { hint: "По умолчанию true у самого WorkspaceConsole." }),
	P("installPackageData", "Устанавливать данные пакета (installPackageData)", "bool"),
	P("installPackageSqlScript", "Выполнять SQL-скрипты пакета (installPackageSqlScript)", "bool"),
	P("regenerateSchemaSources", "Перегенерировать исходники схем (regenerateSchemaSources)", "bool"),
	P("updateDBStructure", "Обновлять структуру БД (updateDBStructure)", "bool"),
	P("updateSystemDBStructure", "Обновлять структуру системных таблиц (updateSystemDBStructure)", "bool"),
	continueIfError(),
	P("skipConstraints", "Пропустить ограничения БД (skipConstraints)", "bool"),
	P("skipCompile", "Не компилировать (skipCompile)", "bool")
];

export const WORKSPACE_CONSOLE_OPERATIONS: WCOperation[] = [
	// --- Сборка и компиляция ---------------------------------------------
	{
		op: "BuildWorkspace",
		category: "Сборка и компиляция",
		caption: "Собрать рабочее пространство",
		description: "Компилирует изменённые схемы (C#, Angular) из файловой системы. Эквивалент кнопки «Компиляция» в Configuration.",
		params: [continueIfError()]
	},
	{
		op: "RebuildWorkspace",
		category: "Сборка и компиляция",
		caption: "Пересобрать рабочее пространство (полностью)",
		description: "То же, что «Собрать», но force=true — пересобирает вообще все схемы, а не только изменённые. Долго.",
		params: [continueIfError()]
	},
	{
		op: "UpdateWorkspaceSolution",
		category: "Сборка и компиляция",
		caption: "Обновить .sln/.csproj для Visual Studio",
		description: "Перегенерирует файлы решения/проектов Visual Studio под текущий состав пакетов.",
		params: []
	},
	{
		op: "BuildAngularModules",
		category: "Сборка и компиляция",
		caption: "Собрать изменённые Angular-модули",
		description: "Собирает только изменённые Angular-модули (в отличие от «Собрать рабочее пространство», не трогает C#).",
		params: []
	},
	{
		op: "RebuildAngularModules",
		category: "Сборка и компиляция",
		caption: "Пересобрать все Angular-модули",
		description: "То же самое, но force=true — пересобирает все Angular-модули, не только изменённые.",
		params: []
	},
	{
		op: "PublishAngularComponentsInPackages",
		category: "Сборка и компиляция",
		caption: "Опубликовать Angular-компоненты в пакетах",
		description: "Публикует ещё не опубликованные Angular-компоненты (нужно после сборки рендер-приложения).",
		params: [P("onlySystemPackages", "Только системные пакеты (onlySystemPackages)", "bool", { hint: "По умолчанию true." })]
	},
	{
		op: "BuildConfiguration",
		category: "Сборка и компиляция",
		caption: "Собрать конфигурацию (клиентский контент)",
		description: "Генерирует runtime-контент (conf\\content) — то, что реально отдаётся браузеру. Использует IBuildConfigurationOperation.",
		params: [
			destinationPath(),
			P("force", "Собрать всё, не только изменённое (force)", "bool"),
			P("generateStaticContent", "Генерировать статический контент (generateStaticContent)", "bool", { hint: "По умолчанию true." })
		]
	},
	{
		op: "GenerateRequiredSourceCode",
		category: "Сборка и компиляция",
		caption: "Догенерировать устаревший исходный код схем",
		description: "Устанавливает связанные данные схем с устаревшими исходниками и пересобирает рабочее пространство.",
		params: []
	},
	{
		op: "RegenerateSchemaSources",
		category: "Сборка и компиляция",
		caption: "Обновить связанные данные схем + пересобрать",
		description: "UpdateSchemasAssociatedData() + BuildWorkspace() одним вызовом.",
		params: []
	},

	// --- Установка и обновление пакетов -----------------------------------
	{
		op: "PrevalidateInstallFromRepository",
		category: "Установка и обновление пакетов",
		caption: "Проверить архив перед установкой (без изменений в БД)",
		description: "Прогоняет валидацию пакетов из ZIP-архива хранилища относительно текущей БД, ничего не сохраняя — безопасный «сухой прогон» перед InstallFromRepository.",
		params: [sourcePath(), destinationPath()]
	},
	{
		op: "InstallFromRepository",
		category: "Установка и обновление пакетов",
		caption: "Установить пакеты из ZIP-архива хранилища",
		description: "Основная операция доставки — распаковывает и устанавливает пакеты из архива(ов) хранилища в БД.",
		params: [sourcePath(), destinationPath(), ...installOptionParams()],
		destructive: true
	},
	{
		op: "InstallPackages",
		category: "Установка и обновление пакетов",
		caption: "Установить пакеты (то же, что «Установить из архива»)",
		description: "Отдельное имя операции, обрабатывается тем же кодом, что InstallFromRepository (используется, когда исходник — уже распакованные пакеты).",
		params: [sourcePath(), destinationPath(), ...installOptionParams()],
		destructive: true
	},
	{
		op: "InstallPackagesFromWorkingCopy",
		category: "Установка и обновление пакетов",
		caption: "Установить пакеты из рабочей копии (несжатые файлы)",
		description: "Устанавливает пакеты прямо из папки \\SvnPackages рабочей копии, без промежуточного ZIP.",
		params: [
			P("workingCopyPath", "Путь к рабочей копии (workingCopyPath)", "path", { required: true }),
			P("culturename", "Культура (culturename)", "text", { hint: "Внимание: флаг именно culturename, одним словом в нижнем регистре — не cultureName." }),
			P("removeConfigurationComments", "Удалить комментарии из исходников перед установкой (removeConfigurationComments)", "bool"),
			...installOptionParams()
		],
		destructive: true
	},
	{
		op: "InstallZipPackage",
		category: "Установка и обновление пакетов",
		caption: "Установить один пакет из ZIP",
		description: "Устанавливает ровно один пакет из ZIP-архива (IInstallZipPackageOperation) — точечная доставка одного пакета, а не всего хранилища.",
		params: [sourcePath(), destinationPath(), ...installOptionParams()],
		destructive: true
	},
	{
		op: "LoadPackagesToFileSystem",
		category: "Установка и обновление пакетов",
		caption: "Выгрузить пакеты из БД в файловую систему",
		description: "Обратная операция — сохраняет пакеты из БД в Pkg\\ (файловый режим разработки).",
		params: []
	},
	{
		op: "LoadPackagesToDB",
		category: "Установка и обновление пакетов",
		caption: "Загрузить пакеты из файловой системы в БД",
		description: "Загружает пакеты из Pkg\\ обратно в БД.",
		params: [...installOptionParams()],
		destructive: true
	},
	{
		op: "InstallRequiredSqlScripts",
		category: "Установка и обновление пакетов",
		caption: "Доустановить неустановленные SQL-скрипты",
		description: "Находит и выполняет SQL-скрипты пакетов, которые ещё не были установлены.",
		params: [],
		destructive: true
	},
	{
		op: "InstallRequiredData",
		category: "Установка и обновление пакетов",
		caption: "Доустановить неустановленные данные пакетов",
		description: "Находит и устанавливает данные пакетов (записи объектов), которые ещё не были установлены.",
		params: [],
		destructive: true
	},
	{
		op: "UpdateRequiredSchemasDBStructure",
		category: "Установка и обновление пакетов",
		caption: "Обновить структуру БД для устаревших таблиц схем",
		description: "Находит объекты, чья структура в БД отстала от схемы, и обновляет их.",
		params: [],
		destructive: true
	},
	{
		op: "InstallPackageData",
		category: "Установка и обновление пакетов",
		caption: "Установить данные конкретного пакета",
		description: "Точечно устанавливает данные одного пакета (опционально — только перечисленные элементы данных).",
		params: [
			packageName("Имя пакета, чьи данные ставим."),
			P("packageData", "Элементы данных (packageData)", "text", { hint: "Список через запятую — если пусто, ставятся все данные пакета." }),
			...installOptionParams().filter((p) => p.flag !== "packageName")
		],
		destructive: true
	},
	{
		op: "ConcatRepositories",
		category: "Установка и обновление пакетов",
		caption: "Слить несколько ZIP-архивов пакетов в один",
		description: "Компонует несколько исходных путей (архивов/папок) в один результирующий ZIP.",
		params: [
			P("sourcePath", "Источники (sourcePath)", "text", { required: true, hint: "Несколько путей через запятую." }),
			destinationPath()
		]
	},
	{
		op: "CompressPackages",
		category: "Установка и обновление пакетов",
		caption: "Сжать пакеты файловой системы в архив",
		description: "Берёт пакеты из рабочей копии (\\SvnPackages) и сохраняет их одним ZIP-архивом.",
		params: [sourcePath(), destinationPath()]
	},
	{
		op: "DownloadPackages",
		category: "Установка и обновление пакетов",
		caption: "Скачать все пакеты из БД в файловую систему",
		description: "Выгружает все пакеты текущей БД по указанному пути (IDownloadPackagesOperation).",
		params: [destinationPath(), P("excludedPackageName", "Исключить пакеты (excludedPackageName)", "text", { hint: "Через запятую." })]
	},

	// --- Приложения (маркетплейс) -----------------------------------------
	{
		op: "InstallApp",
		category: "Приложения",
		caption: "Установить приложение из ZIP",
		description: "Устанавливает маркетплейс-приложение (.zip) — код приложения берётся из имени файла архива.",
		params: [sourcePath(), destinationPath()],
		destructive: true
	},
	{
		op: "UninstallApp",
		category: "Приложения",
		caption: "Удалить установленное приложение",
		description: "Удаляет приложение по коду (appCode) — необратимо удаляет его пакеты из рабочего пространства.",
		params: [P("appCode", "Код приложения (appCode)", "text", { required: true })],
		destructive: true
	},
	{
		op: "ExportApp",
		category: "Приложения",
		caption: "Экспортировать приложение в ZIP",
		description: "Сохраняет приложение по коду (appCode) в ZIP-архив по указанному пути.",
		params: [P("appCode", "Код приложения (appCode)", "text", { required: true }), destinationPath()]
	},

	// --- Рабочие пространства и первичная инициализация БД -----------------
	{
		op: "CreateWorkspace",
		category: "Рабочие пространства",
		caption: "Создать рабочее пространство",
		description: "Создаёт новое рабочее пространство с именем workspaceName (из общих параметров).",
		params: []
	},
	{
		op: "CreateSystemDBStructure",
		category: "Рабочие пространства",
		caption: "Создать структуру системных таблиц в пустой БД",
		description: "Первичная инициализация — создаёт структуру системных объектов. Только для абсолютно новой, пустой БД.",
		params: [],
		destructive: true
	},
	{
		op: "InstallSystemPackage",
		category: "Рабочие пространства",
		caption: "Установить системный пакет (первичная инициализация)",
		description: "Устанавливает системный(е) пакет(ы) из рабочей копии — шаг первичного разворачивания платформы в новую БД.",
		params: [
			P("workingCopyPath", "Путь к рабочей копии (workingCopyPath)", "path", { required: true }),
			packageName("Обязателен — одно имя или несколько через запятую."),
			P("culturename", "Культура (culturename)", "text")
		],
		destructive: true
	},
	{
		op: "InstallCoreSystemSettings",
		category: "Рабочие пространства",
		caption: "Установить базовые системные настройки",
		description: "Заполняет базовые SysSettings платформы для указанной культуры.",
		params: [P("culturename", "Культура (culturename)", "text")],
		destructive: true
	},
	{
		op: "CreateCustomPackage",
		category: "Рабочие пространства",
		caption: "Создать пакет Custom (если отсутствует)",
		description: "Гарантирует наличие пакета Custom в рабочем пространстве.",
		params: [P("updatePackageHierarchy", "Обновить иерархию пакетов (updatePackageHierarchy)", "bool")]
	},
	{
		op: "CreateCurrentPackage",
		category: "Рабочие пространства",
		caption: "Пометить/создать «текущий» пакет",
		description: "Гарантирует наличие «текущего» пакета для дальнейшей разработки.",
		params: []
	},
	{
		op: "ClearAllWorkspaces",
		category: "Рабочие пространства",
		caption: "Очистить ВСЕ рабочие пространства",
		description: "Удаляет содержимое (пакеты, схемы, сборку) каждого рабочего пространства в БД, кроме перечисленных в исключениях.",
		params: [P("excludedWorkspaceNames", "Не трогать (excludedWorkspaceNames)", "text", { hint: "Имена через запятую." })],
		destructive: true
	},
	{
		op: "DeleteWorkspaces",
		category: "Рабочие пространства",
		caption: "Удалить рабочие пространства",
		description: "Полностью удаляет перечисленные рабочие пространства (сперва очищает содержимое, затем удаляет запись SysWorkspace). ⚠ Поле «Рабочее пространство» выше (общий параметр workspaceName) здесь трактуется как список имён через запятую — удаляются все они, а не одно.",
		params: [],
		destructive: true
	},
	{
		op: "DeleteUnusedWorkspaces",
		category: "Рабочие пространства",
		caption: "Удалить неиспользуемые рабочие пространства",
		description: "Удаляет рабочие пространства, в которых ни одна схема не менялась дольше указанного числа дней.",
		params: [P("workspaceUnusedDayCount", "Дней без изменений (workspaceUnusedDayCount)", "int", { required: true })],
		destructive: true
	},

	// --- Схемы и метаданные --------------------------------------------
	{
		op: "SaveEntitySchemasStructureInDB",
		category: "Схемы и метаданные",
		caption: "Сохранить структуру объектов в БД",
		description: "Применяет структуру объектов текущего рабочего пространства к таблицам БД (аналог «Обновить структуру БД» в Configuration).",
		params: [packageName("Необязательный фильтр по пакету."), P("skipConstraints", "Пропустить ограничения БД (skipConstraints)", "bool")],
		destructive: true
	},
	{
		op: "SaveSystemEntitySchemasStructureInDB",
		category: "Схемы и метаданные",
		caption: "Сохранить структуру системных объектов в БД",
		description: "То же самое, но только для системных объектов платформы.",
		params: [P("skipConstraints", "Пропустить ограничения БД (skipConstraints)", "bool")],
		destructive: true
	},
	{
		op: "SaveEntitySchemaReferences",
		category: "Схемы и метаданные",
		caption: "Сохранить связи схем объектов",
		description: "Пересчитывает и сохраняет связи (foreign keys/lookup-зависимости) между схемами объектов.",
		params: [
			P("includedSchemas", "Только схемы (includedSchemas)", "text", { hint: "Через запятую." }),
			P("excludedSchemas", "Кроме схем (excludedSchemas)", "text", { hint: "Через запятую." })
		]
	},
	{
		op: "ExtractMetadata",
		category: "Схемы и метаданные",
		caption: "Извлечь метаданные схем из БД",
		description: "Для ClientUnitSchema/SourceCodeSchema извлекает тело/less из MetaData в отдельную таблицу SysSchemaContent.",
		params: [P("warningsOnly", "Только проверка, без изменений (warningsOnly)", "bool")]
	},
	{
		op: "CreateLocalizationSchemasInDBStructure",
		category: "Схемы и метаданные",
		caption: "Создать структуру БД для схем локализации",
		description: "Создаёт таблицы БД для схем локализации, если их ещё нет.",
		params: [],
		destructive: true
	},
	{
		op: "ReloadSchemaLocalizableCaptions",
		category: "Схемы и метаданные",
		caption: "Перезагрузить локализуемые заголовки схем",
		description: "Пересобирает локализуемые заголовки (Caption) схем и их колонок из ресурсов.",
		params: [],
		destructive: true
	},
	{
		op: "ActualizeSchemaCaptions",
		category: "Схемы и метаданные",
		caption: "Актуализировать заголовки схем",
		description: "Обновляет Caption схем текущего пространства значениями из их же ресурсов.",
		params: [],
		destructive: true
	},
	{
		op: "GeneratePackageResourceChecksums",
		category: "Схемы и метаданные",
		caption: "Заполнить контрольные суммы ресурсов",
		description: "Генерирует контрольные суммы для уже существующих ресурсов пакетов.",
		params: []
	},
	{
		op: "DisableTrackChanges",
		category: "Схемы и метаданные",
		caption: "Отключить отслеживание изменений (IsTrackChangesInDB)",
		description: "Массово выключает флаг IsTrackChangesInDB у всех объектов, где он включён.",
		params: [],
		destructive: true
	},
	{
		op: "InitializeSysSchemaContent",
		category: "Схемы и метаданные",
		caption: "Инициализировать содержимое схем (SysSchemaContent)",
		description: "Заполняет таблицу SysSchemaContent из исходников рабочей копии для указанных рабочих пространств.",
		params: [P("workingCopyPath", "Путь к рабочей копии (workingCopyPath)", "path", { required: true })],
		destructive: true
	},

	// --- Данные и контент -------------------------------------------------
	{
		op: "SaveDBContent",
		category: "Данные и контент",
		caption: "Сохранить контент из БД в файлы",
		description: "Сохраняет содержимое БД (системные/конфигурационные данные, локализуемые данные, ресурсы, сам репозиторий) в файлы — набор типов задаётся contentTypes.",
		params: [
			destinationPath(),
			P("contentTypes", "Типы контента (contentTypes)", "text", { hint: "SystemData, ConfigurationData, LocalizableData, LocalizableSchemaData, Resources, Repository — через запятую; пусто = All." })
		]
	},
	{
		op: "SaveRepositoryContent",
		category: "Данные и контент",
		caption: "Сохранить SQL-скрипты хранилища в файлы",
		description: "Из перечисленных типов контента реально что-то делает только для SqlScripts — сохраняет .sql файлы пакетов хранилища на диск.",
		params: [
			sourcePath(),
			destinationPath(),
			P("contentTypes", "Типы контента (contentTypes)", "text", { required: true, hint: "Должно включать SqlScripts, иначе операция ничего не сделает." })
		]
	},
	{
		op: "LoadWorkspaceContent",
		category: "Данные и контент",
		caption: "Загрузить контент в рабочее пространство из файлов",
		description: "Обратная операция к SaveDBContent — загружает данные/ресурсы/репозиторий из файлов в текущее рабочее пространство.",
		params: [
			sourcePath(),
			destinationPath(),
			P("contentTypes", "Типы контента (contentTypes)", "text", { hint: "SystemData, ConfigurationData, LocalizableData, LocalizableSchemaData, Resources, Repository — через запятую." })
		],
		destructive: true
	},
	{
		op: "ValidateContent",
		category: "Данные и контент",
		caption: "Проверить контент (ресурсы/локализуемые данные)",
		description: "Валидация ресурсов или локализуемых данных конфигурации без установки — результат складывается в destinationPath.",
		params: [
			destinationPath(),
			P("culturename", "Культура (culturename)", "text", { required: true }),
			P("fileName", "Имя файла результата (fileName)", "text", { required: true }),
			P("contentTypes", "Типы контента (contentTypes)", "text", { hint: "Resources, LocalizableData или LocalizableSchemaData." })
		]
	},
	{
		op: "ValidateResourcesByResourceManagers",
		category: "Данные и контент",
		caption: "Проверить ресурсы по менеджерам ресурсов",
		description: "Проверяет ресурсы всех менеджеров ресурсов на предмет непереведённых/отсутствующих значений.",
		params: [
			P("culturename", "Культура (culturename)", "text"),
			destinationPath(),
			P("localizedConfigFileName", "Файл настроек проверки (localizedConfigFileName)", "path")
		]
	},

	// --- Системные настройки и лицензии -----------------------------------
	{
		op: "SetSysSetting",
		category: "Системные настройки и лицензии",
		caption: "Установить значение системной настройки",
		description: "Устанавливает значение SysSettings по коду — точечная правка одной настройки без захода в UI.",
		params: [
			P("sysSettingCode", "Код настройки (sysSettingCode)", "text", { required: true }),
			P("sysSettingValue", "Значение (sysSettingValue)", "text", { required: true })
		],
		destructive: true
	},
	{
		op: "SaveLicenseRequest",
		category: "Системные настройки и лицензии",
		caption: "Сохранить файл запроса лицензии",
		description: "Формирует файл запроса лицензии для клиента (по customerId).",
		params: [
			destinationPath(),
			P("customerId", "Идентификатор клиента (customerId)", "text", { required: true }),
			P("fileName", "Имя файла (fileName)", "text", { hint: "По умолчанию LicenseRequest.<расширение>." })
		]
	},
	{
		op: "LoadLicResponse",
		category: "Системные настройки и лицензии",
		caption: "Загрузить лицензионный ответ",
		description: "Загружает файл лицензионного ответа (sourcePath + fileName) в приложение.",
		params: [sourcePath(), P("fileName", "Имя файла (fileName)", "text", { required: true })],
		destructive: true
	},
	{
		op: "ActualizeSysAdminUnitInRole",
		category: "Системные настройки и лицензии",
		caption: "Актуализировать пользователей в ролях",
		description: "Пересчитывает членство пользователей в организационных ролях. Требует включённой системной настройки UseOrgStructureManagerForActualizeUsersRoles — иначе тихо ничего не делает.",
		params: [continueIfError()],
		destructive: true
	},

	// --- Скрипты и процессы -------------------------------------------
	{
		op: "ExecuteProcess",
		category: "Скрипты и процессы",
		caption: "Выполнить бизнес-процесс по имени",
		description: "Находит бизнес-процесс по имени схемы и запускает его синхронно.",
		params: [
			P("processName", "Имя схемы процесса (processName)", "text", { required: true }),
			P("excludedSchemas", "ExcludedSchemas в процесс (excludedSchemas)", "text", { hint: "Передаётся в параметр процесса ExcludedSchemas, если он есть." })
		],
		destructive: true
	},
	{
		op: "ExecuteScript",
		category: "Скрипты и процессы",
		caption: "Выполнить произвольный C#-скрипт",
		description: "⚠ Загружает указанную сборку и выполняет метод Execute() указанного типа (реализующего IExecutor) с правами приложения — фактически произвольный код.",
		params: [
			P("fileName", "Путь к сборке .dll (fileName)", "path", { required: true }),
			P("typeName", "Полное имя типа (typeName)", "text", { required: true, hint: "Тип должен реализовывать IExecutor." })
		],
		destructive: true
	},

	// --- Безопасность -------------------------------------------------
	{
		op: "EncryptPasswords",
		category: "Безопасность",
		caption: "Перешифровать хэши паролей",
		description: "⚠ Массово перешифровывает хранимые хэши паролей пользователей.",
		params: [],
		destructive: true
	},
	{
		op: "ReEncryptSecurityTextStaticWithNewParam",
		category: "Безопасность",
		caption: "Перешифровать защищённый текст (статический вектор)",
		description: "⚠ Перешифровывает данные, защищённые статическим вектором/ключом, на новую пару значений. Только если системная настройка EnableDynamicVector выключена.",
		params: [
			P("configurationFilePath", "Путь к .config для правки (configurationFilePath)", "path"),
			P("initializationVector", "Текущий вектор (initializationVector)", "password"),
			P("securityKey", "Текущий ключ (securityKey)", "password"),
			P("newInitializationVector", "Новый вектор (newInitializationVector)", "password"),
			P("newSecurityKey", "Новый ключ (newSecurityKey)", "password"),
			continueIfError()
		],
		destructive: true
	},
	{
		op: "ReEncryptSecurityTextDynamicWithNewKey",
		category: "Безопасность",
		caption: "Перешифровать защищённый текст (динамический вектор)",
		description: "⚠ Перешифровывает данные, защищённые динамическим вектором, новым ключом. Только если EnableDynamicVector включена.",
		params: [
			P("configurationFilePath", "Путь к .config для правки (configurationFilePath)", "path"),
			P("securityKey", "Текущий ключ (securityKey)", "password"),
			P("newSecurityKey", "Новый ключ (newSecurityKey)", "password"),
			continueIfError()
		],
		destructive: true
	},
	{
		op: "MigrateFromStaticToDynamicEncryptSecurityText",
		category: "Безопасность",
		caption: "Мигрировать со статического на динамический вектор",
		description: "⚠ Однократная миграция шифрования защищённого текста со старой (статической) схемы на новую (динамическую).",
		params: [P("configurationFilePath", "Путь к .config (configurationFilePath)", "path"), continueIfError()],
		destructive: true
	},

	// --- Утилиты файлов ------------------------------------------------
	{
		op: "ZipDirectory",
		category: "Утилиты файлов",
		caption: "Заархивировать директорию",
		description: "Просто архивирует указанный путь в ZIP — не обращается к БД.",
		params: [sourcePath()]
	},
	{
		op: "UnzipDirectory",
		category: "Утилиты файлов",
		caption: "Разархивировать директорию",
		description: "Просто разархивирует указанный ZIP — не обращается к БД.",
		params: [sourcePath()]
	},
	{
		op: "RemoveConfigurationComments",
		category: "Утилиты файлов",
		caption: "Удалить комментарии из исходников",
		description: "⚠ Необратимо переписывает .sql/.cs/.js файлы рабочей копии, вырезая из них комментарии.",
		params: [P("workingCopyPath", "Путь к рабочей копии (workingCopyPath)", "path", { required: true })],
		destructive: true
	}
];

/** Operations where `confRuntimeParentDirectory` is enforced by
 * `WorkspaceConsoleCommandLine.Validate()` before the operation runs at all —
 * exact list from `CommandsWithRequiredConfRuntimeParentDirectoryParameter`.
 * Includes 3 operations not present in `WORKSPACE_CONSOLE_OPERATIONS` (dead
 * in this build, see file doc) — harmless to list them here too. */
export const CONF_RUNTIME_PARENT_DIRECTORY_REQUIRED = new Set<string>([
	"ExecuteProcess",
	"RegenerateSchemaSources",
	"InstallFromRepository",
	"InstallBundlePackages",
	"InstallTestPackages",
	"InstallUnitTestPackages",
	"InstallTestPackagesBySuffix",
	"UpdatePackages",
	"BuildWorkspace",
	"RebuildWorkspace",
	"RebuildAngularModules",
	"BuildAngularModules",
	"GenerateRequiredSourceCode",
	"InstallPackagesFromWorkingCopy",
	"InstallZipPackage",
	"InstallApp",
	"UninstallApp",
	"InstallSystemPackage",
	"PublishAngularComponentsInPackages"
]);

function formatFlag(flag: string, value: string): string {
	return `-${flag}="${value.replace(/"/g, '\\"')}"`;
}

/**
 * Builds the exact `dotnet <dll> -operation=... -flag="value" ...` command
 * line for one operation. Booleans are always emitted as `-flag=true`/`=false`
 * (never a bare flag) — `GetParameterValue(name, bool defValue)` treats a
 * present-but-empty value as "absent" (see file doc), so a bare `-autoExit`
 * with no `=value` would silently behave as `false`.
 */
export function buildWorkspaceConsoleCommand(
	dllPath: string,
	op: WCOperation,
	baseValues: Record<string, string | boolean>,
	opValues: Record<string, string | boolean>,
	extraArgs: string
): string {
	const parts: string[] = [`dotnet "${dllPath}"`, `-operation=${op.op}`];
	const emit = (param: WCParam, raw: string | boolean | undefined) => {
		if (raw === undefined || raw === "") {
			return;
		}
		if (param.kind === "bool") {
			parts.push(`-${param.flag}=${raw ? "true" : "false"}`);
			return;
		}
		parts.push(formatFlag(param.flag, String(raw)));
	};
	for (const param of WORKSPACE_CONSOLE_BASE_PARAMS) {
		emit(param, baseValues[param.flag]);
	}
	for (const param of op.params) {
		emit(param, opValues[param.flag]);
	}
	const trimmedExtra = extraArgs.trim();
	if (trimmedExtra) {
		parts.push(trimmedExtra);
	}
	return parts.join(" ");
}
