import * as fs from "fs";
import * as path from "path";
import * as acorn from "acorn";
import * as walk from "acorn-walk";
import { IndexedSchemaMessage, SchemaMessageDirection } from "../index/types";
import { resolveAppLayouts } from "../index/workspaceLayout";

type AnyNode = acorn.Node & Record<string, any>;
type CoreAction = "publish" | "subscribe";

const FALLBACK: Array<{ name: string; coreAction: CoreAction }> = [
	{ name: "GetHistoryState", coreAction: "subscribe" },
	{ name: "PushHistoryState", coreAction: "subscribe" },
	{ name: "ReplaceHistoryState", coreAction: "subscribe" },
	{ name: "BackHistoryState", coreAction: "subscribe" },
	{ name: "ForwardHistoryState", coreAction: "subscribe" },
	{ name: "NavigationModuleLoaded", coreAction: "publish" },
	{ name: "HistoryStateChanged", coreAction: "publish" },
	{ name: "BeforeHistoryChanging", coreAction: "publish" },
	{ name: "RefreshCacheHash", coreAction: "publish" }
];

/**
 * Core sandbox messages from NavigationModule.
 * Direction is already mapped to the schema side
 * (core subscribe → schema publish, and the reverse).
 */
export function buildNavigationMessages(
	workspaceRoots: string[]
): IndexedSchemaMessage[] {
	const byKey = new Map<string, IndexedSchemaMessage>();
	for (const filePath of findNavigationModuleFiles(workspaceRoots)) {
		for (const msg of extractNavigationMessages(filePath)) {
			const key = `${msg.direction}:${msg.name}`;
			if (!byKey.has(key)) {
				byKey.set(key, msg);
			}
		}
	}
	if (byKey.size) {
		return Array.from(byKey.values());
	}
	return FALLBACK.map((item) => toSchemaMessage(item.name, item.coreAction));
}

function toSchemaMessage(
	name: string,
	coreAction: CoreAction,
	filePath?: string,
	position?: IndexedSchemaMessage["position"],
	documentation?: string
): IndexedSchemaMessage {
	const direction: SchemaMessageDirection =
		coreAction === "subscribe" ? "publish" : "subscribe";
	return {
		name,
		direction,
		filePath: filePath || undefined,
		position,
		documentation: documentation || `NavigationModule · ${coreAction}`
	};
}

function findNavigationModuleFiles(roots: string[]): string[] {
	const seen = new Set<string>();
	const add = (filePath: string) => {
		const key = path.normalize(filePath);
		if (fs.existsSync(key)) {
			seen.add(key);
		}
	};
	const layouts = resolveAppLayouts(roots);
	for (const layout of layouts) {
		if (layout.autogeneratedRoot) {
			add(path.join(layout.autogeneratedRoot, "Src", "NavigationModule.NUI.js"));
		}
		if (layout.configurationRoot) {
			add(
				path.join(
					layout.configurationRoot,
					"Autogenerated/Src/NavigationModule.NUI.js"
				)
			);
		}
	}
	if (!seen.size) {
		for (const layout of layouts) {
			if (layout.confContent) {
				add(path.join(layout.confContent, "NavigationModule.js"));
			}
		}
	}
	if (!seen.size) {
		for (const root of roots) {
			add(
				path.join(
					root,
					"BPMSoft.Configuration/Autogenerated/Src/NavigationModule.NUI.js"
				)
			);
			if (!seen.size) {
				add(path.join(root, "conf/content/NavigationModule.js"));
			}
		}
	}
	return Array.from(seen);
}

function extractNavigationMessages(filePath: string): IndexedSchemaMessage[] {
	let ast: AnyNode;
	const comments: acorn.Comment[] = [];
	try {
		const source = fs.readFileSync(filePath, "utf8").replace(/^\uFEFF/, "");
		ast = acorn.parse(source, {
			ecmaVersion: "latest",
			sourceType: "script",
			allowReturnOutsideFunction: true,
			locations: true,
			onComment: comments
		}) as AnyNode;
	} catch {
		return [];
	}
	const out: IndexedSchemaMessage[] = [];
	walk.simple(ast, {
		CallExpression(node: AnyNode) {
			const action = sandboxPublishOrSubscribe(node);
			if (!action) {
				return;
			}
			const arg0 = (node.arguments as AnyNode[])?.[0];
			if (!arg0 || arg0.type !== "Literal" || typeof arg0.value !== "string") {
				return;
			}
			const name = arg0.value;
			if (!name) {
				return;
			}
			const loc = arg0.loc?.start;
			out.push(
				toSchemaMessage(
					name,
					action,
					filePath,
					loc ? { line: loc.line - 1, character: loc.column } : undefined,
					leadingComment(comments, node)
				)
			);
		}
	} as any);
	return out;
}

function sandboxPublishOrSubscribe(node: AnyNode): CoreAction | undefined {
	const callee = node.callee as AnyNode;
	if (!callee || callee.type !== "MemberExpression" || callee.computed) {
		return undefined;
	}
	const prop = callee.property as AnyNode;
	if (prop?.type !== "Identifier") {
		return undefined;
	}
	if (prop.name !== "publish" && prop.name !== "subscribe") {
		return undefined;
	}
	if (!isSandboxObject(callee.object as AnyNode)) {
		return undefined;
	}
	return prop.name;
}

function isSandboxObject(node: AnyNode | undefined): boolean {
	if (!node) {
		return false;
	}
	if (node.type === "Identifier") {
		return node.name === "sandbox";
	}
	if (node.type !== "MemberExpression" || node.computed) {
		return false;
	}
	const obj = node.object as AnyNode;
	const prop = node.property as AnyNode;
	return (
		obj?.type === "ThisExpression" &&
		prop?.type === "Identifier" &&
		prop.name === "sandbox"
	);
}

function leadingComment(
	comments: acorn.Comment[],
	node: AnyNode
): string | undefined {
	if (typeof node.start !== "number") {
		return undefined;
	}
	let best: acorn.Comment | undefined;
	for (const comment of comments) {
		if (comment.end <= node.start && node.start - comment.end < 80) {
			if (!best || comment.end > best.end) {
				best = comment;
			}
		}
	}
	if (!best) {
		return undefined;
	}
	return best.value
		.replace(/^\*+/, "")
		.replace(/\n\s*\*/g, "\n")
		.trim();
}
