import * as vscode from "vscode";

export function formattingEnabled(): boolean {
	return vscode.workspace
		.getConfiguration("bpmsoft")
		.get<boolean>("formatting.enabled", true);
}

export function isJsFormatTarget(filePath: string): boolean {
	const normalized = filePath.replace(/\\/g, "/");
	if (normalized.includes("/node_modules/")) {
		return false;
	}
	return !(
		normalized.includes("/Autogenerated/") ||
		normalized.includes("/Resources/ui/") ||
		normalized.includes("/conf/content/") ||
		// Pkg/{Package}/Files/** holds static/vendor assets (minified
		// third-party bundles included) rather than BPMSoft AMD schemas —
		// running our schema-oriented formatter on them is wrong scope, not
		// just noisy (a multi-hundred-KB minified file reformatted by
		// Prettier is actively harmful, not merely unhelpful).
		/\/Pkg\/[^/]+\/Files\//.test(normalized)
	);
}

export function isCsharpFormatTarget(filePath: string): boolean {
	const normalized = filePath.replace(/\\/g, "/");
	return !normalized.includes("/node_modules/") && !/\/obj\//i.test(normalized);
}

export function isSqlScriptFormatTarget(filePath: string): boolean {
	const normalized = filePath.replace(/\\/g, "/");
	return /\/Pkg\/[^/]+\/SqlScripts\/[^/]+\/[^/]+\.sql$/i.test(normalized);
}
