import * as vscode from "vscode";
import { IndexingProgressReporter } from "../index/indexingProgress";

/**
 * Persistent bottom-of-window indicator for the two startup scans
 * (`ModuleIndexer.rebuild` / `NamingIssuesIndex.refresh`) — unlike the
 * transient `vscode.window.withProgress`/`setStatusBarMessage` calls already
 * in `extension.ts` (a notification that's easy to miss, and a status-bar
 * message that self-clears after a few seconds), this stays visible for the
 * whole run and keeps a live "N/total" count. On a workspace big enough to
 * hit the cold-file-cache latency documented in `concurrency.ts`, that scan
 * can take anywhere from a couple of seconds to a couple of minutes — this
 * is what turns that wait from "the whole sidebar looks frozen" into
 * "visibly working, this many schemas so far."
 */
export class IndexingStatusBar implements vscode.Disposable, IndexingProgressReporter {
	private readonly item: vscode.StatusBarItem;

	private modulesRunning = false;
	private moduleDone = 0;
	private moduleTotal = 0;
	private lastModuleCount: number | undefined;
	private lastModuleDurationMs: number | undefined;

	private namingRunning = false;
	private namingDone = 0;
	private namingTotal = 0;
	private lastNamingFindingCount: number | undefined;
	private lastNamingDurationMs: number | undefined;

	constructor() {
		this.item = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 101);
		this.item.name = "BPMSoft Indexing";
		this.item.command = "bpmsoft.rebuildIndex";
		this.render();
		this.item.show();
	}

	dispose(): void {
		this.item.dispose();
	}

	startModules(total: number): void {
		this.modulesRunning = true;
		this.moduleTotal = total;
		this.moduleDone = 0;
		this.render();
	}

	reportModuleProgress(done: number, total: number): void {
		this.moduleDone = done;
		this.moduleTotal = total;
		this.render();
	}

	finishModules(count: number, durationMs: number): void {
		this.modulesRunning = false;
		this.lastModuleCount = count;
		this.lastModuleDurationMs = durationMs;
		this.render();
	}

	startNaming(total: number): void {
		this.namingRunning = true;
		this.namingTotal = total;
		this.namingDone = 0;
		this.render();
	}

	reportNamingProgress(done: number, total: number): void {
		this.namingDone = done;
		this.namingTotal = total;
		this.render();
	}

	finishNaming(findingCount: number, durationMs: number): void {
		this.namingRunning = false;
		this.lastNamingFindingCount = findingCount;
		this.lastNamingDurationMs = durationMs;
		this.render();
	}

	private render(): void {
		if (this.modulesRunning || this.namingRunning) {
			const parts: string[] = [];
			if (this.modulesRunning) {
				parts.push(this.moduleTotal ? `схемы ${this.moduleDone}/${this.moduleTotal}` : "схемы…");
			}
			if (this.namingRunning) {
				parts.push(this.namingTotal ? `нейминг ${this.namingDone}/${this.namingTotal}` : "нейминг…");
			}
			this.item.text = `$(sync~spin) BPMSoft: ${parts.join(", ")}`;
			this.item.tooltip = "BPMSoft: идёт индексация Pkg + Autogenerated + UI. Клик — перезапустить индексацию.";
			this.item.show();
			return;
		}

		const bits: string[] = [];
		if (this.lastModuleCount !== undefined) {
			bits.push(`${this.lastModuleCount} ${pluralRu(this.lastModuleCount, "схема", "схемы", "схем")}`);
		}
		if (this.lastNamingFindingCount !== undefined) {
			bits.push(
				`${this.lastNamingFindingCount} ${pluralRu(this.lastNamingFindingCount, "находка", "находки", "находок")} нейминга`
			);
		}
		this.item.text = `$(check) BPMSoft${bits.length ? ": " + bits.join(", ") : ""}`;

		const tooltipLines = ["**BPMSoft**"];
		if (this.lastModuleCount !== undefined) {
			tooltipLines.push(
				`- Проиндексировано схем: ${this.lastModuleCount}` +
					(this.lastModuleDurationMs !== undefined ? ` (${formatDuration(this.lastModuleDurationMs)})` : "")
			);
		}
		if (this.lastNamingFindingCount !== undefined) {
			tooltipLines.push(
				`- Находок нейминга: ${this.lastNamingFindingCount}` +
					(this.lastNamingDurationMs !== undefined ? ` (${formatDuration(this.lastNamingDurationMs)})` : "")
			);
		}
		tooltipLines.push("", "Клик — перестроить индекс.");
		this.item.tooltip = new vscode.MarkdownString(tooltipLines.join("\n"));
		this.item.show();
	}
}

function formatDuration(ms: number): string {
	if (ms < 1000) {
		return `${ms} мс`;
	}
	return `${(ms / 1000).toFixed(1)} с`;
}

/** Russian plural form for `count` — schema/finding counts are shown raw
 * (not run through `Resources.Strings`-style pluralization anywhere else in
 * this extension), so this is a small local rule rather than a shared
 * utility: last digit 1 (not 11) → `one`, last digit 2-4 (not 12-14) →
 * `few`, everything else → `many`. */
function pluralRu(count: number, one: string, few: string, many: string): string {
	const mod100 = count % 100;
	const mod10 = count % 10;
	if (mod10 === 1 && mod100 !== 11) {
		return one;
	}
	if (mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14)) {
		return few;
	}
	return many;
}
