import * as vscode from "vscode";
import { collectStyleIssues, StyleIssue } from "../parse/styleAnalyzer";
import { SymbolIndex } from "../index/SymbolIndex";
import { DIAG_SOURCE } from "./MissingMemberDiagnostics";
import { clearDebounceTimers, debounceDocument, isJsFile } from "./jsDocuments";

const CODE_BY_KIND: Record<StyleIssue["kind"], string> = {
	krBrace: "bpmsoft.style.krBrace",
	krCuddle: "bpmsoft.style.krCuddle",
	varDecl: "bpmsoft.style.var",
	constAssign: "bpmsoft.style.constAssign",
	ifElseChain: "bpmsoft.style.ifElseChain",
	eqeqeq: "bpmsoft.style.eqeqeq",
	unusedVar: "bpmsoft.style.unusedVar",
	unusedParam: "bpmsoft.style.unusedParam",
	unreachable: "bpmsoft.style.unreachable",
	switchFallthrough: "bpmsoft.style.switchFallthrough",
	switchDuplicateCase: "bpmsoft.style.switchDuplicateCase",
	curly: "bpmsoft.style.curly",
	debuggerStmt: "bpmsoft.style.debugger",
	consoleCall: "bpmsoft.style.console",
	nanCompare: "bpmsoft.style.nanCompare",
	duplicateKey: "bpmsoft.style.duplicateKey",
	unusedMethod: "bpmsoft.style.unusedMethod",
	unusedAttribute: "bpmsoft.style.unusedAttribute",
	unusedMessage: "bpmsoft.style.unusedMessage"
};

export class StyleDiagnostics implements vscode.Disposable {
	private readonly collection: vscode.DiagnosticCollection;
	private readonly timers = new Map<string, ReturnType<typeof setTimeout>>();

	constructor(private readonly index: SymbolIndex) {
		this.collection = vscode.languages.createDiagnosticCollection("bpmsoft-style");
	}

	dispose(): void {
		clearDebounceTimers(this.timers);
		this.collection.dispose();
	}

	schedule(document: vscode.TextDocument): void {
		debounceDocument(this.timers, document, (doc) => this.refresh(doc));
	}

	refresh(document: vscode.TextDocument): void {
		if (!isJsFile(document)) {
			return;
		}
		if (!styleEnabled() || !isStyleTarget(document.uri.fsPath)) {
			this.collection.delete(document.uri);
			return;
		}
		const inherited = this.index.resolveInheritedSchemaNames(document.uri.fsPath);
		const diags = collectStyleIssues(document.getText(), inherited).map((issue) =>
			toDiagnostic(document, issue)
		);
		this.collection.set(document.uri, diags);
	}

	refreshOpenDocuments(): void {
		for (const document of vscode.workspace.textDocuments) {
			this.refresh(document);
		}
	}

	clear(uri: vscode.Uri): void {
		this.collection.delete(uri);
	}
}

function toDiagnostic(
	document: vscode.TextDocument,
	issue: StyleIssue
): vscode.Diagnostic {
	const severity =
		issue.severity === "error"
			? vscode.DiagnosticSeverity.Error
			: vscode.DiagnosticSeverity.Warning;
	const diag = new vscode.Diagnostic(
		new vscode.Range(
			document.positionAt(issue.start),
			document.positionAt(issue.end)
		),
		issue.message,
		severity
	);
	diag.source = DIAG_SOURCE;
	diag.code = CODE_BY_KIND[issue.kind];
	return diag;
}

function styleEnabled(): boolean {
	return vscode.workspace
		.getConfiguration("bpmsoft")
		.get<boolean>("styleDiagnostics", true);
}

function isStyleTarget(filePath: string): boolean {
	const normalized = filePath.replace(/\\/g, "/");
	return !(
		normalized.includes("/node_modules/") ||
		normalized.includes("/Autogenerated/") ||
		normalized.includes("/Resources/ui/") ||
		normalized.includes("/conf/content/")
	);
}
