import * as path from "path";
import * as vscode from "vscode";
import {
	BpmsoftAppLayout,
	DevDotnetProject,
	devDotnetLoadFile,
	findDevDotnetProjects,
	pathRelativePosix
} from "../index/workspaceLayout";
import { ensureDevDotnetSln } from "./devSln";

/** C# language extension; it depends on .NET Install Tool. */
const CSHARP_EXTENSION_ID = "ms-dotnettools.csharp";

/**
 * Point the C# language service at BPMSoft.Configuration.Dev.sln.
 * Does not wait for the C# extension and does not block JS indexing.
 */
export async function ensureDotnetSolution(
	layouts: BpmsoftAppLayout[]
): Promise<void> {
	const project = findDevDotnetProjects(layouts)[0];
	if (!project) {
		return;
	}
	try {
		ensureDevDotnetSln(project);
	} catch {
		void vscode.window.showWarningMessage(
			"Не удалось создать BPMSoft.Configuration.Dev.sln рядом с csproj. Без .sln подсказки C# не работают."
		);
		return;
	}
	await setDefaultSolution(project);
}

/** Prompt to install C# when a .cs file is opened — not during JS index. */
export async function maybeOfferCsharpExtension(
	context: vscode.ExtensionContext
): Promise<void> {
	if (vscode.extensions.getExtension(CSHARP_EXTENSION_ID)) {
		return;
	}
	if (context.workspaceState.get<boolean>("bpmsoft.csharpInstallPrompted")) {
		return;
	}
	const choice = await vscode.window.showInformationMessage(
		"Для подсказок в C# (Pkg и Autogenerated) нужно расширение C#. Вместе с ним установится .NET Install Tool.",
		"Установить",
		"Не сейчас"
	);
	if (choice !== "Установить") {
		await context.workspaceState.update("bpmsoft.csharpInstallPrompted", true);
		return;
	}
	try {
		await vscode.commands.executeCommand(
			"workbench.extensions.installExtension",
			CSHARP_EXTENSION_ID
		);
	} catch {
		void vscode.window.showWarningMessage(
			"Не удалось установить расширение C# (ms-dotnettools.csharp). Установите его вручную."
		);
	}
}

async function setDefaultSolution(project: DevDotnetProject): Promise<void> {
	const target = devDotnetLoadFile(project);
	const relative = workspaceRelativePath(target);
	if (!relative) {
		return;
	}
	try {
		const dotnet = vscode.workspace.getConfiguration("dotnet");
		if (dotnet.get<string>("defaultSolution") !== relative) {
			await dotnet.update(
				"defaultSolution",
				relative,
				vscode.ConfigurationTarget.Workspace
			);
		}
		const omnisharp = vscode.workspace.getConfiguration("omnisharp");
		if (omnisharp.get<string>("defaultLaunchSolution") !== relative) {
			await omnisharp.update(
				"defaultLaunchSolution",
				relative,
				vscode.ConfigurationTarget.Workspace
			);
		}
	} catch {
		// Workspace may be read-only.
	}
}

function workspaceRelativePath(absPath: string): string | undefined {
	const folders = vscode.workspace.workspaceFolders;
	if (!folders?.length) {
		return undefined;
	}
	let best: string | undefined;
	let bestScore = Number.POSITIVE_INFINITY;
	for (const folder of folders) {
		const rel = pathRelativePosix(folder.uri.fsPath, absPath);
		if (!rel || path.isAbsolute(rel)) {
			continue;
		}
		const score = rel.startsWith("..")
			? 1000 + rel.split("/").filter((p) => p === "..").length
			: rel.split("/").length;
		if (score < bestScore) {
			bestScore = score;
			best = rel;
		}
	}
	return best;
}
