import { tokenize } from "./csharpStyleAnalyzer";
import { matchForwardParen, firstDirectLiteralArg } from "./esqCsharp";

/**
 * C#-side `Entity` CRUD column resolution — `entity.SetColumnValue("Col",
 * value)` / `entity.GetTypedColumnValue<T>("Col")` / `entity.GetColumnValue
 * ("Col")` (all real, confirmed against usage: `SetColumnValue` 438,
 * `GetTypedColumnValue<T>` 581, `GetColumnValue` 6 occurrences across one
 * install's own owned packages).
 *
 * Unlike `EntitySchemaQuery`, a plain `Entity` variable carries no static
 * type parameter naming its schema (`Entity` is one concrete class for
 * every schema) — the schema has to come from context. The dominant real
 * pattern (~60 files in one install) is `BaseEntityEventListener` +
 * `[EntityEventListener(SchemaName = "X")]`: inside such a class, the
 * `Entity` the listener's own hooks operate on (`OnSaving`/`OnSaved`/...,
 * typically obtained as `(Entity)sender`) is schema `X`. A real, confirmed
 * exception: `nameof(Schema.Column)` names its own schema right there in
 * the call, which can genuinely differ from the listener's own (a related
 * entity fetched under an unrelated variable name — e.g. a
 * `GoCapexEquipment` listener calling `deal.SetColumnValue(nameof(GoDeal.
 * GoEquipmentCapex), ...)`) — that explicit name wins over the ambient
 * listener context when it resolves to a real schema (see
 * `CsharpHoverProvider.resolveEntityColumnHover`).
 *
 * An `Entity` fetched some other way (a fresh `EntitySchemaManager.
 * CreateNewEntityInternal(...)`, a row pulled from an `EntitySchemaQuery`
 * result, a method parameter with no attribute nearby) isn't traceable this
 * way and gets no hover, same "don't guess" stance as every other
 * cross-reference in this codebase. One more real, *not* chased down here:
 * some `nameof(Schema.Column)` references a column name that doesn't match
 * any real column on that schema at all (e.g. `nameof(Account.CountryId)`
 * where `Account`'s own logical column is actually `Country`) — `Account`
 * there is BPMSoft's own generated per-schema wrapper class, not the schema
 * itself, and its own constant naming convention for lookups doesn't
 * necessarily match the schema's own attribute name 1:1. Untangling that
 * would mean parsing that generated class's own definition (itself several
 * substitution-chain hops deep in `Autogenerated/Src`) — left as a known
 * gap rather than guessed at. Coverage swept across two real installs'
 * owned C# (every file carrying `[EntityEventListener]`): 46.5%/35.3% of
 * real `SetColumnValue`/`GetColumnValue`/`GetTypedColumnValue` call sites
 * resolve, zero crashes.
 */

/** Matches either the plain-string or `nameof(...)` form of the attribute —
 * confirmed real and roughly as common as the string form (44 vs. 47
 * occurrences across one install's own owned packages). Group 1 is the
 * string-literal schema name; group 2 is `nameof(...)`'s own argument
 * (possibly dotted, e.g. `nameof(Account)` — never actually dotted in
 * practice for this specific attribute, but handled the same way as the
 * column-reference case below just in case). */
const ENTITY_EVENT_LISTENER_RE =
	/\[\s*EntityEventListener\s*\(\s*SchemaName\s*=\s*(?:"([^"]+)"|nameof\s*\(\s*([\w.]+)\s*\))/g;

function lastDotSegment(value: string): string {
	const idx = value.lastIndexOf(".");
	return idx < 0 ? value : value.slice(idx + 1);
}

const ENTITY_COLUMN_METHODS = new Set(["SetColumnValue", "GetColumnValue", "GetTypedColumnValue"]);

/** The `SchemaName` of the nearest `[EntityEventListener(SchemaName = "X")]`
 * attribute textually preceding `offset` — attributes directly precede
 * their own class, and classes are sequential, so "nearest preceding
 * occurrence" lands on the enclosing class's own attribute even in a file
 * with several such classes (confirmed real: `SynchronizationEntityEventListener.cs`
 * declares 5). */
export function findEnclosingEntityEventListenerSchema(source: string, offset: number): string | undefined {
	let best: { index: number; schemaName: string } | undefined;
	ENTITY_EVENT_LISTENER_RE.lastIndex = 0;
	let m: RegExpExecArray | null;
	while ((m = ENTITY_EVENT_LISTENER_RE.exec(source))) {
		if (m.index + m[0].length > offset) {
			continue;
		}
		if (!best || m.index > best.index) {
			best = { index: m.index, schemaName: m[1] ?? lastDotSegment(m[2]) };
		}
	}
	return best?.schemaName;
}

export interface EntityColumnContext {
	columnName: string;
	/** Schema named alongside the column in a `nameof(Schema.Column)` call —
	 * see `CsharpLiteralArg.qualifier`. Takes priority over the enclosing
	 * `[EntityEventListener]`'s own SchemaName when present: a real, common
	 * case is a *related* entity reached under some other variable name
	 * (`deal.SetColumnValue(nameof(GoDeal.GoEquipmentCapex), ...)` inside a
	 * differently-schema'd listener), where the listener's own schema would
	 * be the wrong one to resolve against. */
	explicitSchemaName?: string;
	start: number;
	end: number;
}

/** `<entityVar>.SetColumnValue("Col", ...)` / `.GetTypedColumnValue<T>("Col")`
 * / `.GetColumnValue("Col")` at `offset` — `undefined` unless `offset`
 * actually falls on that call's own column-name string literal. */
export function getEntityColumnContext(source: string, offset: number): EntityColumnContext | undefined {
	const { tokens } = tokenize(source);
	for (let i = 0; i < tokens.length; i++) {
		const tok = tokens[i];
		if (tok.kind !== "ident" || !ENTITY_COLUMN_METHODS.has(tok.value)) {
			continue;
		}
		if (tokens[i - 1]?.value !== ".") {
			continue;
		}
		let j = i + 1;
		if (tokens[j]?.value === "<") {
			let depth = 0;
			for (; j < tokens.length; j++) {
				if (tokens[j].value === "<") {
					depth++;
				} else if (tokens[j].value === ">") {
					depth--;
					if (depth === 0) {
						j++;
						break;
					}
				}
			}
		}
		if (tokens[j]?.value !== "(") {
			continue;
		}
		const openParen = j;
		const closeParen = matchForwardParen(tokens, openParen);
		if (closeParen < 0 || offset < tokens[openParen].start || offset > tokens[closeParen].end) {
			continue;
		}
		// offset is inside THIS call - resolve strictly against it.
		const nameArg = firstDirectLiteralArg(tokens, openParen, closeParen);
		if (!nameArg || offset < nameArg.start || offset > nameArg.end) {
			return undefined;
		}
		return {
			columnName: nameArg.value,
			explicitSchemaName: nameArg.qualifier,
			start: nameArg.start,
			end: nameArg.end
		};
	}
	return undefined;
}
