/* eslint-disable @typescript-eslint/no-var-requires */
const fs = require("fs");
const path = require("path");
const { parseAmdModule } = require("../out/parse/amdParser");
const { SymbolIndex } = require("../out/index/SymbolIndex");
const { buildPlatformStubs } = require("../out/stubs/platformGlobals");
const { buildExtStubs } = require("../out/stubs/extGlobals");
const { resolveAppLayout } = require("../out/index/workspaceLayout");
const {
	parseStructuresLine,
	packageFromStackEntry
} = require("../out/index/schemaHierarchy");

const root =
	process.env.BPMSOFT_APP_ROOT ||
	path.resolve(__dirname, "../../crm-volumes/bpmsoftdevelopment");

// --- layout detection for different open roots ---
const layoutCases = [
	["app-root", root],
	["configuration", path.join(root, "BPMSoft.Configuration")],
	["pkg", path.join(root, "BPMSoft.Configuration", "Pkg")],
	[
		"package",
		path.join(root, "BPMSoft.Configuration", "Pkg", "GoRestaurantsMain")
	]
];
for (const [label, openPath] of layoutCases) {
	const layout = resolveAppLayout(openPath);
	const ok =
		layout.kind === label &&
		layout.confContent &&
		fs.existsSync(layout.confContent) &&
		layout.resourcesRoot &&
		fs.existsSync(layout.resourcesRoot) &&
		layout.autogeneratedRoot &&
		fs.existsSync(layout.autogeneratedRoot) &&
		layout.configurationRoot &&
		fs.existsSync(layout.configurationRoot);
	console.log(
		`layout ${label}: kind=${layout.kind} conf=${!!layout.confContent} res=${!!layout.resourcesRoot} auto=${!!layout.autogeneratedRoot}`
	);
	if (!ok) {
		console.error("Layout detection failed for", label, openPath, layout);
		process.exit(1);
	}
}

// Stubs must resolve when "workspace" is a package folder
const packageRoot = path.join(
	root,
	"BPMSoft.Configuration",
	"Pkg",
	"GoRestaurantsMain"
);
const stubsFromPackage = buildPlatformStubs([packageRoot]);
const structuresFromPackage = stubsFromPackage
	.find((m) => m.name === "configuration")
	?.children?.find((c) => c.name === "Structures");
console.log(
	"Structures from package-open:",
	structuresFromPackage?.children?.length || 0
);
if ((structuresFromPackage?.children?.length || 0) < 100) {
	console.error("Expected Structures when workspace is Pkg/{Package}");
	process.exit(1);
}
const extFromPackage = buildExtStubs([packageRoot]);
if (!extFromPackage.some((m) => m.name === "isEmpty")) {
	console.error("Expected Ext stubs when workspace is Pkg/{Package}");
	process.exit(1);
}

const samples = [
	"BPMSoft.Configuration/Pkg/GoRestaurantsMain/Schemas/GoClientConstants/GoClientConstants.js",
	"BPMSoft.Configuration/Pkg/GoRestaurantsMain/Schemas/LeadPageV2/LeadPageV2.js",
	"BPMSoft.Configuration/Pkg/GoRestaurantsMain/Schemas/GoCrossSellCommunicationModalBoxMixin/GoCrossSellCommunicationModalBoxMixin.js",
	"BPMSoft.Configuration/Pkg/GoRestaurantsMain/Schemas/MainHeaderSchema/MainHeaderSchema.js",
	"BPMSoft.Configuration/Pkg/GoMain/Schemas/MainHeaderSchema/MainHeaderSchema.js",
	"BPMSoft.Configuration/Autogenerated/Src/MainHeaderSchema.NUI.js",
	"BPMSoft.Configuration/Pkg/GoMain/Schemas/GoPersonalDataGrid/GoPersonalDataGrid.js",
	"Resources/ui/BPMSoft/controls/grid/grid.js",
	"BPMSoft.Configuration/Pkg/GoInfrastructure/Schemas/GoWSFieldManagementMixinOverride/GoWSFieldManagementMixinOverride.js",
	"BPMSoft.Configuration/Autogenerated/Src/WSFieldManagementMixin.WSFieldsmanagement.js",
	"Resources/ui/BPMSoft/core/sys-settings.js"
];

const index = new SymbolIndex();
index.setWorkspaceRoots([root]);
index.setPlatformStubs(buildPlatformStubs([root]));
index.setExtStubs(buildExtStubs([root]));
let failed = false;

for (const rel of samples) {
	const filePath = path.join(root, rel);
	if (!fs.existsSync(filePath)) {
		console.error("MISSING", filePath);
		failed = true;
		continue;
	}
	const source = fs.readFileSync(filePath, "utf8");
	const mod = parseAmdModule(source, filePath);
	if (!mod) {
		console.error("PARSE FAIL", rel);
		failed = true;
		continue;
	}
	index.upsertModule(mod);
	console.log(
		`OK ${mod.name} kind=${mod.kind} members=${mod.members.length} override=${mod.override || "-"} extend=${mod.extend || "-"}`
	);
}

const consts = index.resolveMembers("GoClientConstants", true);
if (consts.length < 5) {
	console.error("Expected many GoClientConstants members");
	failed = true;
}

const bpm = index.resolveMembers("BPMSoft", true);
for (const need of ["DataValueType", "emptyString", "MessageMode", "SysValue", "SysSettings", "configuration"]) {
	if (!bpm.some((m) => m.name === need)) {
		console.error("Missing BPMSoft root member", need);
		failed = true;
	}
}
console.log("BPMSoft. root count=", bpm.length);

const sysValue = index.resolveMembers("BPMSoft.SysValue", true);
if (!sysValue.some((m) => m.name === "CURRENT_USER")) {
	console.error("Expected BPMSoft.SysValue.CURRENT_USER");
	failed = true;
} else {
	console.log("BPMSoft.SysValue OK", sysValue.length);
}

const sysSettings = index.resolveMembers("BPMSoft.SysSettings", true);
if (!sysSettings.some((m) => m.name === "querySysSettingsItem")) {
	console.error("Expected BPMSoft.SysSettings.querySysSettingsItem");
	failed = true;
} else {
	console.log("BPMSoft.SysSettings OK", sysSettings.length);
}

const structures = index.resolveMembers("BPMSoft.configuration.Structures", true);
console.log("Structures schemas=", structures.length);
if (structures.length < 100) {
	console.error("Expected many Structures schema names from conf/content");
	failed = true;
}
if (!structures.some((m) => m.name === "LeadPageV2")) {
	console.error("Expected Structures.LeadPageV2");
	failed = true;
}
if (!structures.some((m) => m.name === "MainHeaderSchema")) {
	console.error("Expected Structures.MainHeaderSchema");
	failed = true;
}

const extRoot = index.resolveMembers("Ext", true);
if (!extRoot.some((m) => m.name === "isEmpty")) {
	console.error("Expected Ext.isEmpty");
	failed = true;
} else {
	console.log("Ext. members=", extRoot.length);
}
const extString = index.resolveMembers("Ext.String", true);
if (!extString.some((m) => m.name === "format")) {
	console.error("Expected Ext.String.format");
	failed = true;
} else {
	console.log("Ext.String OK", extString.length);
}

const nested = index.resolveMembers("BPMSoft.DataValueType", true);
if (!nested.some((m) => m.name === "BOOLEAN")) {
	console.error("Missing DataValueType.BOOLEAN");
	failed = true;
}

// --- conf Structures parse ---
const leadConf = fs
	.readFileSync(path.join(root, "conf/content/LeadPageV2.js"), "utf8")
	.slice(0, 2500);
const leadStruct = parseStructuresLine(leadConf, "LeadPageV2");
console.log(
	"LeadPageV2 structureParent=",
	leadStruct?.structureParent,
	"stackLen=",
	leadStruct?.innerHierarchyStack?.length
);
if (!leadStruct || leadStruct.structureParent !== "BaseLeadPage") {
	console.error("Failed to parse LeadPageV2 Structures");
	failed = true;
}
if (packageFromStackEntry("LeadPageV2", "LeadPageV2OrderLead") !== "OrderLead") {
	console.error("packageFromStackEntry failed");
	failed = true;
}

const layers = index.hierarchy.resolveSchemaLayers("LeadPageV2");
console.log(
	"LeadPageV2 layers:",
	layers.length,
	layers
		.slice(0, 6)
		.map((l) => `${l.source}:${path.basename(l.filePath)}`)
		.join(", "),
	"..."
);
if (layers.length < 10) {
	console.error("Expected deep LeadPageV2 hierarchy layers");
	failed = true;
}
if (!layers.some((l) => /GoRestaurantsMain/.test(l.filePath))) {
	console.error("Expected GoRestaurantsMain Pkg-extra in LeadPageV2 layers");
	failed = true;
}
if (!layers.some((l) => /LeadPageV2\.Lead\.js/.test(l.filePath))) {
	console.error("Expected Autogenerated LeadPageV2.Lead.js in stack");
	failed = true;
}
if (!layers.some((l) => /BaseLeadPage/.test(l.filePath))) {
	console.error("Expected structureParent BaseLeadPage layers");
	failed = true;
}

// Rightmost stack wins: bare LeadPageV2 → EventTracking in this volume
const orderLead = layers.find((l) => /LeadPageV2\.OrderLead\.js/.test(l.filePath));
const eventTracking = layers.find((l) =>
	/LeadPageV2\.EventTracking\.js/.test(l.filePath)
);
if (orderLead && eventTracking) {
	if (layers.indexOf(eventTracking) >= layers.indexOf(orderLead)) {
		console.error(
			"Expected EventTracking (rightmost/top) before OrderLead in child→parent order"
		);
		failed = true;
	}
}

const leadPath = path.join(root, samples[1]);
const thisMembers = index.resolveThisMembers(leadPath);
console.log(
	"LeadPageV2 this. members:",
	thisMembers.length,
	"sample detail=",
	thisMembers.find((m) => m.name === "onEntityInitialized")?.detail ||
		thisMembers[0]?.detail
);
if (thisMembers.length < 50) {
	console.error("Expected rich this. members from hierarchy");
	failed = true;
}

const headerPath = path.join(root, samples[3]);
const headerThis = index.resolveThisMembers(headerPath);
const hasSetSettings = headerThis.some((m) => m.name === "setSettings");
const headerHits = index.findThisMemberLocations(headerPath, "setSettings");
console.log(
	"MainHeaderSchema this.setSettings?",
	hasSetSettings,
	"locations=",
	headerHits.map((h) => path.basename(h.module.filePath)).join(", ")
);
if (!hasSetSettings) {
	console.error("Expected setSettings via hierarchy");
	failed = true;
}

const gridPath = path.join(root, samples[6]);
const gridThis = index.resolveThisMembers(gridPath);
if (!gridThis.some((m) => m.name === "formatCellContent")) {
	console.error("Expected Grid parent methods on GoPersonalDataGrid");
	failed = true;
} else {
	console.log("GoPersonalDataGrid override→Grid OK");
}

const wsOverridePath = path.join(root, samples[8]);
const wsThis = index.resolveThisMembers(wsOverridePath);
if (!wsThis.some((m) => m.name === "getFilterCollectionResult")) {
	console.error("Expected WSFieldManagementMixin parent method");
	failed = true;
} else {
	console.log("GoWSFieldManagementMixinOverride OK");
}

if (failed) {
	console.error("SMOKE FAILED");
	process.exit(1);
}
console.log("SMOKE PASSED");
