/* eslint-disable @typescript-eslint/no-var-requires */
const fs = require("fs");
const path = require("path");
const { parseAmdModule, parseEntityColumns, getThisGetSetContext, getThisLookupAccessContext } = require("../out/parse/amdParser");
const { SymbolIndex } = require("../out/index/SymbolIndex");
const { buildPlatformStubs } = require("../out/stubs/platformGlobals");
const { buildExtStubs } = require("../out/stubs/extGlobals");
const { buildSandboxStubs } = require("../out/stubs/sandboxGlobals");
const { resolveAppLayout } = require("../out/index/workspaceLayout");
const {
	parseStructuresLine,
	packageFromStackEntry,
	parseStructurePlatformExtend
} = require("../out/index/schemaHierarchy");

const root =
	process.env.BPMSOFT_APP_ROOT ||
	path.resolve(__dirname, "../../crm-volumes/bpmsoftdevelopment");

// --- layout detection for different open roots ---
const layoutCases = [
	["app-root", root],
	["configuration", path.join(root, "BPMSoft.Configuration")],
	["pkg", path.join(root, "BPMSoft.Configuration", "Pkg")],
	[
		"package",
		path.join(root, "BPMSoft.Configuration", "Pkg", "GoRestaurantsMain")
	]
];
for (const [label, openPath] of layoutCases) {
	const layout = resolveAppLayout(openPath);
	const ok =
		layout.kind === label &&
		layout.confContent &&
		fs.existsSync(layout.confContent) &&
		layout.resourcesRoot &&
		fs.existsSync(layout.resourcesRoot) &&
		layout.autogeneratedRoot &&
		fs.existsSync(layout.autogeneratedRoot) &&
		layout.configurationRoot &&
		fs.existsSync(layout.configurationRoot);
	console.log(
		`layout ${label}: kind=${layout.kind} conf=${!!layout.confContent} res=${!!layout.resourcesRoot} auto=${!!layout.autogeneratedRoot}`
	);
	if (!ok) {
		console.error("Layout detection failed for", label, openPath, layout);
		process.exit(1);
	}
}

// Stubs must resolve when "workspace" is a package folder
const packageRoot = path.join(
	root,
	"BPMSoft.Configuration",
	"Pkg",
	"GoRestaurantsMain"
);
const stubsFromPackage = buildPlatformStubs([packageRoot]);
const structuresFromPackage = stubsFromPackage
	.find((m) => m.name === "configuration")
	?.children?.find((c) => c.name === "Structures");
console.log(
	"Structures from package-open:",
	structuresFromPackage?.children?.length || 0
);
if ((structuresFromPackage?.children?.length || 0) < 100) {
	console.error("Expected Structures when workspace is Pkg/{Package}");
	process.exit(1);
}
const extFromPackage = buildExtStubs([packageRoot]);
if (!extFromPackage.some((m) => m.name === "isEmpty")) {
	console.error("Expected Ext stubs when workspace is Pkg/{Package}");
	process.exit(1);
}
const sandboxFromPackage = buildSandboxStubs([packageRoot]);
const sandboxMembers = sandboxFromPackage.members;
const sandboxSubscribe = sandboxMembers.find((m) => m.name === "subscribe");
if (!sandboxMembers.some((m) => m.name === "publish")) {
	console.error("Expected sandbox.publish from bootstrap.js when workspace is Pkg/{Package}");
	process.exit(1);
}
if (!sandboxSubscribe?.documentation || !/Subscribes/i.test(sandboxSubscribe.documentation)) {
	console.error("Expected sandbox.subscribe JSDoc from bootstrap.js, got", sandboxSubscribe?.documentation);
	process.exit(1);
}
if (!sandboxMembers.some((m) => m.name === "id" && m.kind === "property")) {
	console.error("Expected sandbox.id from core-base.js createSandbox");
	process.exit(1);
}
const sandboxLoad = sandboxMembers.find((m) => m.name === "loadModule");
if (
	!sandboxLoad?.filePath ||
	!/core-base\.js$/i.test(sandboxLoad.filePath) ||
	sandboxLoad.position == null
) {
	console.error(
		"Expected this.sandbox.loadModule definition in core-base.js",
		sandboxLoad?.filePath,
		sandboxLoad?.position
	);
	process.exit(1);
}
if (!sandboxSubscribe.filePath || !/bootstrap\.js$/i.test(sandboxSubscribe.filePath)) {
	console.error("Expected sandbox.subscribe definition in bootstrap.js");
	process.exit(1);
}
console.log("sandbox from package-open:", sandboxMembers.length);

const samples = [
	"BPMSoft.Configuration/Pkg/GoRestaurantsMain/Schemas/GoClientConstants/GoClientConstants.js",
	"BPMSoft.Configuration/Pkg/GoRestaurantsMain/Schemas/LeadPageV2/LeadPageV2.js",
	"BPMSoft.Configuration/Pkg/GoRestaurantsMain/Schemas/GoCrossSellCommunicationModalBoxMixin/GoCrossSellCommunicationModalBoxMixin.js",
	"BPMSoft.Configuration/Pkg/GoRestaurantsMain/Schemas/MainHeaderSchema/MainHeaderSchema.js",
	"BPMSoft.Configuration/Pkg/GoMain/Schemas/MainHeaderSchema/MainHeaderSchema.js",
	"BPMSoft.Configuration/Autogenerated/Src/MainHeaderSchema.NUI.js",
	"BPMSoft.Configuration/Pkg/GoMain/Schemas/GoPersonalDataGrid/GoPersonalDataGrid.js",
	"Resources/ui/BPMSoft/controls/grid/grid.js",
	"BPMSoft.Configuration/Pkg/GoInfrastructure/Schemas/GoWSFieldManagementMixinOverride/GoWSFieldManagementMixinOverride.js",
	"BPMSoft.Configuration/Autogenerated/Src/WSFieldManagementMixin.WSFieldsmanagement.js",
	"Resources/ui/BPMSoft/core/sys-settings.js",
	"Resources/ui/BPMSoft/data/models/base-view-model.js",
	"Resources/ui/BPMSoft/data/models/base-model.js",
	"Resources/ui/BPMSoft/core/baseobject.js"
];

const index = new SymbolIndex();
index.setWorkspaceRoots([root]);
index.setPlatformStubs(buildPlatformStubs([root]));
index.setExtStubs(buildExtStubs([root]));
const sandboxBuilt = buildSandboxStubs([root]);
index.setSandboxStubs(sandboxBuilt.members, sandboxBuilt.origin);
let failed = false;

for (const rel of samples) {
	const filePath = path.join(root, rel);
	if (!fs.existsSync(filePath)) {
		console.error("MISSING", filePath);
		failed = true;
		continue;
	}
	const source = fs.readFileSync(filePath, "utf8");
	const mod = parseAmdModule(source, filePath);
	if (!mod) {
		console.error("PARSE FAIL", rel);
		failed = true;
		continue;
	}
	index.upsertModule(mod);
	console.log(
		`OK ${mod.name} kind=${mod.kind} members=${mod.members.length} override=${mod.override || "-"} extend=${mod.extend || "-"}`
	);
}

const consts = index.resolveMembers("GoClientConstants", true);
if (consts.length < 5) {
	console.error("Expected many GoClientConstants members");
	failed = true;
}

const bpm = index.resolveMembers("BPMSoft", true);
for (const need of ["DataValueType", "emptyString", "MessageMode", "SysValue", "SysSettings", "configuration"]) {
	if (!bpm.some((m) => m.name === need)) {
		console.error("Missing BPMSoft root member", need);
		failed = true;
	}
}
console.log("BPMSoft. root count=", bpm.length);

const sysValue = index.resolveMembers("BPMSoft.SysValue", true);
if (!sysValue.some((m) => m.name === "CURRENT_USER")) {
	console.error("Expected BPMSoft.SysValue.CURRENT_USER");
	failed = true;
} else {
	console.log("BPMSoft.SysValue OK", sysValue.length);
}

const sysSettings = index.resolveMembers("BPMSoft.SysSettings", true);
if (!sysSettings.some((m) => m.name === "querySysSettingsItem")) {
	console.error("Expected BPMSoft.SysSettings.querySysSettingsItem");
	failed = true;
} else {
	console.log("BPMSoft.SysSettings OK", sysSettings.length);
}

const structures = index.resolveMembers("BPMSoft.configuration.Structures", true);
console.log("Structures schemas=", structures.length);
if (structures.length < 100) {
	console.error("Expected many Structures schema names from conf/content");
	failed = true;
}
if (!structures.some((m) => m.name === "LeadPageV2")) {
	console.error("Expected Structures.LeadPageV2");
	failed = true;
}
if (!structures.some((m) => m.name === "MainHeaderSchema")) {
	console.error("Expected Structures.MainHeaderSchema");
	failed = true;
}

const extRoot = index.resolveMembers("Ext", true);
if (!extRoot.some((m) => m.name === "isEmpty")) {
	console.error("Expected Ext.isEmpty");
	failed = true;
} else {
	console.log("Ext. members=", extRoot.length);
}
const extString = index.resolveMembers("Ext.String", true);
if (!extString.some((m) => m.name === "format")) {
	console.error("Expected Ext.String.format");
	failed = true;
} else {
	console.log("Ext.String OK", extString.length);
}

const nested = index.resolveMembers("BPMSoft.DataValueType", true);
if (!nested.some((m) => m.name === "BOOLEAN")) {
	console.error("Missing DataValueType.BOOLEAN");
	failed = true;
}

// --- conf Structures parse ---
const leadConf = fs
	.readFileSync(path.join(root, "conf/content/LeadPageV2.js"), "utf8")
	.slice(0, 2500);
const leadStruct = parseStructuresLine(leadConf, "LeadPageV2");
console.log(
	"LeadPageV2 structureParent=",
	leadStruct?.structureParent,
	"stackLen=",
	leadStruct?.innerHierarchyStack?.length
);
if (!leadStruct || leadStruct.structureParent !== "BaseLeadPage") {
	console.error("Failed to parse LeadPageV2 Structures");
	failed = true;
}
const leadExtend = parseStructurePlatformExtend(leadConf);
if (leadExtend !== "BPMSoft.model.BaseViewModel") {
	console.error("Expected LeadPageV2 Structure extend BPMSoft.model.BaseViewModel", leadExtend);
	failed = true;
}
const baseDataViewConf = fs
	.readFileSync(path.join(root, "conf/content/BaseDataView.js"), "utf8")
	.slice(0, 2500);
const baseDvExtend = parseStructurePlatformExtend(baseDataViewConf);
if (baseDvExtend !== "BPMSoft.model.BaseViewModel") {
	console.error("Expected BaseDataView Structure extend BPMSoft.model.BaseViewModel", baseDvExtend);
	failed = true;
}
if (packageFromStackEntry("LeadPageV2", "LeadPageV2OrderLead") !== "OrderLead") {
	console.error("packageFromStackEntry failed");
	failed = true;
}

const layers = index.hierarchy.resolveSchemaLayers("LeadPageV2");
console.log(
	"LeadPageV2 layers:",
	layers.length,
	layers
		.slice(0, 6)
		.map((l) => `${l.source}:${path.basename(l.filePath)}`)
		.join(", "),
	"..."
);
if (layers.length < 10) {
	console.error("Expected deep LeadPageV2 hierarchy layers");
	failed = true;
}
if (!layers.some((l) => /GoRestaurantsMain/.test(l.filePath))) {
	console.error("Expected GoRestaurantsMain Pkg-extra in LeadPageV2 layers");
	failed = true;
}
if (!layers.some((l) => /LeadPageV2\.Lead\.js/.test(l.filePath))) {
	console.error("Expected Autogenerated LeadPageV2.Lead.js in stack");
	failed = true;
}
if (!layers.some((l) => /BaseLeadPage/.test(l.filePath))) {
	console.error("Expected structureParent BaseLeadPage layers");
	failed = true;
}

// Rightmost stack wins: bare LeadPageV2 → EventTracking in this volume
const orderLead = layers.find((l) => /LeadPageV2\.OrderLead\.js/.test(l.filePath));
const eventTracking = layers.find((l) =>
	/LeadPageV2\.EventTracking\.js/.test(l.filePath)
);
if (orderLead && eventTracking) {
	if (layers.indexOf(eventTracking) >= layers.indexOf(orderLead)) {
		console.error(
			"Expected EventTracking (rightmost/top) before OrderLead in child→parent order"
		);
		failed = true;
	}
}

const leadPath = path.join(root, samples[1]);
const thisMembers = index.resolveThisMembers(leadPath);
console.log(
	"LeadPageV2 this. members:",
	thisMembers.length,
	"sample detail=",
	thisMembers.find((m) => m.name === "onEntityInitialized")?.detail ||
		thisMembers[0]?.detail
);
if (thisMembers.length < 50) {
	console.error("Expected rich this. members from hierarchy");
	failed = true;
}
const leadIndustryCol = thisMembers.find((m) => m.name === "Industry" && m.kind === "attribute");
const leadTitleCol = thisMembers.find((m) => m.name === "Title" && m.kind === "attribute");
if (!leadTitleCol) {
	console.error("Expected Lead entity column this.$Title from conf/content/Lead.js");
	failed = true;
}
if (!leadIndustryCol?.children?.some((c) => c.name === "displayValue")) {
	console.error("Expected Lead.Industry lookup fields value/displayValue");
	failed = true;
} else {
	console.log("Lead entity columns OK", "Title", !!leadTitleCol, "Industry.lookup", true);
}
const platformGet = thisMembers.find((m) => m.name === "get" && m.kind === "method");
const platformDestroy = thisMembers.find((m) => m.name === "destroy");
if (!platformGet) {
	console.error("Expected this.get from BPMSoft.model.BaseModel via Structure extend");
	failed = true;
}
if (!platformDestroy) {
	console.error("Expected this.destroy from BPMSoft.core.BaseObject via extend chain");
	failed = true;
} else {
	console.log(
		"platform this.get/destroy OK",
		platformGet?.detail,
		platformDestroy.detail
	);
}
const thisExt = thisMembers.find((m) => m.name === "Ext");
const thisBpmsoft = thisMembers.find((m) => m.name === "BPMSoft");
const thisSandbox = thisMembers.find((m) => m.name === "sandbox");
const sandboxApi = ["publish", "subscribe", "loadModule", "registerMessages"];
if (!thisExt || !thisBpmsoft || !thisSandbox) {
	console.error("Expected this.Ext / this.BPMSoft / this.sandbox on schema");
	failed = true;
} else if (
	!sandboxApi.every((name) => thisSandbox.children?.some((c) => c.name === name))
) {
	console.error("Expected this.sandbox.publish/subscribe/loadModule");
	failed = true;
} else {
	console.log(
		"this.Ext/BPMSoft/sandbox OK",
		"sandbox children=",
		thisSandbox.children?.length || 0
	);
	const loadMod = thisSandbox.children?.find((c) => c.name === "loadModule");
	if (
		!loadMod?.filePath ||
		!/core-base\.js$/i.test(loadMod.filePath) ||
		loadMod.position == null
	) {
		console.error("Expected this.sandbox.loadModule Go to Definition in core-base.js");
		failed = true;
	}
}

const headerPath = path.join(root, samples[3]);
const headerThis = index.resolveThisMembers(headerPath);
const hasSetSettings = headerThis.some((m) => m.name === "setSettings");
const headerHits = index.findThisMemberLocations(headerPath, "setSettings");
console.log(
	"MainHeaderSchema this.setSettings?",
	hasSetSettings,
	"locations=",
	headerHits.map((h) => path.basename(h.module.filePath)).join(", ")
);
if (!hasSetSettings) {
	console.error("Expected setSettings via hierarchy");
	failed = true;
}

const gridPath = path.join(root, samples[6]);
const gridThis = index.resolveThisMembers(gridPath);
if (!gridThis.some((m) => m.name === "formatCellContent")) {
	console.error("Expected Grid parent methods on GoPersonalDataGrid");
	failed = true;
} else {
	console.log("GoPersonalDataGrid override→Grid OK");
}

const wsOverridePath = path.join(root, samples[8]);
const wsThis = index.resolveThisMembers(wsOverridePath);
if (!wsThis.some((m) => m.name === "getFilterCollectionResult")) {
	console.error("Expected WSFieldManagementMixin parent method");
	failed = true;
} else {
	console.log("GoWSFieldManagementMixinOverride OK");
}
if (!wsThis.some((m) => m.name === "colorTimeout" && m.kind === "property")) {
	console.error("Expected colorTimeout property from parent mixin");
	failed = true;
} else {
	console.log("GoWSFieldManagementMixinOverride this.colorTimeout OK");
}

const syntheticChild = parseAmdModule(
	`
define("GoPropChild", [], function() {
	return {
		entitySchemaName: "Lead",
		properties: {
			childFlag: true,
			titleText: "hello"
		},
		methods: {
			onEntityInitialized: function() {}
		}
	};
});
`,
	path.join(root, "synthetic/GoPropChild.js")
);
const syntheticParent = parseAmdModule(
	`
define("GoPropParent", [], function() {
	return {
		entitySchemaName: "Lead",
		properties: {
			parentProp: "from-parent",
			titleText: "parent-title"
		},
		methods: {
			parentMethod: function() {}
		}
	};
});
`,
	path.join(root, "synthetic/GoPropParent.js")
);
if (!syntheticChild || !syntheticParent) {
	console.error("Failed to parse synthetic property schemas");
	failed = true;
} else {
	index.upsertModule(syntheticParent);
	index.upsertModule(syntheticChild);
	const childProps = syntheticChild.members.filter((m) => m.kind === "property");
	const parentProps = syntheticParent.members.filter((m) => m.kind === "property");
	console.log(
		"synthetic properties: child=",
		childProps.map((m) => m.name).join(","),
		"parent=",
		parentProps.map((m) => m.name).join(",")
	);
	if (!childProps.some((m) => m.name === "titleText" && m.documentation === '"hello"')) {
		console.error("Expected child property titleText with literal preview");
		failed = true;
	}
	if (!childProps.some((m) => m.name === "childFlag")) {
		console.error("Expected childFlag property");
		failed = true;
	}
	if (syntheticChild.members.some((m) => m.name === "onEntityInitialized" && m.kind !== "method")) {
		console.error("Expected onEntityInitialized to remain a method");
		failed = true;
	}
	const childThis = index.resolveThisMembers(syntheticChild.filePath);
	if (!childThis.some((m) => m.name === "titleText" && m.kind === "property")) {
		console.error("Expected this.titleText from properties");
		failed = true;
	}
	const titleHits = index.findThisMemberLocations(
		syntheticChild.filePath,
		"titleText"
	);
	if (!titleHits.length || titleHits[0].member.kind !== "property") {
		console.error("Expected Go to Definition for this.titleText");
		failed = true;
	}
}

const syntheticMixin = parseAmdModule(
	`
define("GoSynthMixin", [], function() {
	Ext.define("BPMSoft.configuration.mixins.GoSynthMixin", {
		alternateClassName: "BPMSoft.GoSynthMixin",
		colorTimeout: 0,
		getFilterCollectionResult: function() {}
	});
	return Ext.create("BPMSoft.configuration.mixins.GoSynthMixin");
});
`,
	path.join(root, "synthetic/GoSynthMixin.js")
);
const syntheticOverride = parseAmdModule(
	`
define("GoSynthMixinOverride", ["GoSynthMixin"], function() {
	Ext.define("BPMSoft.configuration.mixins.GoSynthMixinOverride", {
		override: "BPMSoft.GoSynthMixin",
		maxColoringRetryCount: 50,
		getFieldsColors: function() {}
	});
});
`,
	path.join(root, "synthetic/GoSynthMixinOverride.js")
);
if (!syntheticMixin || !syntheticOverride) {
	console.error("Failed to parse synthetic mixin/override");
	failed = true;
} else {
	index.upsertModule(syntheticMixin);
	index.upsertModule(syntheticOverride);
	if (!syntheticMixin.members.some((m) => m.name === "colorTimeout" && m.kind === "property")) {
		console.error("Expected mixin root property colorTimeout");
		failed = true;
	}
	if (syntheticMixin.members.some((m) => m.name === "alternateClassName")) {
		console.error("Did not expect Ext.define meta key alternateClassName as member");
		failed = true;
	}
	const overrideThis = index.resolveThisMembers(syntheticOverride.filePath);
	if (!overrideThis.some((m) => m.name === "colorTimeout" && m.kind === "property")) {
		console.error("Expected this.colorTimeout from parent mixin");
		failed = true;
	}
	if (!overrideThis.some((m) => m.name === "maxColoringRetryCount")) {
		console.error("Expected this.maxColoringRetryCount from override");
		failed = true;
	}
	const colorHits = index.findThisMemberLocations(
		syntheticOverride.filePath,
		"colorTimeout"
	);
	if (!colorHits.length) {
		console.error("Expected Go to Definition for this.colorTimeout");
		failed = true;
	} else {
		console.log("synthetic mixin this.colorTimeout OK");
	}
}

const syntheticAttrChild = parseAmdModule(
	`
define("GoAttrChild", [], function() {
	return {
		entitySchemaName: "Lead",
		attributes: {
			"ChildFlag": {
				dataValueType: BPMSoft.DataValueType.BOOLEAN,
				value: true
			},
			"TitleText": {
				dataValueType: BPMSoft.DataValueType.TEXT,
				value: "hello"
			},
			"SearchFieldFilterList": {
				dataValueType: BPMSoft.DataValueType.ENUM
			},
			"Owner": {
				dataValueType: BPMSoft.DataValueType.LOOKUP
			}
		},
		methods: {
			onEntityInitialized: function() {
				this.get("TitleText");
				this.set("ChildFlag", false);
				this.$TitleText = "x";
			}
		}
	};
});
`,
	path.join(root, "synthetic/GoAttrChild.js")
);
const syntheticAttrParent = parseAmdModule(
	`
define("GoAttrChild", [], function() {
	return {
		entitySchemaName: "Lead",
		attributes: {
			"ParentAttr": {
				dataValueType: BPMSoft.DataValueType.INTEGER,
				value: 1
			},
			"TitleText": {
				dataValueType: BPMSoft.DataValueType.TEXT,
				value: "parent"
			}
		}
	};
});
`,
	path.join(root, "synthetic/GoAttrParent.js")
);
if (!syntheticAttrChild || !syntheticAttrParent) {
	console.error("Failed to parse synthetic attribute schemas");
	failed = true;
} else {
	const attrIndex = new SymbolIndex();
	attrIndex.upsertModule(syntheticAttrParent);
	attrIndex.upsertModule(syntheticAttrChild);
	const childAttrs = syntheticAttrChild.members.filter((m) => m.kind === "attribute");
	if (!childAttrs.some((m) => m.name === "TitleText")) {
		console.error("Expected TitleText attribute");
		failed = true;
	}
	if (!childAttrs.some((m) => m.documentation && m.documentation.includes("DataValueType.TEXT"))) {
		console.error("Expected attribute dataValueType in documentation");
		failed = true;
	}
	const attrThis = attrIndex.resolveThisMembers(syntheticAttrChild.filePath);
	if (!attrThis.some((m) => m.name === "TitleText" && m.kind === "attribute")) {
		console.error("Expected this.$TitleText from attributes");
		failed = true;
	}
	if (!attrThis.some((m) => m.name === "ParentAttr" && m.kind === "attribute")) {
		console.error("Expected parent attribute ParentAttr via same-name replacement");
		failed = true;
	}
	const dollarHits = attrIndex.findThisMemberLocations(
		syntheticAttrChild.filePath,
		"$TitleText"
	);
	if (!dollarHits.length || dollarHits[0].member.kind !== "attribute") {
		console.error("Expected Go to Definition for this.$TitleText");
		failed = true;
	}
	const getHits = attrIndex.findThisMemberLocations(
		syntheticAttrChild.filePath,
		"TitleText",
		"attribute"
	);
	if (!getHits.length) {
		console.error("Expected Go to Definition for this.get(\"TitleText\")");
		failed = true;
	}
	const src = "this.get(\"TitleText\"); this.set(\"ChildFlag\", 1);";
	const getCtx = getThisGetSetContext(src, src.indexOf("TitleText") + 2);
	const setCtx = getThisGetSetContext(src, src.indexOf("ChildFlag") + 2);
	if (!getCtx || getCtx.method !== "get" || getCtx.name !== "TitleText") {
		console.error("getThisGetSetContext failed for this.get");
		failed = true;
	}
	if (!setCtx || setCtx.method !== "set" || setCtx.name !== "ChildFlag") {
		console.error("getThisGetSetContext failed for this.set");
		failed = true;
	}
	const enumAttr = childAttrs.find((m) => m.name === "SearchFieldFilterList");
	const lookupAttr = childAttrs.find((m) => m.name === "Owner");
	const textAttr = childAttrs.find((m) => m.name === "TitleText");
	if (!enumAttr?.children?.some((c) => c.name === "value") ||
		!enumAttr?.children?.some((c) => c.name === "displayValue")) {
		console.error("Expected ENUM attribute children value/displayValue");
		failed = true;
	}
	if (!lookupAttr?.children?.some((c) => c.name === "displayValue")) {
		console.error("Expected LOOKUP attribute children value/displayValue");
		failed = true;
	}
	if (textAttr?.children?.length) {
		console.error("Did not expect nested fields on TEXT attribute");
		failed = true;
	}
	const dollarLookup = "this.$SearchFieldFilterList.";
	const getLookup = 'this.get("Owner").';
	const dollarCtx = getThisLookupAccessContext(dollarLookup, dollarLookup.length);
	const getLookupCtx = getThisLookupAccessContext(getLookup, getLookup.length);
	if (!dollarCtx || dollarCtx.attrName !== "SearchFieldFilterList") {
		console.error("getThisLookupAccessContext failed for this.$Enum.");
		failed = true;
	}
	if (!getLookupCtx || getLookupCtx.attrName !== "Owner") {
		console.error("getThisLookupAccessContext failed for this.get(\"Lookup\").");
		failed = true;
	}
	const getInsideDot = 'this.get("Owner".';
	const getValue = 'this.get("Owner").value';
	const getInsideCtx = getThisLookupAccessContext(getInsideDot, getInsideDot.length);
	const getValueCtx = getThisLookupAccessContext(getValue, getValue.length);
	if (!getInsideCtx || getInsideCtx.attrName !== "Owner") {
		console.error("getThisLookupAccessContext failed for this.get(\"Owner\".");
		failed = true;
	}
	if (!getValueCtx || getValueCtx.attrName !== "Owner") {
		console.error("getThisLookupAccessContext failed for this.get(\"Owner\").value");
		failed = true;
	} else {
		console.log("synthetic attributes this.$ / get / set OK");
	}
}

const syntheticEntityCols = parseEntityColumns(
	`
define("Account", ["BPMSoft"], function(BPMSoft) {
	Ext.define("BPMSoft.data.models.Account", {
		extend: "BPMSoft.BaseEntitySchema",
		columns: {
			Id: {
				dataValueType: BPMSoft.DataValueType.GUID,
				isRequired: true
			},
			Name: {
				dataValueType: BPMSoft.DataValueType.TEXT
			},
			Owner: {
				dataValueType: BPMSoft.DataValueType.LOOKUP,
				isLookup: true,
				referenceSchemaName: "Contact"
			}
		}
	});
});
`,
	"/tmp/conf/content/Account.js"
);
if (!syntheticEntityCols.some((m) => m.name === "Name" && m.kind === "attribute")) {
	console.error("Expected entity column Name");
	failed = true;
}
if (!syntheticEntityCols.some((m) => m.name === "Owner" && m.children?.some((c) => c.name === "value"))) {
	console.error("Expected entity LOOKUP Owner.value");
	failed = true;
} else {
	console.log("synthetic entity columns OK", syntheticEntityCols.map((m) => m.name).join(","));
}

if (failed) {
	console.error("SMOKE FAILED");
	process.exit(1);
}
console.log("SMOKE PASSED");
