/* eslint-disable @typescript-eslint/no-var-requires */
const fs = require("fs");
const path = require("path");
const { parseAmdModule, parseEntityColumns, getThisGetSetContext, getThisLookupAccessContext, getOverrideInsertContext, formatOverrideSnippet, collectLocalMethodKeys, collectThisMemberAccesses, planCreateMemberInsert } = require("../out/parse/amdParser");
const { SymbolIndex } = require("../out/index/SymbolIndex");
const { isPrivateMemberFromOtherFile } = require("../out/index/types");
const { buildPlatformStubs } = require("../out/stubs/platformGlobals");
const { buildExtStubs } = require("../out/stubs/extGlobals");
const { buildSandboxStubs } = require("../out/stubs/sandboxGlobals");
const { resolveAppLayout } = require("../out/index/workspaceLayout");
const {
	parseStructuresLine,
	packageFromStackEntry,
	parseStructurePlatformExtend,
	parseDescriptorParent,
	shouldWalkDescriptorParent
} = require("../out/index/schemaHierarchy");

const root =
	process.env.BPMSOFT_APP_ROOT ||
	path.resolve(__dirname, "../../crm-volumes/bpmsoftdevelopment");

// --- layout detection for different open roots ---
const layoutCases = [
	["app-root", root],
	["configuration", path.join(root, "BPMSoft.Configuration")],
	["pkg", path.join(root, "BPMSoft.Configuration", "Pkg")],
	[
		"package",
		path.join(root, "BPMSoft.Configuration", "Pkg", "GoRestaurantsMain")
	]
];
for (const [label, openPath] of layoutCases) {
	const layout = resolveAppLayout(openPath);
	const ok =
		layout.kind === label &&
		layout.confContent &&
		fs.existsSync(layout.confContent) &&
		layout.resourcesRoot &&
		fs.existsSync(layout.resourcesRoot) &&
		layout.autogeneratedRoot &&
		fs.existsSync(layout.autogeneratedRoot) &&
		layout.configurationRoot &&
		fs.existsSync(layout.configurationRoot);
	console.log(
		`layout ${label}: kind=${layout.kind} conf=${!!layout.confContent} res=${!!layout.resourcesRoot} auto=${!!layout.autogeneratedRoot}`
	);
	if (!ok) {
		console.error("Layout detection failed for", label, openPath, layout);
		process.exit(1);
	}
}

// Stubs must resolve when "workspace" is a package folder
const packageRoot = path.join(
	root,
	"BPMSoft.Configuration",
	"Pkg",
	"GoRestaurantsMain"
);
const stubsFromPackage = buildPlatformStubs([packageRoot]);
const structuresFromPackage = stubsFromPackage
	.find((m) => m.name === "configuration")
	?.children?.find((c) => c.name === "Structures");
console.log(
	"Structures from package-open:",
	structuresFromPackage?.children?.length || 0
);
if ((structuresFromPackage?.children?.length || 0) < 100) {
	console.error("Expected Structures when workspace is Pkg/{Package}");
	process.exit(1);
}
const extFromPackage = buildExtStubs([packageRoot]);
if (!extFromPackage.some((m) => m.name === "isEmpty")) {
	console.error("Expected Ext stubs when workspace is Pkg/{Package}");
	process.exit(1);
}
const sandboxFromPackage = buildSandboxStubs([packageRoot]);
const sandboxMembers = sandboxFromPackage.members;
const sandboxSubscribe = sandboxMembers.find((m) => m.name === "subscribe");
if (!sandboxMembers.some((m) => m.name === "publish")) {
	console.error("Expected sandbox.publish from bootstrap.js when workspace is Pkg/{Package}");
	process.exit(1);
}
if (!sandboxSubscribe?.documentation || !/Subscribes/i.test(sandboxSubscribe.documentation)) {
	console.error("Expected sandbox.subscribe JSDoc from bootstrap.js, got", sandboxSubscribe?.documentation);
	process.exit(1);
}
if (!sandboxMembers.some((m) => m.name === "id" && m.kind === "property")) {
	console.error("Expected sandbox.id from core-base.js createSandbox");
	process.exit(1);
}
const sandboxLoad = sandboxMembers.find((m) => m.name === "loadModule");
if (
	!sandboxLoad?.filePath ||
	!/core-base\.js$/i.test(sandboxLoad.filePath) ||
	sandboxLoad.position == null
) {
	console.error(
		"Expected this.sandbox.loadModule definition in core-base.js",
		sandboxLoad?.filePath,
		sandboxLoad?.position
	);
	process.exit(1);
}
if (!sandboxSubscribe.filePath || !/bootstrap\.js$/i.test(sandboxSubscribe.filePath)) {
	console.error("Expected sandbox.subscribe definition in bootstrap.js");
	process.exit(1);
}
console.log("sandbox from package-open:", sandboxMembers.length);

const samples = [
	"BPMSoft.Configuration/Pkg/GoRestaurantsMain/Schemas/GoClientConstants/GoClientConstants.js",
	"BPMSoft.Configuration/Pkg/GoRestaurantsMain/Schemas/LeadPageV2/LeadPageV2.js",
	"BPMSoft.Configuration/Pkg/GoRestaurantsMain/Schemas/GoCrossSellCommunicationModalBoxMixin/GoCrossSellCommunicationModalBoxMixin.js",
	"BPMSoft.Configuration/Pkg/GoRestaurantsMain/Schemas/MainHeaderSchema/MainHeaderSchema.js",
	"BPMSoft.Configuration/Pkg/GoMain/Schemas/MainHeaderSchema/MainHeaderSchema.js",
	"BPMSoft.Configuration/Autogenerated/Src/MainHeaderSchema.NUI.js",
	"BPMSoft.Configuration/Pkg/GoMain/Schemas/GoPersonalDataGrid/GoPersonalDataGrid.js",
	"Resources/ui/BPMSoft/controls/grid/grid.js",
	"BPMSoft.Configuration/Pkg/GoInfrastructure/Schemas/GoWSFieldManagementMixinOverride/GoWSFieldManagementMixinOverride.js",
	"BPMSoft.Configuration/Autogenerated/Src/WSFieldManagementMixin.WSFieldsmanagement.js",
	"Resources/ui/BPMSoft/core/sys-settings.js",
	"Resources/ui/BPMSoft/data/models/base-view-model.js",
	"Resources/ui/BPMSoft/data/models/base-model.js",
	"Resources/ui/BPMSoft/core/baseobject.js",
	"BPMSoft.Configuration/Autogenerated/Src/BaseSchemaViewModel.NUI.js"
];

const index = new SymbolIndex();
index.setWorkspaceRoots([root]);
index.setPlatformStubs(buildPlatformStubs([root]));
index.setExtStubs(buildExtStubs([root]));
const sandboxBuilt = buildSandboxStubs([root]);
index.setSandboxStubs(sandboxBuilt.members, sandboxBuilt.origin);
let failed = false;

for (const rel of samples) {
	const filePath = path.join(root, rel);
	if (!fs.existsSync(filePath)) {
		console.error("MISSING", filePath);
		failed = true;
		continue;
	}
	const source = fs.readFileSync(filePath, "utf8");
	const mod = parseAmdModule(source, filePath);
	if (!mod) {
		console.error("PARSE FAIL", rel);
		failed = true;
		continue;
	}
	index.upsertModule(mod);
	console.log(
		`OK ${mod.name} kind=${mod.kind} members=${mod.members.length} override=${mod.override || "-"} extend=${mod.extend || "-"}`
	);
}

const consts = index.resolveMembers("GoClientConstants", true);
if (consts.length < 5) {
	console.error("Expected many GoClientConstants members");
	failed = true;
}

const bpm = index.resolveMembers("BPMSoft", true);
for (const need of ["DataValueType", "emptyString", "MessageMode", "SysValue", "SysSettings", "configuration"]) {
	if (!bpm.some((m) => m.name === need)) {
		console.error("Missing BPMSoft root member", need);
		failed = true;
	}
}
console.log("BPMSoft. root count=", bpm.length);

const sysValue = index.resolveMembers("BPMSoft.SysValue", true);
if (!sysValue.some((m) => m.name === "CURRENT_USER")) {
	console.error("Expected BPMSoft.SysValue.CURRENT_USER");
	failed = true;
} else {
	console.log("BPMSoft.SysValue OK", sysValue.length);
}

const sysSettings = index.resolveMembers("BPMSoft.SysSettings", true);
if (!sysSettings.some((m) => m.name === "querySysSettingsItem")) {
	console.error("Expected BPMSoft.SysSettings.querySysSettingsItem");
	failed = true;
} else {
	console.log("BPMSoft.SysSettings OK", sysSettings.length);
}

const structures = index.resolveMembers("BPMSoft.configuration.Structures", true);
console.log("Structures schemas=", structures.length);
if (structures.length < 100) {
	console.error("Expected many Structures schema names from conf/content");
	failed = true;
}
if (!structures.some((m) => m.name === "LeadPageV2")) {
	console.error("Expected Structures.LeadPageV2");
	failed = true;
}
if (!structures.some((m) => m.name === "MainHeaderSchema")) {
	console.error("Expected Structures.MainHeaderSchema");
	failed = true;
}

const extRoot = index.resolveMembers("Ext", true);
if (!extRoot.some((m) => m.name === "isEmpty")) {
	console.error("Expected Ext.isEmpty");
	failed = true;
} else {
	console.log("Ext. members=", extRoot.length);
}
const extString = index.resolveMembers("Ext.String", true);
if (!extString.some((m) => m.name === "format")) {
	console.error("Expected Ext.String.format");
	failed = true;
} else {
	console.log("Ext.String OK", extString.length);
}

const nested = index.resolveMembers("BPMSoft.DataValueType", true);
if (!nested.some((m) => m.name === "BOOLEAN")) {
	console.error("Missing DataValueType.BOOLEAN");
	failed = true;
}

// --- conf Structures parse ---
const leadConf = fs
	.readFileSync(path.join(root, "conf/content/LeadPageV2.js"), "utf8")
	.slice(0, 2500);
const leadStruct = parseStructuresLine(leadConf, "LeadPageV2");
console.log(
	"LeadPageV2 structureParent=",
	leadStruct?.structureParent,
	"stackLen=",
	leadStruct?.innerHierarchyStack?.length
);
if (!leadStruct || leadStruct.structureParent !== "BaseLeadPage") {
	console.error("Failed to parse LeadPageV2 Structures");
	failed = true;
}
const leadExtend = parseStructurePlatformExtend(leadConf);
if (leadExtend !== "BPMSoft.model.BaseViewModel") {
	console.error("Expected LeadPageV2 Structure extend BPMSoft.model.BaseViewModel", leadExtend);
	failed = true;
}
const baseDataViewConf = fs
	.readFileSync(path.join(root, "conf/content/BaseDataView.js"), "utf8")
	.slice(0, 2500);
const baseDvExtend = parseStructurePlatformExtend(baseDataViewConf);
if (baseDvExtend !== "BPMSoft.model.BaseViewModel") {
	console.error("Expected BaseDataView Structure extend BPMSoft.model.BaseViewModel", baseDvExtend);
	failed = true;
}
if (packageFromStackEntry("LeadPageV2", "LeadPageV2OrderLead") !== "OrderLead") {
	console.error("packageFromStackEntry failed");
	failed = true;
}

const layers = index.hierarchy.resolveSchemaLayers("LeadPageV2");
console.log(
	"LeadPageV2 layers:",
	layers.length,
	layers
		.slice(0, 6)
		.map((l) => `${l.source}:${path.basename(l.filePath)}`)
		.join(", "),
	"..."
);
if (layers.length < 10) {
	console.error("Expected deep LeadPageV2 hierarchy layers");
	failed = true;
}
if (!layers.some((l) => /GoRestaurantsMain/.test(l.filePath))) {
	console.error("Expected GoRestaurantsMain Pkg-extra in LeadPageV2 layers");
	failed = true;
}
if (!layers.some((l) => /LeadPageV2\.Lead\.js/.test(l.filePath))) {
	console.error("Expected Autogenerated LeadPageV2.Lead.js in stack");
	failed = true;
}
if (!layers.some((l) => /BaseLeadPage/.test(l.filePath))) {
	console.error("Expected structureParent BaseLeadPage layers");
	failed = true;
}

if (
	parseDescriptorParent(
		'\uFEFF{"Descriptor":{"Parent":{"UId":"x","Name":"BaseModulePageV2"}}}'
	) !== "BaseModulePageV2"
) {
	console.error("parseDescriptorParent failed on Descriptor.Parent.Name");
	failed = true;
}
if (
	parseDescriptorParent(
		'{"Descriptor":{"Name":"FooPage","Parent":{"Name":"FooPage"},"ExtendParent":true}}'
	) !== "FooPage"
) {
	console.error("parseDescriptorParent should still read same-name Parent");
	failed = true;
}
if (shouldWalkDescriptorParent("FooPage", "FooPage", new Set())) {
	console.error("same-name descriptor Parent must not be walked (cycle)");
	failed = true;
}
if (!shouldWalkDescriptorParent("FooPage", "BaseModulePageV2", new Set())) {
	console.error("different-name descriptor Parent should be walked");
	failed = true;
}
if (shouldWalkDescriptorParent("FooPage", "BarPage", new Set(["BarPage"]))) {
	console.error("already visited parent must not be walked (A→B→A)");
	failed = true;
}

const bookingRel =
	"BPMSoft.Configuration/Pkg/GoRestaurantsMain/Schemas/GoBookingOpportunityBasePage/GoBookingOpportunityBasePage.js";
const bookingPath = path.join(root, bookingRel);
const bookingConf = path.join(root, "conf/content/GoBookingOpportunityBasePage.js");
if (!fs.existsSync(bookingPath)) {
	console.error("MISSING", bookingPath);
	failed = true;
} else if (fs.existsSync(bookingConf)) {
	console.error("Expected GoBookingOpportunityBasePage to be absent from conf/content");
	failed = true;
} else {
	const descPath = path.join(path.dirname(bookingPath), "descriptor.json");
	const descParent = parseDescriptorParent(fs.readFileSync(descPath, "utf8"));
	if (descParent !== "BaseModulePageV2") {
		console.error("Expected descriptor Parent BaseModulePageV2", descParent);
		failed = true;
	}
	const bookingMod = parseAmdModule(fs.readFileSync(bookingPath, "utf8"), bookingPath);
	if (!bookingMod) {
		console.error("Failed to parse GoBookingOpportunityBasePage");
		failed = true;
	} else {
		index.upsertModule(bookingMod);
		const bookingLayers = index.hierarchy.resolveSchemaLayers(
			"GoBookingOpportunityBasePage",
			bookingPath
		);
		if (!bookingLayers.some((l) => /BaseModulePageV2/.test(l.filePath))) {
			console.error(
				"Expected descriptor parent BaseModulePageV2 in layers",
				bookingLayers.map((l) => path.basename(l.filePath)).slice(0, 12)
			);
			failed = true;
		}
		if (!bookingLayers.some((l) => /BaseEntityPage/.test(l.filePath))) {
			console.error("Expected BaseEntityPage via BaseModulePageV2 structureParent chain");
			failed = true;
		}
		const bookingThis = index.resolveThisMembers(bookingPath);
		if (!bookingThis.some((m) => m.name === "loadLookupDisplayValue" && m.kind === "method")) {
			console.error(
				"Expected this.loadLookupDisplayValue from BaseEntityPage via descriptor parent"
			);
			failed = true;
		} else {
			console.log(
				"descriptor parent fallback OK",
				bookingLayers.length,
				"layers, loadLookupDisplayValue"
			);
		}
	}
}

// Rightmost stack wins: bare LeadPageV2 → EventTracking in this volume
const orderLead = layers.find((l) => /LeadPageV2\.OrderLead\.js/.test(l.filePath));
const eventTracking = layers.find((l) =>
	/LeadPageV2\.EventTracking\.js/.test(l.filePath)
);
if (orderLead && eventTracking) {
	if (layers.indexOf(eventTracking) >= layers.indexOf(orderLead)) {
		console.error(
			"Expected EventTracking (rightmost/top) before OrderLead in child→parent order"
		);
		failed = true;
	}
}

const leadPath = path.join(root, samples[1]);
const thisMembers = index.resolveThisMembers(leadPath);
console.log(
	"LeadPageV2 this. members:",
	thisMembers.length,
	"sample detail=",
	thisMembers.find((m) => m.name === "onEntityInitialized")?.detail ||
		thisMembers[0]?.detail
);
if (thisMembers.length < 50) {
	console.error("Expected rich this. members from hierarchy");
	failed = true;
}
const leadIndustryCol = thisMembers.find((m) => m.name === "Industry" && m.kind === "attribute");
const leadTitleCol = thisMembers.find((m) => m.name === "Title" && m.kind === "attribute");
if (!leadTitleCol) {
	console.error("Expected Lead entity column this.$Title from conf/content/Lead.js");
	failed = true;
}
if (!leadIndustryCol?.children?.some((c) => c.name === "displayValue")) {
	console.error("Expected Lead.Industry lookup fields value/displayValue");
	failed = true;
} else {
	console.log("Lead entity columns OK", "Title", !!leadTitleCol, "Industry.lookup", true);
}
const platformGet = thisMembers.find((m) => m.name === "get" && m.kind === "method");
const platformDestroy = thisMembers.find((m) => m.name === "destroy");
if (!platformGet) {
	console.error("Expected this.get from BPMSoft.model.BaseModel via Structure extend");
	failed = true;
}
if (!platformDestroy) {
	console.error("Expected this.destroy from BPMSoft.core.BaseObject via extend chain");
	failed = true;
} else {
	console.log(
		"platform this.get/destroy OK",
		platformGet?.detail,
		platformDestroy.detail
	);
}
const schemaVmMethod = thisMembers.find(
	(m) => m.name === "getButtonMenuItem" && m.kind === "method"
);
if (!schemaVmMethod) {
	console.error(
		"Expected this.getButtonMenuItem from BPMSoft.BaseSchemaViewModel"
	);
	failed = true;
} else {
	console.log("BaseSchemaViewModel this.getButtonMenuItem OK", schemaVmMethod.detail);
}
const thisExt = thisMembers.find((m) => m.name === "Ext");
const thisBpmsoft = thisMembers.find((m) => m.name === "BPMSoft");
const thisSandbox = thisMembers.find((m) => m.name === "sandbox");
const sandboxApi = ["publish", "subscribe", "loadModule", "registerMessages"];
if (!thisExt || !thisBpmsoft || !thisSandbox) {
	console.error("Expected this.Ext / this.BPMSoft / this.sandbox on schema");
	failed = true;
} else if (
	!sandboxApi.every((name) => thisSandbox.children?.some((c) => c.name === name))
) {
	console.error("Expected this.sandbox.publish/subscribe/loadModule");
	failed = true;
} else {
	console.log(
		"this.Ext/BPMSoft/sandbox OK",
		"sandbox children=",
		thisSandbox.children?.length || 0
	);
	const loadMod = thisSandbox.children?.find((c) => c.name === "loadModule");
	if (
		!loadMod?.filePath ||
		!/core-base\.js$/i.test(loadMod.filePath) ||
		loadMod.position == null
	) {
		console.error("Expected this.sandbox.loadModule Go to Definition in core-base.js");
		failed = true;
	}
}

const headerPath = path.join(root, samples[3]);
const headerThis = index.resolveThisMembers(headerPath);
const hasSetSettings = headerThis.some((m) => m.name === "setSettings");
const headerHits = index.findThisMemberLocations(headerPath, "setSettings");
console.log(
	"MainHeaderSchema this.setSettings?",
	hasSetSettings,
	"locations=",
	headerHits.map((h) => path.basename(h.module.filePath)).join(", ")
);
if (!hasSetSettings) {
	console.error("Expected setSettings via hierarchy");
	failed = true;
}

const gridPath = path.join(root, samples[6]);
const gridThis = index.resolveThisMembers(gridPath);
if (!gridThis.some((m) => m.name === "formatCellContent")) {
	console.error("Expected Grid parent methods on GoPersonalDataGrid");
	failed = true;
} else {
	console.log("GoPersonalDataGrid override→Grid OK");
}

const wsOverridePath = path.join(root, samples[8]);
const wsThis = index.resolveThisMembers(wsOverridePath);
if (!wsThis.some((m) => m.name === "getFilterCollectionResult")) {
	console.error("Expected WSFieldManagementMixin parent method");
	failed = true;
} else {
	console.log("GoWSFieldManagementMixinOverride OK");
}
if (!wsThis.some((m) => m.name === "colorTimeout" && m.kind === "property")) {
	console.error("Expected colorTimeout property from parent mixin");
	failed = true;
} else {
	console.log("GoWSFieldManagementMixinOverride this.colorTimeout OK");
}

const syntheticChild = parseAmdModule(
	`
define("GoPropChild", [], function() {
	return {
		entitySchemaName: "Lead",
		properties: {
			childFlag: true,
			titleText: "hello"
		},
		methods: {
			onEntityInitialized: function() {}
		}
	};
});
`,
	path.join(root, "synthetic/GoPropChild.js")
);
const syntheticParent = parseAmdModule(
	`
define("GoPropParent", [], function() {
	return {
		entitySchemaName: "Lead",
		properties: {
			parentProp: "from-parent",
			titleText: "parent-title"
		},
		methods: {
			parentMethod: function() {}
		}
	};
});
`,
	path.join(root, "synthetic/GoPropParent.js")
);
if (!syntheticChild || !syntheticParent) {
	console.error("Failed to parse synthetic property schemas");
	failed = true;
} else {
	index.upsertModule(syntheticParent);
	index.upsertModule(syntheticChild);
	const childProps = syntheticChild.members.filter((m) => m.kind === "property");
	const parentProps = syntheticParent.members.filter((m) => m.kind === "property");
	console.log(
		"synthetic properties: child=",
		childProps.map((m) => m.name).join(","),
		"parent=",
		parentProps.map((m) => m.name).join(",")
	);
	if (!childProps.some((m) => m.name === "titleText" && m.documentation === '"hello"')) {
		console.error("Expected child property titleText with literal preview");
		failed = true;
	}
	if (!childProps.some((m) => m.name === "childFlag")) {
		console.error("Expected childFlag property");
		failed = true;
	}
	if (syntheticChild.members.some((m) => m.name === "onEntityInitialized" && m.kind !== "method")) {
		console.error("Expected onEntityInitialized to remain a method");
		failed = true;
	}
	const childThis = index.resolveThisMembers(syntheticChild.filePath);
	if (!childThis.some((m) => m.name === "titleText" && m.kind === "property")) {
		console.error("Expected this.titleText from properties");
		failed = true;
	}
	const titleHits = index.findThisMemberLocations(
		syntheticChild.filePath,
		"titleText"
	);
	if (!titleHits.length || titleHits[0].member.kind !== "property") {
		console.error("Expected Go to Definition for this.titleText");
		failed = true;
	}
}

const syntheticMixin = parseAmdModule(
	`
define("GoSynthMixin", [], function() {
	Ext.define("BPMSoft.configuration.mixins.GoSynthMixin", {
		alternateClassName: "BPMSoft.GoSynthMixin",
		colorTimeout: 0,
		_secretProp: 1,
		getFilterCollectionResult: function() {},
		_secret: function() {}
	});
	return Ext.create("BPMSoft.configuration.mixins.GoSynthMixin");
});
`,
	path.join(root, "synthetic/GoSynthMixin.js")
);
const syntheticOverride = parseAmdModule(
	`
define("GoSynthMixinOverride", ["GoSynthMixin"], function() {
	Ext.define("BPMSoft.configuration.mixins.GoSynthMixinOverride", {
		override: "BPMSoft.GoSynthMixin",
		maxColoringRetryCount: 50,
		getFieldsColors: function() {}
	});
});
`,
	path.join(root, "synthetic/GoSynthMixinOverride.js")
);
if (!syntheticMixin || !syntheticOverride) {
	console.error("Failed to parse synthetic mixin/override");
	failed = true;
} else {
	index.upsertModule(syntheticMixin);
	index.upsertModule(syntheticOverride);
	if (!syntheticMixin.members.some((m) => m.name === "colorTimeout" && m.kind === "property")) {
		console.error("Expected mixin root property colorTimeout");
		failed = true;
	}
	if (syntheticMixin.members.some((m) => m.name === "alternateClassName")) {
		console.error("Did not expect Ext.define meta key alternateClassName as member");
		failed = true;
	}
	const overrideThis = index.resolveThisMembers(syntheticOverride.filePath);
	if (!overrideThis.some((m) => m.name === "colorTimeout" && m.kind === "property")) {
		console.error("Expected this.colorTimeout from parent mixin");
		failed = true;
	}
	if (!overrideThis.some((m) => m.name === "maxColoringRetryCount")) {
		console.error("Expected this.maxColoringRetryCount from override");
		failed = true;
	}
	const colorHits = index.findThisMemberLocations(
		syntheticOverride.filePath,
		"colorTimeout"
	);
	if (!colorHits.length) {
		console.error("Expected Go to Definition for this.colorTimeout");
		failed = true;
	} else {
		console.log("synthetic mixin this.colorTimeout OK");
	}
}

const syntheticMixinPage = parseAmdModule(
	`
define("GoSynthMixinPage", [], function() {
	return {
		mixins: {
			GoSynthMixin: "BPMSoft.GoSynthMixin"
		},
		methods: {
			foo: function() {
				this.GoSynthMixin.getFilterCollectionResult();
				this.mixins.GoSynthMixin.getFilterCollectionResult();
				this.mixins.MissingMixin;
			}
		}
	};
});
`,
	path.join(root, "synthetic/GoSynthMixinPage.js")
);
if (!syntheticMixinPage || !syntheticMixin) {
	console.error("Failed to parse synthetic mixin page");
	failed = true;
} else {
	index.upsertModule(syntheticMixinPage);
	const pageThis = index.resolveThisMembers(syntheticMixinPage.filePath);
	const mixinNs = pageThis.find((m) => m.name === "GoSynthMixin" && m.kind === "namespace");
	if (!mixinNs?.children?.some((m) => m.name === "getFilterCollectionResult")) {
		console.error("Expected this.GoSynthMixin.getFilterCollectionResult from mixins block", mixinNs);
		failed = true;
	}
	const mixinsBag = pageThis.find((m) => m.name === "mixins");
	if (!mixinsBag?.children?.some((m) => m.name === "GoSynthMixin")) {
		console.error("Expected this.mixins.GoSynthMixin", mixinsBag);
		failed = true;
	}
	const nested = index.resolveThisPathMembers(syntheticMixinPage.filePath, "mixins.GoSynthMixin");
	if (!nested.some((m) => m.name === "getFilterCollectionResult")) {
		console.error("Expected nested mixin members via this.mixins.GoSynthMixin", nested.map((m) => m.name));
		failed = true;
	}
	const secret = nested.find((m) => m.name === "_secret");
	if (
		!secret?.filePath ||
		!isPrivateMemberFromOtherFile("_secret", secret.filePath, syntheticMixinPage.filePath)
	) {
		console.error("Expected mixin _secret to be foreign private for the page", secret);
		failed = true;
	}
	const localPrivate = pageThis.find((m) => m.name === "_secret");
	if (!localPrivate?.filePath) {
		console.error("Expected flattened this._secret from mixin");
		failed = true;
	} else if (
		!isPrivateMemberFromOtherFile(
			"_secret",
			localPrivate.filePath,
			syntheticMixinPage.filePath
		)
	) {
		console.error("Expected flattened this._secret to be foreign private for the page");
		failed = true;
	}
	const mixinAccesses = collectThisMemberAccesses(`
		this.mixins.GoSynthMixin.foo();
		this.mixins.GoSynthMixin.missingProp;
		this.mixins.MissingMixin;
		this.GoSynthMixin.bar();
		this.mixins.GoSynthMixin.getFilterCollectionResult();
	`);
	if (!mixinAccesses.some((a) => a.kind === "mixin" && a.name === "GoSynthMixin")) {
		console.error("collectThisMemberAccesses missing mixin access", mixinAccesses);
		failed = true;
	}
	if (!mixinAccesses.some((a) => a.kind === "mixin" && a.name === "MissingMixin")) {
		console.error("collectThisMemberAccesses missing unknown mixin", mixinAccesses);
		failed = true;
	}
	if (
		!mixinAccesses.some(
			(a) =>
				a.kind === "mixinMethod" &&
				a.name === "foo" &&
				a.mixinName === "GoSynthMixin"
		)
	) {
		console.error("collectThisMemberAccesses missing mixinMethod", mixinAccesses);
		failed = true;
	}
	if (
		!mixinAccesses.some(
			(a) =>
				a.kind === "mixinProperty" &&
				a.name === "missingProp" &&
				a.mixinName === "GoSynthMixin"
		)
	) {
		console.error("collectThisMemberAccesses missing mixinProperty", mixinAccesses);
		failed = true;
	}
	if (
		!mixinAccesses.some(
			(a) =>
				a.kind === "mixinMethod" &&
				a.name === "bar" &&
				a.mixinName === "GoSynthMixin"
		)
	) {
		console.error("collectThisMemberAccesses missing this.Mixin.bar()", mixinAccesses);
		failed = true;
	}
	const knownMethod = mixinAccesses.find(
		(a) =>
			a.kind === "mixinMethod" && a.name === "getFilterCollectionResult"
	);
	if (!knownMethod) {
		console.error("collectThisMemberAccesses missing known mixin method", mixinAccesses);
		failed = true;
	}
	console.log("synthetic schema mixin accessors OK");
}

const syntheticMixinParentClass = parseAmdModule(
	`
define("GoSynthMixinParentClass", [], function() {
	Ext.define("BPMSoft.GoSynthMixinParentClass", {
		mixins: {
			GoSynthMixin: "BPMSoft.GoSynthMixin"
		}
	});
});
`,
	path.join(root, "synthetic/GoSynthMixinParentClass.js")
);
const syntheticMixinChildClass = parseAmdModule(
	`
define("GoSynthMixinChildClass", [], function() {
	Ext.define("BPMSoft.GoSynthMixinChildClass", {
		extend: "BPMSoft.GoSynthMixinParentClass",
		childMethod: function() {}
	});
});
`,
	path.join(root, "synthetic/GoSynthMixinChildClass.js")
);
if (!syntheticMixinParentClass || !syntheticMixinChildClass) {
	console.error("Failed to parse synthetic mixin inherit classes");
	failed = true;
} else {
	index.upsertModule(syntheticMixinParentClass);
	index.upsertModule(syntheticMixinChildClass);
	const childThis = index.resolveThisMembers(syntheticMixinChildClass.filePath);
	if (!childThis.some((m) => m.name === "GoSynthMixin" && m.kind === "namespace")) {
		console.error("Expected inherited mixin on this. from parent Ext.define mixins");
		failed = true;
	}
	const inherited = index.resolveThisPathMembers(
		syntheticMixinChildClass.filePath,
		"mixins.GoSynthMixin"
	);
	if (!inherited.some((m) => m.name === "getFilterCollectionResult")) {
		console.error("Expected inherited this.mixins.GoSynthMixin methods", inherited.map((m) => m.name));
		failed = true;
	} else {
		console.log("synthetic inherited mixin accessors OK");
	}
}

const overrideSrc = `
define("LeadPageV2", [], function() {
	return {
		attributes: {
			Foo: {}
		},
		methods: {
			foo: function() {
				var inside = 1;
			},
			onEnt
		}
	};
});
`;
const ovAtKey = getOverrideInsertContext(overrideSrc, overrideSrc.indexOf("onEnt") + 5);
const ovInsideFn = getOverrideInsertContext(overrideSrc, overrideSrc.indexOf("inside"));
const ovInAttrs = getOverrideInsertContext(
	overrideSrc,
	overrideSrc.indexOf("Foo:")
);
if (!ovAtKey || ovAtKey.kind !== "methods" || ovAtKey.typed !== "onEnt") {
	console.error("Expected override context at methods key", ovAtKey);
	failed = true;
} else {
	console.log("override context in methods OK");
}
const localKeys = collectLocalMethodKeys(
	overrideSrc,
	overrideSrc.lastIndexOf("onEnt"),
	overrideSrc.lastIndexOf("onEnt") + 5
);
if (!localKeys.has("foo")) {
	console.error("Expected local methods to include existing foo");
	failed = true;
}
if (localKeys.has("onEnt")) {
	console.error("Did not expect the name currently being typed as a local method");
	failed = true;
}
if (ovInsideFn) {
	console.error("Did not expect override context inside method body");
	failed = true;
}
if (ovInAttrs) {
	console.error("Did not expect override context in attributes");
	failed = true;
}
const classSrc = `
Ext.define("BPMSoft.GoOvChild", {
	override: "BPMSoft.GoOvBase",
	onEnt
});
`;
const ovClass = getOverrideInsertContext(classSrc, classSrc.indexOf("onEnt") + 5);
if (!ovClass || ovClass.kind !== "class") {
	console.error("Expected override context in Ext.define class body", ovClass);
	failed = true;
}
const snippet = formatOverrideSnippet(
	"BPMSoft.BasePageV2",
	"onEntityInitialized"
);
if (
	!snippet.includes("@inheritdoc BPMSoft.BasePageV2#onEntityInitialized") ||
	!snippet.includes("@overriden") ||
	!snippet.includes("onEntityInitialized: function () {") ||
	snippet.split("\n").some((line, i) => i > 0 && line.startsWith("\t\t"))
) {
	console.error("Unexpected override snippet", snippet);
	failed = true;
}

if (syntheticOverride) {
	const overridable = index.resolveOverridableMethods(syntheticOverride.filePath);
	const parentHook = overridable.find((m) => m.name === "getFilterCollectionResult");
	if (!parentHook || parentHook.owner !== "BPMSoft.GoSynthMixin") {
		console.error(
			"Expected overridable getFilterCollectionResult from mixin parent",
			parentHook
		);
		failed = true;
	} else if (overridable.some((m) => m.name === "getFieldsColors")) {
		console.error("Did not expect current-file method in overridable list");
		failed = true;
	} else {
		console.log("overridable methods OK", parentHook.owner);
	}
}

const syntheticAttrChild = parseAmdModule(
	`
define("GoAttrChild", [], function() {
	return {
		entitySchemaName: "Lead",
		attributes: {
			"ChildFlag": {
				dataValueType: BPMSoft.DataValueType.BOOLEAN,
				value: true
			},
			"TitleText": {
				dataValueType: BPMSoft.DataValueType.TEXT,
				value: "hello"
			},
			"SearchFieldFilterList": {
				dataValueType: BPMSoft.DataValueType.ENUM
			},
			"Owner": {
				dataValueType: BPMSoft.DataValueType.LOOKUP
			}
		},
		methods: {
			onEntityInitialized: function() {
				this.get("TitleText");
				this.set("ChildFlag", false);
				this.$TitleText = "x";
			}
		}
	};
});
`,
	path.join(root, "synthetic/GoAttrChild.js")
);
const syntheticAttrParent = parseAmdModule(
	`
define("GoAttrChild", [], function() {
	return {
		entitySchemaName: "Lead",
		attributes: {
			"ParentAttr": {
				dataValueType: BPMSoft.DataValueType.INTEGER,
				value: 1
			},
			"TitleText": {
				dataValueType: BPMSoft.DataValueType.TEXT,
				value: "parent"
			}
		}
	};
});
`,
	path.join(root, "synthetic/GoAttrParent.js")
);
if (!syntheticAttrChild || !syntheticAttrParent) {
	console.error("Failed to parse synthetic attribute schemas");
	failed = true;
} else {
	const attrIndex = new SymbolIndex();
	attrIndex.upsertModule(syntheticAttrParent);
	attrIndex.upsertModule(syntheticAttrChild);
	const childAttrs = syntheticAttrChild.members.filter((m) => m.kind === "attribute");
	if (!childAttrs.some((m) => m.name === "TitleText")) {
		console.error("Expected TitleText attribute");
		failed = true;
	}
	if (!childAttrs.some((m) => m.documentation && m.documentation.includes("DataValueType.TEXT"))) {
		console.error("Expected attribute dataValueType in documentation");
		failed = true;
	}
	const attrThis = attrIndex.resolveThisMembers(syntheticAttrChild.filePath);
	if (!attrThis.some((m) => m.name === "TitleText" && m.kind === "attribute")) {
		console.error("Expected this.$TitleText from attributes");
		failed = true;
	}
	if (!attrThis.some((m) => m.name === "ParentAttr" && m.kind === "attribute")) {
		console.error("Expected parent attribute ParentAttr via same-name replacement");
		failed = true;
	}
	const dollarHits = attrIndex.findThisMemberLocations(
		syntheticAttrChild.filePath,
		"$TitleText"
	);
	if (!dollarHits.length || dollarHits[0].member.kind !== "attribute") {
		console.error("Expected Go to Definition for this.$TitleText");
		failed = true;
	}
	const getHits = attrIndex.findThisMemberLocations(
		syntheticAttrChild.filePath,
		"TitleText",
		"attribute"
	);
	if (!getHits.length) {
		console.error("Expected Go to Definition for this.get(\"TitleText\")");
		failed = true;
	}
	const src = "this.get(\"TitleText\"); this.set(\"ChildFlag\", 1);";
	const getCtx = getThisGetSetContext(src, src.indexOf("TitleText") + 2);
	const setCtx = getThisGetSetContext(src, src.indexOf("ChildFlag") + 2);
	if (!getCtx || getCtx.method !== "get" || getCtx.name !== "TitleText") {
		console.error("getThisGetSetContext failed for this.get");
		failed = true;
	}
	if (!setCtx || setCtx.method !== "set" || setCtx.name !== "ChildFlag") {
		console.error("getThisGetSetContext failed for this.set");
		failed = true;
	}
	const enumAttr = childAttrs.find((m) => m.name === "SearchFieldFilterList");
	const lookupAttr = childAttrs.find((m) => m.name === "Owner");
	const textAttr = childAttrs.find((m) => m.name === "TitleText");
	if (!enumAttr?.children?.some((c) => c.name === "value") ||
		!enumAttr?.children?.some((c) => c.name === "displayValue")) {
		console.error("Expected ENUM attribute children value/displayValue");
		failed = true;
	}
	if (!lookupAttr?.children?.some((c) => c.name === "displayValue")) {
		console.error("Expected LOOKUP attribute children value/displayValue");
		failed = true;
	}
	if (textAttr?.children?.length) {
		console.error("Did not expect nested fields on TEXT attribute");
		failed = true;
	}
	const dollarLookup = "this.$SearchFieldFilterList.";
	const getLookup = 'this.get("Owner").';
	const dollarCtx = getThisLookupAccessContext(dollarLookup, dollarLookup.length);
	const getLookupCtx = getThisLookupAccessContext(getLookup, getLookup.length);
	if (!dollarCtx || dollarCtx.attrName !== "SearchFieldFilterList") {
		console.error("getThisLookupAccessContext failed for this.$Enum.");
		failed = true;
	}
	if (!getLookupCtx || getLookupCtx.attrName !== "Owner") {
		console.error("getThisLookupAccessContext failed for this.get(\"Lookup\").");
		failed = true;
	}
	const getInsideDot = 'this.get("Owner".';
	const getValue = 'this.get("Owner").value';
	const getInsideCtx = getThisLookupAccessContext(getInsideDot, getInsideDot.length);
	const getValueCtx = getThisLookupAccessContext(getValue, getValue.length);
	if (!getInsideCtx || getInsideCtx.attrName !== "Owner") {
		console.error("getThisLookupAccessContext failed for this.get(\"Owner\".");
		failed = true;
	}
	if (!getValueCtx || getValueCtx.attrName !== "Owner") {
		console.error("getThisLookupAccessContext failed for this.get(\"Owner\").value");
		failed = true;
	} else {
		console.log("synthetic attributes this.$ / get / set OK");
	}
}

const syntheticEntityCols = parseEntityColumns(
	`
define("Account", ["BPMSoft"], function(BPMSoft) {
	Ext.define("BPMSoft.data.models.Account", {
		extend: "BPMSoft.BaseEntitySchema",
		columns: {
			Id: {
				dataValueType: BPMSoft.DataValueType.GUID,
				isRequired: true
			},
			Name: {
				dataValueType: BPMSoft.DataValueType.TEXT
			},
			Owner: {
				dataValueType: BPMSoft.DataValueType.LOOKUP,
				isLookup: true,
				referenceSchemaName: "Contact"
			}
		}
	});
});
`,
	"/tmp/conf/content/Account.js"
);
if (!syntheticEntityCols.some((m) => m.name === "Name" && m.kind === "attribute")) {
	console.error("Expected entity column Name");
	failed = true;
}
if (!syntheticEntityCols.some((m) => m.name === "Owner" && m.children?.some((c) => c.name === "value"))) {
	console.error("Expected entity LOOKUP Owner.value");
	failed = true;
} else {
	console.log("synthetic entity columns OK", syntheticEntityCols.map((m) => m.name).join(","));
}

{
	const schemaSrc = `
define("FooPage", [], function() {
	return {
		entitySchemaName: "Foo",
		attributes: {
			ExistingAttr: { dataValueType: BPMSoft.DataValueType.TEXT }
		},
		properties: {
			existingProp: null
		},
		methods: {
			existingMethod: function() {
				this.missingMethod(entity);
				this.existingMethod();
				this.missingProp;
				this.$MissingAttr;
				this.get("MissingGet");
				this.set("ExistingAttr", 1);
				this.sandbox;
			}
		}
	};
});
`;
	const accesses = collectThisMemberAccesses(schemaSrc);
	const byKey = (kind, name) =>
		accesses.find((a) => a.kind === kind && a.name === name);
	if (!byKey("methodCall", "missingMethod")?.argNames?.includes("entity")) {
		console.error("collectThisMemberAccesses missing methodCall", accesses);
		failed = true;
	}
	if (!byKey("bare", "missingProp") || !byKey("bare", "sandbox")) {
		console.error("collectThisMemberAccesses missing bare access", accesses);
		failed = true;
	}
	if (!byKey("attribute", "MissingAttr") || !byKey("attribute", "MissingGet")) {
		console.error("collectThisMemberAccesses missing attribute access", accesses);
		failed = true;
	}
	if (byKey("methodCall", "get") || byKey("methodCall", "set")) {
		console.error("collectThisMemberAccesses should not flag get/set as methods");
		failed = true;
	}
	const methodInsert = planCreateMemberInsert(schemaSrc, "method", "newOne", ["a"]);
	if (!methodInsert || !methodInsert.text.includes("newOne: function (a)")) {
		console.error("planCreateMemberInsert method failed", methodInsert);
		failed = true;
	}
	const noMethods = `define("X", [], function() { return { entitySchemaName: "E", diff: [] }; });`;
	const sectionInsert = planCreateMemberInsert(noMethods, "method", "init");
	if (!sectionInsert || !sectionInsert.text.includes("methods:")) {
		console.error("planCreateMemberInsert should create methods section", sectionInsert);
		failed = true;
	}
	const extSrc = `Ext.define("BPMSoft.Foo", { extend: "BPMSoft.Bar", init: function() {} });`;
	const propInsert = planCreateMemberInsert(extSrc, "property", "flag");
	if (!propInsert || !propInsert.text.includes("flag: null")) {
		console.error("planCreateMemberInsert Ext property failed", propInsert);
		failed = true;
	} else {
		console.log("this-member diagnostics parse/insert OK");
	}
}

{
	const privateSrc = `
define("BasePageV2", [], function() {
	return {
		methods: {
			_closePage: function(silentMode) {
				this._closePage();
			}
		}
	};
});
`;
	const privateMod = parseAmdModule(privateSrc, path.join(root, "synthetic/BasePageV2Private.js"));
	if (!privateMod?.members.some((m) => m.name === "_closePage" && m.kind === "method")) {
		console.error("Expected _closePage to be indexed (underscore methods)");
		failed = true;
	} else if (
		isPrivateMemberFromOtherFile(
			"_closePage",
			privateMod.filePath,
			privateMod.filePath
		)
	) {
		console.error("Same-file this._closePage must not be treated as foreign private");
		failed = true;
	} else {
		console.log("underscore this._closePage indexed OK");
	}
}

{
	const emptyFnSrc = `
define("BasePageV2", [], function() {
	return {
		methods: {
			getIncrementColumn: this.BPMSoft.emptyFn,
			foo: function() {
				this.getIncrementColumn();
			}
		}
	};
});
`;
	const emptyFnMod = parseAmdModule(emptyFnSrc, path.join(root, "synthetic/EmptyFnPage.js"));
	if (
		!emptyFnMod?.members.some(
			(m) => m.name === "getIncrementColumn" && m.kind === "method"
		)
	) {
		console.error("Expected getIncrementColumn: this.BPMSoft.emptyFn to be a method");
		failed = true;
	} else {
		console.log("emptyFn stub method indexed OK");
	}
}

if (failed) {
	console.error("SMOKE FAILED");
	process.exit(1);
}
console.log("SMOKE PASSED");
