import * as vscode from "vscode";
import { SymbolIndex } from "./index/SymbolIndex";
import { ModuleIndexer } from "./index/ModuleIndexer";
import { resolveAppLayouts } from "./index/workspaceLayout";
import { BpmsoftCompletionProvider } from "./providers/CompletionProvider";
import { BpmsoftDefinitionProvider } from "./providers/DefinitionProvider";
import { BpmsoftHoverProvider } from "./providers/HoverProvider";
import { MissingMemberDiagnostics } from "./providers/MissingMemberDiagnostics";
import {
	CREATE_MEMBER_COMMAND,
	CreateMemberArgs,
	CreateMemberCodeActionProvider,
	executeCreateMember
} from "./providers/CreateMemberCodeActionProvider";

let index: SymbolIndex;
let indexer: ModuleIndexer;
let diagnostics: MissingMemberDiagnostics;

export async function activate(context: vscode.ExtensionContext): Promise<void> {
	index = new SymbolIndex();
	indexer = new ModuleIndexer(index);
	diagnostics = new MissingMemberDiagnostics(index);

	await preferIndexedCompletions();

	const jsSelector: vscode.DocumentSelector = { language: "javascript", scheme: "file" };

	const completionProvider = new BpmsoftCompletionProvider(index);

	context.subscriptions.push(
		diagnostics,
		// After "." — members; without trigger — bare "BPMSoft" / "Ext" while typing
		vscode.languages.registerCompletionItemProvider(
			jsSelector,
			completionProvider,
			".",
			"$",
			"\"",
			"'",
			"("
		),
		vscode.languages.registerCompletionItemProvider(
			jsSelector,
			completionProvider
		),
		vscode.languages.registerDefinitionProvider(
			jsSelector,
			new BpmsoftDefinitionProvider(index)
		),
		vscode.languages.registerHoverProvider(
			jsSelector,
			new BpmsoftHoverProvider(index)
		),
		vscode.languages.registerCodeActionsProvider(
			jsSelector,
			new CreateMemberCodeActionProvider(),
			{ providedCodeActionKinds: [vscode.CodeActionKind.QuickFix] }
		),
		vscode.commands.registerCommand("bpmsoft.rebuildIndex", async () => {
			await rebuildWithProgress();
		}),
		vscode.commands.registerCommand(
			CREATE_MEMBER_COMMAND,
			(args: CreateMemberArgs) => executeCreateMember(args, diagnostics)
		),
		vscode.workspace.onDidChangeTextDocument((e) => {
			diagnostics.schedule(e.document);
		}),
		vscode.workspace.onDidOpenTextDocument((document) => {
			diagnostics.refresh(document);
		}),
		vscode.workspace.onDidCloseTextDocument((document) => {
			diagnostics.clear(document.uri);
			if (document.uri.scheme === "file" && document.languageId === "javascript") {
				void indexer.indexFile(document.uri.fsPath);
			}
		})
	);

	const folders = vscode.workspace.workspaceFolders;
	if (folders?.length) {
		const watchGlobs = [
			"**/Pkg/**/Schemas/**/*.js",
			"**/Autogenerated/Src/*.js",
			"**/Resources/ui/BPMSoft/**/*.js"
		];
		for (const folder of folders) {
			for (const watchGlob of watchGlobs) {
				const watcher = vscode.workspace.createFileSystemWatcher(
					new vscode.RelativePattern(folder, watchGlob)
				);
				watcher.onDidCreate((uri) => void indexer.indexFile(uri.fsPath));
				watcher.onDidChange((uri) => void indexer.indexFile(uri.fsPath));
				watcher.onDidDelete((uri) => indexer.removeFile(uri.fsPath));
				context.subscriptions.push(watcher);
			}
		}
		for (const layout of resolveAppLayouts(folders.map((f) => f.uri.fsPath))) {
			if (!layout.confContent) {
				continue;
			}
			const confWatcher = vscode.workspace.createFileSystemWatcher(
				new vscode.RelativePattern(layout.confContent, "*.js")
			);
			const invalidate = (uri: vscode.Uri) => index.invalidateEntity(uri.fsPath);
			confWatcher.onDidCreate(invalidate);
			confWatcher.onDidChange(invalidate);
			confWatcher.onDidDelete(invalidate);
			context.subscriptions.push(confWatcher);
		}
	}

	await rebuildWithProgress();
}

/**
 * Workspace overrides beat user defaults that keep word/history suggestions on top.
 */
async function preferIndexedCompletions(): Promise<void> {
	const enabled = vscode.workspace
		.getConfiguration("bpmsoft")
		.get<boolean>("preferIndexedCompletions", true);
	if (!enabled || !vscode.workspace.workspaceFolders?.length) {
		return;
	}

	try {
		const jsEditor = vscode.workspace.getConfiguration("editor", {
			languageId: "javascript"
		});
		await jsEditor.update(
			"wordBasedSuggestions",
			"off",
			vscode.ConfigurationTarget.Workspace
		);
		await jsEditor.update(
			"suggestSelection",
			"first",
			vscode.ConfigurationTarget.Workspace
		);
		await jsEditor.update(
			"quickSuggestions",
			{ other: true, comments: false, strings: true },
			vscode.ConfigurationTarget.Workspace
		);

		await vscode.workspace
			.getConfiguration("javascript")
			.update("suggest.names", false, vscode.ConfigurationTarget.Workspace);
	} catch {
		// Workspace may be read-only; configurationDefaults still apply as fallback.
	}
}

async function rebuildWithProgress(): Promise<void> {
	await vscode.window.withProgress(
		{
			location: vscode.ProgressLocation.Window,
			title: "BPMSoft: indexing Pkg + Autogenerated + UI"
		},
		async (progress) => {
			const count = await indexer.rebuild(progress);
			const folders =
				vscode.workspace.workspaceFolders?.map((f) => f.uri.fsPath) || [];
			const layouts = resolveAppLayouts(folders);
			const kind = layouts.map((l) => l.kind).join("/") || "unknown";
			vscode.window.setStatusBarMessage(
				`BPMSoft: indexed ${count} modules (${kind})`,
				5000
			);
			diagnostics.refreshOpenDocuments();
		}
	);
}

export function deactivate(): void {
	// no-op
}
