import * as vscode from "vscode";
import { SymbolIndex } from "./index/SymbolIndex";
import { ModuleIndexer } from "./index/ModuleIndexer";
import { resolveAppLayouts } from "./index/workspaceLayout";
import { ensureDotnetSolution, maybeOfferCsharpExtension } from "./dotnet/ensureDotnetIntellisense";
import { BpmsoftCompletionProvider } from "./providers/CompletionProvider";
import { BpmsoftDefinitionProvider } from "./providers/DefinitionProvider";
import { BpmsoftHoverProvider } from "./providers/HoverProvider";
import { MissingMemberDiagnostics } from "./providers/MissingMemberDiagnostics";
import { StyleDiagnostics } from "./providers/StyleDiagnostics";
import { StyleCodeActionProvider } from "./providers/StyleCodeActionProvider";
import {
	CREATE_MEMBER_COMMAND,
	CreateMemberArgs,
	CreateMemberCodeActionProvider,
	executeCreateMember
} from "./providers/CreateMemberCodeActionProvider";

let index: SymbolIndex;
let indexer: ModuleIndexer;
let diagnostics: MissingMemberDiagnostics;
let styleDiagnostics: StyleDiagnostics;

export async function activate(context: vscode.ExtensionContext): Promise<void> {
	try {
		index = new SymbolIndex();
		indexer = new ModuleIndexer(index);
		diagnostics = new MissingMemberDiagnostics(index);
		styleDiagnostics = new StyleDiagnostics(index);

		const folders = vscode.workspace.workspaceFolders;
		const layouts = resolveAppLayouts(folders?.map((f) => f.uri.fsPath) || []);

		const jsSelector: vscode.DocumentSelector = {
			language: "javascript",
			scheme: "file"
		};
		const csharpSelector: vscode.DocumentSelector = [
			{ language: "csharp" },
			{ pattern: "**/*.cs", scheme: "file" }
		];

		const completionProvider = new BpmsoftCompletionProvider(index);

		context.subscriptions.push(
			diagnostics,
			styleDiagnostics,
			vscode.languages.registerCompletionItemProvider(
				jsSelector,
				completionProvider,
				".",
				"$",
				"\"",
				"'",
				"("
			),
			vscode.languages.registerDefinitionProvider(
				jsSelector,
				new BpmsoftDefinitionProvider(index)
			),
			vscode.languages.registerHoverProvider(
				jsSelector,
				new BpmsoftHoverProvider(index)
			),
			vscode.languages.registerCodeActionsProvider(
				jsSelector,
				new CreateMemberCodeActionProvider(),
				{ providedCodeActionKinds: [vscode.CodeActionKind.QuickFix] }
			),
			vscode.languages.registerCodeActionsProvider(
				jsSelector,
				new StyleCodeActionProvider(),
				{ providedCodeActionKinds: [vscode.CodeActionKind.QuickFix] }
			),
			vscode.languages.registerCodeActionsProvider(
				csharpSelector,
				new StyleCodeActionProvider(),
				{ providedCodeActionKinds: [vscode.CodeActionKind.QuickFix] }
			),
			vscode.commands.registerCommand("bpmsoft.rebuildIndex", async () => {
				await rebuildWithProgress();
			}),
			vscode.commands.registerCommand(
				CREATE_MEMBER_COMMAND,
				(args: CreateMemberArgs) => executeCreateMember(args, diagnostics)
			),
			vscode.workspace.onDidChangeTextDocument((e) => {
				diagnostics.schedule(e.document);
				styleDiagnostics.schedule(e.document);
			}),
			vscode.workspace.onDidOpenTextDocument((document) => {
				diagnostics.refresh(document);
				styleDiagnostics.refresh(document);
				if (document.languageId === "csharp") {
					void maybeOfferCsharpExtension(context);
				}
			}),
			vscode.window.onDidChangeActiveTextEditor((editor) => {
				if (editor) {
					styleDiagnostics.refresh(editor.document);
					if (editor.document.languageId === "csharp") {
						void maybeOfferCsharpExtension(context);
					}
				}
			}),
			vscode.workspace.onDidCloseTextDocument((document) => {
				diagnostics.clear(document.uri);
				styleDiagnostics.clear(document.uri);
				if (
					document.uri.scheme === "file" &&
					document.languageId === "javascript"
				) {
					void indexer.indexFile(document.uri.fsPath);
				}
			}),
			vscode.workspace.onDidChangeConfiguration((e) => {
				if (e.affectsConfiguration("bpmsoft.styleDiagnostics")) {
					styleDiagnostics.refreshOpenDocuments();
				}
			})
		);

		registerWatchers(context, folders, layouts);
		styleDiagnostics.refreshOpenDocuments();

		void preferIndexedCompletions();
		void rebuildWithProgress();
		void ensureDotnetSolution(layouts);
		const active = vscode.window.activeTextEditor?.document;
		if (active?.languageId === "csharp") {
			void maybeOfferCsharpExtension(context);
		}
	} catch (err) {
		const message = err instanceof Error ? err.message : String(err);
		void vscode.window.showErrorMessage(
			`BPMSoft IntelliSense не запустилось: ${message}`
		);
		throw err;
	}
}

function registerWatchers(
	context: vscode.ExtensionContext,
	folders: readonly vscode.WorkspaceFolder[] | undefined,
	layouts: ReturnType<typeof resolveAppLayouts>
): void {
	if (!folders?.length) {
		return;
	}
	const watchGlobs = [
		"**/Pkg/**/Schemas/**/*.js",
		"**/Autogenerated/Src/*.js",
		"**/Resources/ui/BPMSoft/**/*.js"
	];
	for (const folder of folders) {
		for (const watchGlob of watchGlobs) {
			const watcher = vscode.workspace.createFileSystemWatcher(
				new vscode.RelativePattern(folder, watchGlob)
			);
			watcher.onDidCreate((uri) => void indexer.indexFile(uri.fsPath));
			watcher.onDidChange((uri) => void indexer.indexFile(uri.fsPath));
			watcher.onDidDelete((uri) => indexer.removeFile(uri.fsPath));
			context.subscriptions.push(watcher);
		}
	}
	for (const layout of layouts) {
		if (!layout.confContent) {
			continue;
		}
		const confWatcher = vscode.workspace.createFileSystemWatcher(
			new vscode.RelativePattern(layout.confContent, "*.js")
		);
		const onConfJs = (uri: vscode.Uri) => {
			index.invalidateEntity(uri.fsPath);
			if (/Module[^/]*\.js$/i.test(uri.fsPath.replace(/\\/g, "/"))) {
				void indexer.indexFile(uri.fsPath);
			}
		};
		confWatcher.onDidCreate(onConfJs);
		confWatcher.onDidChange(onConfJs);
		confWatcher.onDidDelete((uri) => {
			index.invalidateEntity(uri.fsPath);
			indexer.removeFile(uri.fsPath);
		});
		context.subscriptions.push(confWatcher);
	}
}

/**
 * Workspace overrides beat user defaults that keep word/history suggestions on top.
 */
async function preferIndexedCompletions(): Promise<void> {
	const enabled = vscode.workspace
		.getConfiguration("bpmsoft")
		.get<boolean>("preferIndexedCompletions", true);
	if (!enabled || !vscode.workspace.workspaceFolders?.length) {
		return;
	}

	try {
		const jsEditor = vscode.workspace.getConfiguration("editor", {
			languageId: "javascript"
		});
		await jsEditor.update(
			"wordBasedSuggestions",
			"off",
			vscode.ConfigurationTarget.Workspace
		);
		await jsEditor.update(
			"suggestSelection",
			"first",
			vscode.ConfigurationTarget.Workspace
		);
		await jsEditor.update(
			"quickSuggestions",
			{ other: true, comments: false, strings: true },
			vscode.ConfigurationTarget.Workspace
		);

		await vscode.workspace
			.getConfiguration("javascript")
			.update("suggest.names", false, vscode.ConfigurationTarget.Workspace);
	} catch {
		// Workspace may be read-only; configurationDefaults still apply as fallback.
	}
}

async function rebuildWithProgress(): Promise<void> {
	await vscode.window.withProgress(
		{
			location: vscode.ProgressLocation.Window,
			title: "BPMSoft: indexing Pkg + Autogenerated + UI"
		},
		async (progress) => {
			const count = await indexer.rebuild(progress);
			const folders =
				vscode.workspace.workspaceFolders?.map((f) => f.uri.fsPath) || [];
			const layouts = resolveAppLayouts(folders);
			const kind = layouts.map((l) => l.kind).join("/") || "unknown";
			vscode.window.setStatusBarMessage(
				`BPMSoft: indexed ${count} modules (${kind})`,
				5000
			);
			diagnostics.refreshOpenDocuments();
			styleDiagnostics.refreshOpenDocuments();
		}
	);
}

export function deactivate(): void {
	diagnostics?.clearAll();
	styleDiagnostics?.clearAll();
	index?.clearAll();
}